run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - internal/graph/generated
    - internal/graph/model
