run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
    - revive

issues:
  exclude-dirs:
    - internal/graph/generated
    - internal/graph/model
