package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/graph/model"
)

// SwitchOrg is the resolver for the switchOrg field.
func (r *mutationResolver) SwitchOrg(ctx context.Context, orgID string) (bool, error) {
	return true, r.Client.SwitchOrg(ctx, orgID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	me, err := r.Client.Me(ctx)
	if err != nil {
		return nil, err
	}
	return meToModel(me), nil
}

// MyOrgs is the resolver for the myOrgs field.
func (r *queryResolver) MyOrgs(ctx context.Context) ([]*model.OrgSummary, error) {
	orgs, err := r.Client.MyOrgs(ctx)
	if err != nil {
		return nil, err
	}
	return orgSummariesToModel(orgs), nil
}
