package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/graph/model"
)

// CreateService is the resolver for the createService field.
func (r *mutationResolver) CreateService(ctx context.Context, orgID string, input model.CreateServiceInput) (*model.Service, error) {
	s, err := r.Client.CreateService(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return serviceToModel(s), nil
}

// UpdateService is the resolver for the updateService field.
func (r *mutationResolver) UpdateService(ctx context.Context, orgID string, id string, input model.UpdateServiceInput) (*model.Service, error) {
	s, err := r.Client.UpdateService(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return serviceToModel(s), nil
}

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteService(ctx, orgID, id)
}

// CreateAPIGroup is the resolver for the createAPIGroup field.
func (r *mutationResolver) CreateAPIGroup(ctx context.Context, orgID string, serviceID string, input model.CreateAPIGroupInput) (*model.APIGroup, error) {
	g, err := r.Client.CreateAPIGroup(ctx, orgID, serviceID, toMap(input))
	if err != nil {
		return nil, err
	}
	return apiGroupToModel(g), nil
}

// UpdateAPIGroup is the resolver for the updateAPIGroup field.
func (r *mutationResolver) UpdateAPIGroup(ctx context.Context, orgID string, serviceID string, id string, input model.UpdateAPIGroupInput) (*model.APIGroup, error) {
	g, err := r.Client.UpdateAPIGroup(ctx, orgID, serviceID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return apiGroupToModel(g), nil
}

// DeleteAPIGroup is the resolver for the deleteAPIGroup field.
func (r *mutationResolver) DeleteAPIGroup(ctx context.Context, orgID string, serviceID string, id string) (bool, error) {
	return true, r.Client.DeleteAPIGroup(ctx, orgID, serviceID, id)
}

// SyncAPIGroup is the resolver for the syncAPIGroup field.
func (r *mutationResolver) SyncAPIGroup(ctx context.Context, orgID string, serviceID string, input model.SyncAPIGroupInput) (*model.SyncAPIGroupResult, error) {
	out, err := r.Client.SyncAPIGroup(ctx, orgID, serviceID, toMap(input))
	if err != nil {
		return nil, err
	}
	return &model.SyncAPIGroupResult{
		APIGroupID:     strFromMap(out, "apiGroupId"),
		VersionCreated: boolFromMap(out, "versionCreated"),
	}, nil
}

// CreateAPIEndpoint is the resolver for the createAPIEndpoint field.
func (r *mutationResolver) CreateAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, input model.CreateAPIEndpointInput) (*model.APIEndpoint, error) {
	e, err := r.Client.CreateAPIEndpoint(ctx, orgID, serviceID, apiGroupID, toMap(input))
	if err != nil {
		return nil, err
	}
	return apiEndpointToModel(e), nil
}

// UpdateAPIEndpoint is the resolver for the updateAPIEndpoint field.
func (r *mutationResolver) UpdateAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string, input model.UpdateAPIEndpointInput) (*model.APIEndpoint, error) {
	e, err := r.Client.UpdateAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return apiEndpointToModel(e), nil
}

// DeleteAPIEndpoint is the resolver for the deleteAPIEndpoint field.
func (r *mutationResolver) DeleteAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string) (bool, error) {
	return true, r.Client.DeleteAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id)
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, orgID string, folderID *string) ([]*model.Service, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	services, err := r.Client.ListServices(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return servicesToModel(services), nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, orgID string, id string) (*model.Service, error) {
	s, err := r.Client.GetService(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return serviceToModel(s), nil
}

// APIGroups is the resolver for the apiGroups field.
func (r *queryResolver) APIGroups(ctx context.Context, orgID string, serviceID string) ([]*model.APIGroup, error) {
	groups, err := r.Client.ListAPIGroups(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return apiGroupsToModel(groups), nil
}

// APIGroup is the resolver for the apiGroup field.
func (r *queryResolver) APIGroup(ctx context.Context, orgID string, serviceID string, id string) (*model.APIGroup, error) {
	g, err := r.Client.GetAPIGroup(ctx, orgID, serviceID, id)
	if err != nil {
		return nil, err
	}
	return apiGroupToModel(g), nil
}

// APIGroupVersions is the resolver for the apiGroupVersions field.
func (r *queryResolver) APIGroupVersions(ctx context.Context, orgID string, serviceID string, apiGroupID string) ([]*model.APIGroupVersion, error) {
	versions, err := r.Client.ListAPIGroupVersions(ctx, orgID, serviceID, apiGroupID)
	if err != nil {
		return nil, err
	}
	return apiGroupVersionsToModel(versions), nil
}

// APIEndpoints is the resolver for the apiEndpoints field.
func (r *queryResolver) APIEndpoints(ctx context.Context, orgID string, serviceID string, apiGroupID string) ([]*model.APIEndpoint, error) {
	endpoints, err := r.Client.ListAPIEndpoints(ctx, orgID, serviceID, apiGroupID)
	if err != nil {
		return nil, err
	}
	return apiEndpointsToModel(endpoints), nil
}

// APIEndpoint is the resolver for the apiEndpoint field.
func (r *queryResolver) APIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string) (*model.APIEndpoint, error) {
	e, err := r.Client.GetAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id)
	if err != nil {
		return nil, err
	}
	return apiEndpointToModel(e), nil
}
