package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/graph/generated"
	"github.com/uigraph/graphql/graph/model"
)

// CreatedByActor is the resolver for the createdByActor field.
func (r *commentResolver) CreatedByActor(ctx context.Context, obj *model.Comment) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, orgID string, input model.CreateCommentInput) (*model.Comment, error) {
	c, err := r.Client.CreateComment(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return commentToModel(c), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, orgID string, id string, input model.UpdateCommentInput) (*model.Comment, error) {
	c, err := r.Client.UpdateComment(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return commentToModel(c), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteComment(ctx, orgID, id)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, orgID string, resourceID string) ([]*model.Comment, error) {
	cs, err := r.Client.ListComments(ctx, orgID, resourceID)
	if err != nil {
		return nil, err
	}
	return commentsToModel(cs), nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
