package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/graph/model"
)

func (r *mutationResolver) CreateFolder(ctx context.Context, orgID string, input model.CreateFolderInput) (*model.Folder, error) {
	f, err := r.Client.CreateFolder(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return folderToModel(f), nil
}

func (r *mutationResolver) UpdateFolder(ctx context.Context, orgID string, id string, input model.UpdateFolderInput) (*model.Folder, error) {
	f, err := r.Client.UpdateFolder(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return folderToModel(f), nil
}

func (r *mutationResolver) DeleteFolder(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteFolder(ctx, orgID, id)
}

func (r *mutationResolver) CreateDiagram(ctx context.Context, orgID string, input model.CreateDiagramInput) (*model.Diagram, error) {
	d, err := r.Client.CreateDiagram(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

func (r *mutationResolver) UpdateDiagram(ctx context.Context, orgID string, id string, input model.UpdateDiagramInput) (*model.Diagram, error) {
	d, err := r.Client.UpdateDiagram(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

func (r *mutationResolver) DeleteDiagram(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteDiagram(ctx, orgID, id)
}

func (r *mutationResolver) SyncDiagram(ctx context.Context, orgID string, input model.SyncDiagramInput) (*model.SyncDiagramResult, error) {
	out, err := r.Client.SyncDiagram(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	res := &model.SyncDiagramResult{
		DiagramID:      strFromMap(out, "diagramId"),
		VersionCreated: boolFromMap(out, "versionCreated"),
	}
	if v := optStrFromMap(out, "versionId"); v != nil {
		res.VersionID = v
	}
	return res, nil
}

func (r *mutationResolver) CreateDiagramVersion(ctx context.Context, orgID string, diagramID string, label *string) (*model.DiagramVersion, error) {
	body := map[string]interface{}{}
	if label != nil {
		body["label"] = *label
	}
	v, err := r.Client.CreateDiagramVersion(ctx, orgID, diagramID, body)
	if err != nil {
		return nil, err
	}
	return diagramVersionToModel(*v), nil
}

func (r *mutationResolver) RestoreDiagramVersion(ctx context.Context, orgID string, diagramID string, versionID string) (*model.Diagram, error) {
	d, err := r.Client.RestoreDiagramVersion(ctx, orgID, diagramID, versionID)
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

func (r *mutationResolver) CreateMap(ctx context.Context, orgID string, input model.CreateMapInput) (*model.UIMap, error) {
	m, err := r.Client.CreateMap(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return uimapToModel(m), nil
}

func (r *mutationResolver) UpdateMap(ctx context.Context, orgID string, id string, input model.UpdateMapInput) (*model.UIMap, error) {
	m, err := r.Client.UpdateMap(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return uimapToModel(m), nil
}

func (r *mutationResolver) DeleteMap(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteMap(ctx, orgID, id)
}

func (r *mutationResolver) CreateFrame(ctx context.Context, orgID string, mapID string, input model.CreateFrameInput) (*model.Frame, error) {
	f, err := r.Client.CreateFrame(ctx, orgID, mapID, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameToModel(f), nil
}

func (r *mutationResolver) UpdateFrame(ctx context.Context, orgID string, mapID string, id string, input model.UpdateFrameInput) (*model.Frame, error) {
	f, err := r.Client.UpdateFrame(ctx, orgID, mapID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameToModel(f), nil
}

func (r *mutationResolver) DeleteFrame(ctx context.Context, orgID string, mapID string, id string) (bool, error) {
	return true, r.Client.DeleteFrame(ctx, orgID, mapID, id)
}

func (r *mutationResolver) SyncFrame(ctx context.Context, orgID string, mapID string, input model.SyncFrameInput) (*model.SyncFrameResult, error) {
	out, err := r.Client.SyncFrame(ctx, orgID, mapID, toMap(input))
	if err != nil {
		return nil, err
	}
	return &model.SyncFrameResult{
		FrameID:        strFromMap(out, "frameId"),
		VersionCreated: boolFromMap(out, "versionCreated"),
	}, nil
}

func (r *mutationResolver) CreateFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFocalPointInput) (*model.FocalPoint, error) {
	fp, err := r.Client.CreateFocalPoint(ctx, orgID, mapID, frameID, toMap(input))
	if err != nil {
		return nil, err
	}
	return focalPointToModel(fp), nil
}

func (r *mutationResolver) UpdateFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFocalPointInput) (*model.FocalPoint, error) {
	fp, err := r.Client.UpdateFocalPoint(ctx, orgID, mapID, frameID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return focalPointToModel(fp), nil
}

func (r *mutationResolver) DeleteFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.Client.DeleteFocalPoint(ctx, orgID, mapID, frameID, id)
}

func (r *mutationResolver) UpsertCanvas(ctx context.Context, orgID string, mapID string, input model.UpsertCanvasInput) (*model.Canvas, error) {
	body := toMap(input)
	if fp, ok := body["framePositions"].(string); ok {
		var raw interface{}
		if err := unmarshalJSONString(fp, &raw); err == nil {
			body["framePositions"] = raw
		}
	}
	c, err := r.Client.UpsertCanvas(ctx, orgID, mapID, body)
	if err != nil {
		return nil, err
	}
	return canvasToModel(c), nil
}

func (r *mutationResolver) CreateFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFrameGroupInput) (*model.FrameGroup, error) {
	g, err := r.Client.CreateFrameGroup(ctx, orgID, mapID, frameID, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameGroupToModel(g), nil
}

func (r *mutationResolver) UpdateFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFrameGroupInput) (*model.FrameGroup, error) {
	g, err := r.Client.UpdateFrameGroup(ctx, orgID, mapID, frameID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameGroupToModel(g), nil
}

func (r *mutationResolver) DeleteFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.Client.DeleteFrameGroup(ctx, orgID, mapID, frameID, id)
}

func (r *mutationResolver) CreateFrameLink(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFrameLinkInput) (*model.FrameLink, error) {
	l, err := r.Client.CreateFrameLink(ctx, orgID, mapID, frameID, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameLinkToModel(l), nil
}

func (r *mutationResolver) UpdateFrameLink(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFrameLinkInput) (*model.FrameLink, error) {
	l, err := r.Client.UpdateFrameLink(ctx, orgID, mapID, frameID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return frameLinkToModel(l), nil
}

func (r *mutationResolver) DeleteFrameLink(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.Client.DeleteFrameLink(ctx, orgID, mapID, frameID, id)
}

func (r *mutationResolver) CreateFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, input model.CreateFocalPointMetaInput) (*model.FocalPointMeta, error) {
	m, err := r.Client.CreateFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, focalPointMetaBody(toMap(input)))
	if err != nil {
		return nil, err
	}
	return focalPointMetaToModel(m), nil
}

func (r *mutationResolver) UpdateFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, id string, input model.UpdateFocalPointMetaInput) (*model.FocalPointMeta, error) {
	m, err := r.Client.UpdateFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, id, focalPointMetaBody(toMap(input)))
	if err != nil {
		return nil, err
	}
	return focalPointMetaToModel(m), nil
}

func (r *mutationResolver) DeleteFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, id string) (bool, error) {
	return true, r.Client.DeleteFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, id)
}

func (r *queryResolver) Folders(ctx context.Context, orgID string, typeArg *string, parentID *string) ([]*model.Folder, error) {
	t := ""
	if typeArg != nil {
		t = *typeArg
	}
	p := ""
	if parentID != nil {
		p = *parentID
	}
	folders, err := r.Client.ListFolders(ctx, orgID, t, p)
	if err != nil {
		return nil, err
	}
	return foldersToModel(folders), nil
}

func (r *queryResolver) Folder(ctx context.Context, orgID string, id string) (*model.Folder, error) {
	f, err := r.Client.GetFolder(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return folderToModel(f), nil
}

func (r *queryResolver) Diagrams(ctx context.Context, orgID string, folderID *string) ([]*model.Diagram, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	diagrams, err := r.Client.ListDiagrams(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return diagramsToModel(diagrams), nil
}

func (r *queryResolver) Diagram(ctx context.Context, orgID string, id string) (*model.Diagram, error) {
	d, err := r.Client.GetDiagram(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

func (r *queryResolver) DiagramContent(ctx context.Context, orgID string, id string) (*model.DiagramContent, error) {
	content, err := r.Client.GetDiagramContent(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return &model.DiagramContent{DiagramID: id, Content: content}, nil
}

func (r *queryResolver) DiagramVersions(ctx context.Context, orgID string, diagramID string) ([]*model.DiagramVersion, error) {
	versions, err := r.Client.ListDiagramVersions(ctx, orgID, diagramID)
	if err != nil {
		return nil, err
	}
	return diagramVersionsToModel(versions), nil
}

func (r *queryResolver) DiagramVersionContent(ctx context.Context, orgID string, diagramID string, versionID string) (*model.DiagramContent, error) {
	content, err := r.Client.GetDiagramVersionContent(ctx, orgID, diagramID, versionID)
	if err != nil {
		return nil, err
	}
	return &model.DiagramContent{DiagramID: diagramID, Content: content}, nil
}

func (r *queryResolver) FlowDiagramComponents(ctx context.Context, orgID string) (*model.FlowDiagramComponents, error) {
	res, err := r.Client.ListFlowDiagramComponents(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return &model.FlowDiagramComponents{
		Components:       flowComponentsToModel(res.Components),
		CustomComponents: flowComponentsToModel(res.CustomComponents),
	}, nil
}

func (r *queryResolver) DiagramImages(ctx context.Context, orgID string, diagramID string) ([]*model.DiagramImage, error) {
	images, err := r.Client.ListDiagramImages(ctx, orgID, diagramID)
	if err != nil {
		return nil, err
	}
	return diagramImagesToModel(images), nil
}

func (r *queryResolver) Maps(ctx context.Context, orgID string, folderID *string) ([]*model.UIMap, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	maps, err := r.Client.ListMaps(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return uimapsToModel(maps), nil
}

func (r *queryResolver) Map(ctx context.Context, orgID string, id string) (*model.UIMap, error) {
	m, err := r.Client.GetMap(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return uimapToModel(m), nil
}

func (r *queryResolver) Frames(ctx context.Context, orgID string, mapID string) ([]*model.Frame, error) {
	frames, err := r.Client.ListFrames(ctx, orgID, mapID)
	if err != nil {
		return nil, err
	}
	return framesToModel(frames), nil
}

func (r *queryResolver) Frame(ctx context.Context, orgID string, mapID string, id string) (*model.Frame, error) {
	f, err := r.Client.GetFrame(ctx, orgID, mapID, id)
	if err != nil {
		return nil, err
	}
	return frameToModel(f), nil
}

func (r *queryResolver) FrameByID(ctx context.Context, orgID string, id string) (*model.Frame, error) {
	f, err := r.Client.GetFrameByID(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return frameToModel(f), nil
}

func (r *queryResolver) FocalPoints(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FocalPoint, error) {
	fps, err := r.Client.ListFocalPoints(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return focalPointsToModel(fps), nil
}

func (r *queryResolver) Canvas(ctx context.Context, orgID string, mapID string) (*model.Canvas, error) {
	c, err := r.Client.GetCanvas(ctx, orgID, mapID)
	if err != nil {
		return nil, err
	}
	return canvasToModel(c), nil
}

func (r *queryResolver) FrameGroups(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FrameGroup, error) {
	groups, err := r.Client.ListFrameGroups(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return frameGroupsToModel(groups), nil
}

func (r *queryResolver) FrameLinks(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FrameLink, error) {
	links, err := r.Client.ListFrameLinks(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return frameLinksToModel(links), nil
}

func (r *queryResolver) FocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string) ([]*model.FocalPointMeta, error) {
	metas, err := r.Client.ListFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID)
	if err != nil {
		return nil, err
	}
	return focalPointMetasToModel(metas), nil
}
