// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIEndpoint struct {
	ID                  string    `json:"id"`
	APIGroupID          string    `json:"apiGroupId"`
	ServiceID           string    `json:"serviceId"`
	OrgID               string    `json:"orgId"`
	OperationID         string    `json:"operationId"`
	Method              string    `json:"method"`
	Path                string    `json:"path"`
	Summary             string    `json:"summary"`
	Description         string    `json:"description"`
	Tags                []string  `json:"tags"`
	Parameters          string    `json:"parameters"`
	RequestBody         string    `json:"requestBody"`
	Responses           string    `json:"responses"`
	ExampleRequests     string    `json:"exampleRequests"`
	ExampleResponses    string    `json:"exampleResponses"`
	Order               float64   `json:"order"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type APIGroup struct {
	ID                  string    `json:"id"`
	ServiceID           string    `json:"serviceId"`
	OrgID               string    `json:"orgId"`
	Name                string    `json:"name"`
	Version             string    `json:"version"`
	Label               *string   `json:"label,omitempty"`
	Protocol            string    `json:"protocol"`
	SpecKey             *string   `json:"specKey,omitempty"`
	SpecHash            *string   `json:"specHash,omitempty"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type APIGroupVersion struct {
	ID                  string    `json:"id"`
	OrgID               string    `json:"orgId"`
	APIGroupID          string    `json:"apiGroupId"`
	VersionNumber       int       `json:"versionNumber"`
	Label               *string   `json:"label,omitempty"`
	SpecKey             string    `json:"specKey"`
	SpecHash            string    `json:"specHash"`
	IsAutoVersion       bool      `json:"isAutoVersion"`
	CreatedBy           string    `json:"createdBy"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	CreatedByActor      *Actor    `json:"createdByActor,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
}

type APITestCase struct {
	HTTPMethod         string       `json:"httpMethod"`
	APISpecID          *string      `json:"apiSpecId,omitempty"`
	OperationID        *string      `json:"operationId,omitempty"`
	Auth               *AuthConfig  `json:"auth,omitempty"`
	RequestHeaders     []*KeyValue  `json:"requestHeaders,omitempty"`
	QueryParams        []*KeyValue  `json:"queryParams,omitempty"`
	RequestBody        *string      `json:"requestBody,omitempty"`
	ExpectedStatusCode *int         `json:"expectedStatusCode,omitempty"`
	MaxResponseTimeMs  *int         `json:"maxResponseTimeMs,omitempty"`
	ResponseBody       *string      `json:"responseBody,omitempty"`
	Assertions         []*Assertion `json:"assertions,omitempty"`
}

type APITestCaseInput struct {
	HTTPMethod         string            `json:"httpMethod"`
	APISpecID          *string           `json:"apiSpecId,omitempty"`
	OperationID        *string           `json:"operationId,omitempty"`
	Auth               *AuthConfigInput  `json:"auth,omitempty"`
	RequestHeaders     []*KeyValueInput  `json:"requestHeaders,omitempty"`
	QueryParams        []*KeyValueInput  `json:"queryParams,omitempty"`
	RequestBody        *string           `json:"requestBody,omitempty"`
	ExpectedStatusCode *int              `json:"expectedStatusCode,omitempty"`
	MaxResponseTimeMs  *int              `json:"maxResponseTimeMs,omitempty"`
	ResponseBody       *string           `json:"responseBody,omitempty"`
	Assertions         []*AssertionInput `json:"assertions,omitempty"`
}

type Actor struct {
	ID        string  `json:"id"`
	Type      string  `json:"type"`
	Name      string  `json:"name"`
	Email     *string `json:"email,omitempty"`
	Disabled  bool    `json:"disabled"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type AddMemberInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type Assertion struct {
	Field string `json:"field"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type AssertionInput struct {
	Field string `json:"field"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type AssetURL struct {
	AssetID string `json:"assetId"`
	URL     string `json:"url"`
}

type AssetUpload struct {
	AssetID   string `json:"assetId"`
	UploadURL string `json:"uploadUrl"`
}

type AuthConfig struct {
	Type          string  `json:"type"`
	BearerToken   *string `json:"bearerToken,omitempty"`
	APIKeyHeader  *string `json:"apiKeyHeader,omitempty"`
	APIKeyValue   *string `json:"apiKeyValue,omitempty"`
	BasicUsername *string `json:"basicUsername,omitempty"`
	BasicPassword *string `json:"basicPassword,omitempty"`
}

type AuthConfigInput struct {
	Type          string  `json:"type"`
	BearerToken   *string `json:"bearerToken,omitempty"`
	APIKeyHeader  *string `json:"apiKeyHeader,omitempty"`
	APIKeyValue   *string `json:"apiKeyValue,omitempty"`
	BasicUsername *string `json:"basicUsername,omitempty"`
	BasicPassword *string `json:"basicPassword,omitempty"`
}

type Canvas struct {
	MapID          string    `json:"mapId"`
	OrgID          string    `json:"orgId"`
	Zoom           float64   `json:"zoom"`
	NavigationX    float64   `json:"navigationX"`
	NavigationY    float64   `json:"navigationY"`
	FramePositions string    `json:"framePositions"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ChatMessage struct {
	ID            string    `json:"id"`
	OrgID         string    `json:"orgId"`
	ChatSessionID string    `json:"chatSessionId"`
	Role          string    `json:"role"`
	Content       string    `json:"content"`
	Parts         any       `json:"parts,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
}

type ChatSession struct {
	ID           string    `json:"id"`
	OrgID        string    `json:"orgId"`
	OwnerUserID  string    `json:"ownerUserId"`
	Title        string    `json:"title"`
	IsPinned     bool      `json:"isPinned"`
	MessageCount int       `json:"messageCount"`
	CreatedBy    string    `json:"createdBy"`
	UpdatedBy    *string   `json:"updatedBy,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type ChatSessionWithMessages struct {
	Session  *ChatSession   `json:"session"`
	Messages []*ChatMessage `json:"messages"`
}

type ClientSavings struct {
	ClientName      string  `json:"clientName"`
	TotalCalls      int     `json:"totalCalls"`
	TokensSaved     int     `json:"tokensSaved"`
	CostSavedUsd    float64 `json:"costSavedUsd"`
	TotalDurationMs int     `json:"totalDurationMs"`
}

type Comment struct {
	ID              string    `json:"id"`
	OrgID           string    `json:"orgId"`
	ResourceID      string    `json:"resourceId"`
	ParentCommentID *string   `json:"parentCommentId,omitempty"`
	Text            string    `json:"text"`
	CreatedBy       string    `json:"createdBy"`
	UpdatedBy       *string   `json:"updatedBy,omitempty"`
	CreatedByActor  *Actor    `json:"createdByActor,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Component struct {
	ComponentID     string            `json:"componentId"`
	Type            string            `json:"type"`
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	Category        string            `json:"category"`
	Tags            []string          `json:"tags"`
	Slug            string            `json:"slug"`
	PreviewImageJpg string            `json:"previewImageJpg"`
	IsActive        bool              `json:"isActive"`
	Order           int               `json:"order"`
	ComponentFields []*ComponentField `json:"componentFields"`
	CreatedAt       time.Time         `json:"createdAt"`
	UpdatedAt       time.Time         `json:"updatedAt"`
}

type ComponentField struct {
	ComponentFieldID string   `json:"componentFieldId"`
	Label            string   `json:"label"`
	Type             string   `json:"type"`
	Required         bool     `json:"required"`
	Readonly         *bool    `json:"readonly,omitempty"`
	Options          []string `json:"options,omitempty"`
	Order            int      `json:"order"`
}

type ComponentLinkUsage struct {
	MetaID             string  `json:"metaId"`
	OrgID              string  `json:"orgId"`
	ComponentID        string  `json:"componentId"`
	MapID              string  `json:"mapId"`
	MapName            string  `json:"mapName"`
	FrameID            string  `json:"frameId"`
	FrameName          string  `json:"frameName"`
	ScreenshotAssetID  *string `json:"screenshotAssetId,omitempty"`
	ScreenshotImageURL *string `json:"screenshotImageUrl,omitempty"`
	FocalPointID       string  `json:"focalPointId"`
	FocalPointName     string  `json:"focalPointName"`
	LocationX          float64 `json:"locationX"`
	LocationY          float64 `json:"locationY"`
}

type ComponentModalField struct {
	ComponentFieldID *string   `json:"componentFieldId,omitempty"`
	Label            *string   `json:"label,omitempty"`
	Type             *string   `json:"type,omitempty"`
	Required         *bool     `json:"required,omitempty"`
	IsReadonly       *bool     `json:"isReadonly,omitempty"`
	Data             []any     `json:"data,omitempty"`
	Options          []*string `json:"options,omitempty"`
	Order            *int      `json:"order,omitempty"`
}

type ComponentModalFieldInput struct {
	ComponentFieldID *string   `json:"componentFieldId,omitempty"`
	Label            *string   `json:"label,omitempty"`
	Type             *string   `json:"type,omitempty"`
	Required         *bool     `json:"required,omitempty"`
	IsReadonly       *bool     `json:"isReadonly,omitempty"`
	Data             []any     `json:"data,omitempty"`
	Options          []*string `json:"options,omitempty"`
	Order            *int      `json:"order,omitempty"`
}

type Components struct {
	Components       []*Component `json:"components"`
	CustomComponents []*Component `json:"customComponents"`
}

type CreateAPIEndpointInput struct {
	OperationID      *string  `json:"operationId,omitempty"`
	Method           string   `json:"method"`
	Path             string   `json:"path"`
	Summary          *string  `json:"summary,omitempty"`
	Description      *string  `json:"description,omitempty"`
	Tags             []string `json:"tags,omitempty"`
	Parameters       *string  `json:"parameters,omitempty"`
	RequestBody      *string  `json:"requestBody,omitempty"`
	Responses        *string  `json:"responses,omitempty"`
	ExampleRequests  *string  `json:"exampleRequests,omitempty"`
	ExampleResponses *string  `json:"exampleResponses,omitempty"`
	Order            *float64 `json:"order,omitempty"`
}

type CreateAPIGroupInput struct {
	Name        string  `json:"name"`
	Version     *string `json:"version,omitempty"`
	Label       *string `json:"label,omitempty"`
	Protocol    *string `json:"protocol,omitempty"`
	Spec        *string `json:"spec,omitempty"`
	SpecAssetID *string `json:"specAssetId,omitempty"`
}

type CreateChatMessageInput struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type CreateChatSessionInput struct {
	Title *string `json:"title,omitempty"`
}

type CreateCommentInput struct {
	ResourceID      string  `json:"resourceId"`
	Text            string  `json:"text"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
}

type CreateDiagramImageInput struct {
	AssetID  string  `json:"assetId"`
	FileName *string `json:"fileName,omitempty"`
	Order    *int    `json:"order,omitempty"`
}

type CreateDiagramInput struct {
	Name     string  `json:"name"`
	Content  string  `json:"content"`
	FolderID *string `json:"folderId,omitempty"`
	TeamID   *string `json:"teamId,omitempty"`
	Source   *string `json:"source,omitempty"`
}

type CreateDocInput struct {
	FileName      string  `json:"fileName"`
	FileType      *string `json:"fileType,omitempty"`
	Description   *string `json:"description,omitempty"`
	ContentBase64 *string `json:"contentBase64,omitempty"`
	FileAssetID   *string `json:"fileAssetId,omitempty"`
	FolderID      *string `json:"folderId,omitempty"`
	TeamID        *string `json:"teamId,omitempty"`
}

type CreateFocalPointInput struct {
	Name       string  `json:"name"`
	LocationX  float64 `json:"locationX"`
	LocationY  float64 `json:"locationY"`
	Visibility *string `json:"visibility,omitempty"`
	IsActive   *bool   `json:"isActive,omitempty"`
}

type CreateFocalPointMetaInput struct {
	ComponentID                string                      `json:"componentId"`
	ComponentLinkDiagramID     *string                     `json:"componentLinkDiagramId,omitempty"`
	ComponentLinkAPIEndpointID *string                     `json:"componentLinkApiEndpointId,omitempty"`
	ComponentLinkTestPackID    *string                     `json:"componentLinkTestPackId,omitempty"`
	ComponentLinkServiceDocID  *string                     `json:"componentLinkServiceDocId,omitempty"`
	ComponentModalFields       []*ComponentModalFieldInput `json:"componentModalFields,omitempty"`
}

type CreateFolderInput struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	ParentID *string  `json:"parentId,omitempty"`
	TeamID   *string  `json:"teamId,omitempty"`
	Order    *float64 `json:"order,omitempty"`
}

type CreateFrameGroupInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	LocationX   *float64 `json:"locationX,omitempty"`
	LocationY   *float64 `json:"locationY,omitempty"`
	Width       *float64 `json:"width,omitempty"`
	Height      *float64 `json:"height,omitempty"`
	Order       *float64 `json:"order,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
}

type CreateFrameInput struct {
	Name              string   `json:"name"`
	Description       *string  `json:"description,omitempty"`
	TemplateType      string   `json:"templateType"`
	ParentFrameID     *string  `json:"parentFrameId,omitempty"`
	Order             *float64 `json:"order,omitempty"`
	Screenshot        *string  `json:"screenshot,omitempty"`
	ScreenshotAssetID *string  `json:"screenshotAssetId,omitempty"`
}

type CreateFrameLinkInput struct {
	Kind          string   `json:"kind"`
	TargetFrameID *string  `json:"targetFrameId,omitempty"`
	TargetMapID   *string  `json:"targetMapId,omitempty"`
	Label         *string  `json:"label,omitempty"`
	LocationX     *float64 `json:"locationX,omitempty"`
	LocationY     *float64 `json:"locationY,omitempty"`
	IsActive      *bool    `json:"isActive,omitempty"`
}

type CreateMapInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	FolderID    *string `json:"folderId,omitempty"`
	TeamID      *string `json:"teamId,omitempty"`
}

type CreateMlDeploymentInput struct {
	ModelID      string     `json:"modelId"`
	VersionID    string     `json:"versionId"`
	Name         string     `json:"name"`
	Environment  *string    `json:"environment,omitempty"`
	Status       *string    `json:"status,omitempty"`
	Endpoint     *string    `json:"endpoint,omitempty"`
	Region       *string    `json:"region,omitempty"`
	DeployedAt   *time.Time `json:"deployedAt,omitempty"`
	RolledBackAt *time.Time `json:"rolledBackAt,omitempty"`
}

type CreateMlFindingInput struct {
	ModelID     string   `json:"modelId"`
	VersionID   *string  `json:"versionId,omitempty"`
	Title       string   `json:"title"`
	Summary     *string  `json:"summary,omitempty"`
	Description *string  `json:"description,omitempty"`
	RunIds      []string `json:"runIds,omitempty"`
}

type CreateOrgInput struct {
	Name string `json:"name"`
}

type CreateRoleMappingInput struct {
	ClaimKey     string  `json:"claimKey"`
	ClaimValue   string  `json:"claimValue"`
	Role         string  `json:"role"`
	Scope        string  `json:"scope"`
	ResourceType *string `json:"resourceType,omitempty"`
	ResourceID   *string `json:"resourceId,omitempty"`
}

type CreateSavedQueryFolderInput struct {
	Name  string          `json:"name"`
	Scope SavedQueryScope `json:"scope"`
}

type CreateSavedQueryInput struct {
	Title       string          `json:"title"`
	Description *string         `json:"description,omitempty"`
	QueryText   string          `json:"queryText"`
	Tags        []string        `json:"tags,omitempty"`
	FolderID    *string         `json:"folderId,omitempty"`
	Scope       SavedQueryScope `json:"scope"`
}

type CreateServerOrgInput struct {
	Name     string `json:"name"`
	AutoJoin *bool  `json:"autoJoin,omitempty"`
}

type CreateServiceAccountInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Scopes      []string `json:"scopes"`
}

type CreateServiceDBInput struct {
	DbName     string     `json:"dbName"`
	DbType     *string    `json:"dbType,omitempty"`
	Dialect    *string    `json:"dialect,omitempty"`
	SchemaJSON *string    `json:"schemaJson,omitempty"`
	Source     *string    `json:"source,omitempty"`
	SourceTs   *time.Time `json:"sourceTs,omitempty"`
}

type CreateServiceDBVersionInput struct {
	Label         *string    `json:"label,omitempty"`
	IsAutoVersion *bool      `json:"isAutoVersion,omitempty"`
	DbName        *string    `json:"dbName,omitempty"`
	DbType        *string    `json:"dbType,omitempty"`
	Dialect       *string    `json:"dialect,omitempty"`
	SchemaJSON    *string    `json:"schemaJson,omitempty"`
	Source        *string    `json:"source,omitempty"`
	SourceTs      *time.Time `json:"sourceTs,omitempty"`
}

type CreateServiceDiagramInput struct {
	DiagramID *string `json:"diagramId,omitempty"`
	Name      *string `json:"name,omitempty"`
	Content   *string `json:"content,omitempty"`
	FolderID  *string `json:"folderId,omitempty"`
	TeamID    *string `json:"teamId,omitempty"`
	Source    *string `json:"source,omitempty"`
}

type CreateServiceDocInput struct {
	DocID         *string `json:"docId,omitempty"`
	FileName      *string `json:"fileName,omitempty"`
	FileType      *string `json:"fileType,omitempty"`
	Description   *string `json:"description,omitempty"`
	ContentBase64 *string `json:"contentBase64,omitempty"`
	FileAssetID   *string `json:"fileAssetId,omitempty"`
	FolderID      *string `json:"folderId,omitempty"`
	TeamID        *string `json:"teamId,omitempty"`
}

type CreateServiceInput struct {
	Name            string   `json:"name"`
	Description     *string  `json:"description,omitempty"`
	Status          *string  `json:"status,omitempty"`
	Tier            *string  `json:"tier,omitempty"`
	Category        *string  `json:"category,omitempty"`
	Language        *string  `json:"language,omitempty"`
	FolderID        *string  `json:"folderId,omitempty"`
	TeamID          *string  `json:"teamId,omitempty"`
	GitRepoURL      *string  `json:"gitRepoUrl,omitempty"`
	JiraProjectURL  *string  `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL *string  `json:"slackChannelUrl,omitempty"`
	Labels          []string `json:"labels,omitempty"`
	Metadata        *string  `json:"metadata,omitempty"`
}

type CreateTeamInput struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

type CreateTestCaseInput struct {
	TestPackID            string                 `json:"testPackId"`
	Title                 string                 `json:"title"`
	Order                 *float64               `json:"order,omitempty"`
	Type                  string                 `json:"type"`
	Description           *string                `json:"description,omitempty"`
	Priority              *string                `json:"priority,omitempty"`
	Labels                []string               `json:"labels,omitempty"`
	LinkedTicket          *string                `json:"linkedTicket,omitempty"`
	EstimatedDurationMins *int                   `json:"estimatedDurationMins,omitempty"`
	TestOwner             *string                `json:"testOwner,omitempty"`
	LinkedMapNodeID       *string                `json:"linkedMapNodeId,omitempty"`
	IsCritical            *bool                  `json:"isCritical,omitempty"`
	EvidenceRequired      *bool                  `json:"evidenceRequired,omitempty"`
	Manual                *ManualTestCaseInput   `json:"manual,omitempty"`
	API                   *APITestCaseInput      `json:"api,omitempty"`
	Graphql               *GraphQLTestCaseInput  `json:"graphql,omitempty"`
	Database              *DatabaseTestCaseInput `json:"database,omitempty"`
	Grpc                  *GRPCTestCaseInput     `json:"grpc,omitempty"`
	Status                *string                `json:"status,omitempty"`
	Version               *int                   `json:"version,omitempty"`
	BaselineRunResultID   *string                `json:"baselineRunResultId,omitempty"`
	Dependencies          []string               `json:"dependencies,omitempty"`
}

type CreateTestPackInput struct {
	Name string  `json:"name"`
	Type *string `json:"type,omitempty"`
}

type CreateTestRunInput struct {
	TestPackID    string     `json:"testPackId"`
	Environment   string     `json:"environment"`
	ReleaseLabel  *string    `json:"releaseLabel,omitempty"`
	StartedAt     *time.Time `json:"startedAt,omitempty"`
	CompletedAt   *time.Time `json:"completedAt,omitempty"`
	Status        *string    `json:"status,omitempty"`
	StartedBy     *string    `json:"startedBy,omitempty"`
	OverallStatus *string    `json:"overallStatus,omitempty"`
}

type CreateTestRunResultInput struct {
	TestRunID      string   `json:"testRunId"`
	TestCaseID     string   `json:"testCaseId"`
	Status         string   `json:"status"`
	BlockedReason  *string  `json:"blockedReason,omitempty"`
	ResponseStatus *int     `json:"responseStatus,omitempty"`
	ResponseBody   *string  `json:"responseBody,omitempty"`
	ResponseTimeMs *int     `json:"responseTimeMs,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
	ScreenshotUrls []string `json:"screenshotUrls,omitempty"`
}

type CreateTokenInput struct {
	Name      string  `json:"name"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

type CreateUserInput struct {
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
	Role     *string `json:"role,omitempty"`
}

type CreatedToken struct {
	ID               string    `json:"id"`
	ServiceAccountID string    `json:"serviceAccountId"`
	Name             string    `json:"name"`
	Prefix           string    `json:"prefix"`
	Token            string    `json:"token"`
	CreatedAt        time.Time `json:"createdAt"`
}

type CustomComponentFieldInput struct {
	ComponentFieldID *string  `json:"componentFieldId,omitempty"`
	Label            string   `json:"label"`
	Type             string   `json:"type"`
	Required         bool     `json:"required"`
	Readonly         *bool    `json:"readonly,omitempty"`
	Options          []string `json:"options,omitempty"`
	Order            int      `json:"order"`
}

type CustomComponentInput struct {
	Name            string                       `json:"name"`
	Category        *string                      `json:"category,omitempty"`
	Description     *string                      `json:"description,omitempty"`
	IsActive        *bool                        `json:"isActive,omitempty"`
	ComponentFields []*CustomComponentFieldInput `json:"componentFields,omitempty"`
}

type DailySavings struct {
	Date              time.Time `json:"date"`
	TotalCalls        int       `json:"totalCalls"`
	TotalTokensServed int       `json:"totalTokensServed"`
	TotalTokensSaved  int       `json:"totalTokensSaved"`
	CostServedUsd     float64   `json:"costServedUsd"`
	CostRawUsd        float64   `json:"costRawUsd"`
	CostSavedUsd      float64   `json:"costSavedUsd"`
	TotalDurationMs   int       `json:"totalDurationMs"`
	EstAgentTimeMs    int       `json:"estAgentTimeMs"`
	TimeSavedMs       int       `json:"timeSavedMs"`
}

type DatabaseTestCase struct {
	Dialect       string       `json:"dialect"`
	SchemaID      *string      `json:"schemaId,omitempty"`
	Query         string       `json:"query"`
	Assertions    []*Assertion `json:"assertions,omitempty"`
	SetupQuery    *string      `json:"setupQuery,omitempty"`
	TeardownQuery *string      `json:"teardownQuery,omitempty"`
}

type DatabaseTestCaseInput struct {
	Dialect       string            `json:"dialect"`
	SchemaID      *string           `json:"schemaId,omitempty"`
	Query         string            `json:"query"`
	Assertions    []*AssertionInput `json:"assertions,omitempty"`
	SetupQuery    *string           `json:"setupQuery,omitempty"`
	TeardownQuery *string           `json:"teardownQuery,omitempty"`
}

type DbColumn struct {
	Name          *string `json:"name,omitempty"`
	Type          *string `json:"type,omitempty"`
	Nullable      *bool   `json:"nullable,omitempty"`
	IsPrimaryKey  *bool   `json:"isPrimaryKey,omitempty"`
	Unique        *bool   `json:"unique,omitempty"`
	AutoIncrement *bool   `json:"autoIncrement,omitempty"`
	DefaultValue  *string `json:"defaultValue,omitempty"`
	ForeignKey    *string `json:"foreignKey,omitempty"`
	Description   *string `json:"description,omitempty"`
}

type DbIndex struct {
	Name   *string  `json:"name,omitempty"`
	Type   *string  `json:"type,omitempty"`
	Fields []string `json:"fields,omitempty"`
}

type DbTable struct {
	Name    *string     `json:"name,omitempty"`
	Columns []*DbColumn `json:"columns,omitempty"`
	Indexes []*DbIndex  `json:"indexes,omitempty"`
}

type Dependency struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	ConsumerService  *DependencyService `json:"consumerService"`
	ProviderService  *DependencyService `json:"providerService,omitempty"`
	ProviderName     *string            `json:"providerName,omitempty"`
	Type             *string            `json:"type,omitempty"`
	Criticality      *string            `json:"criticality,omitempty"`
	Description      *string            `json:"description,omitempty"`
	APIGroupName     *string            `json:"apiGroupName,omitempty"`
	APIEndpointNames []string           `json:"apiEndpointNames,omitempty"`
	DatabaseName     *string            `json:"databaseName,omitempty"`
	Direction        *string            `json:"direction,omitempty"`
}

type DependencyService struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	Tier        *string `json:"tier,omitempty"`
	Category    *string `json:"category,omitempty"`
	Language    *string `json:"language,omitempty"`
	GitRepoURL  *string `json:"gitRepoUrl,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
	Metadata    any     `json:"metadata,omitempty"`
}

type Diagram struct {
	ID                  string    `json:"id"`
	OrgID               string    `json:"orgId"`
	FolderID            *string   `json:"folderId,omitempty"`
	TeamID              *string   `json:"teamId,omitempty"`
	Name                string    `json:"name"`
	ContentKey          string    `json:"contentKey"`
	ContentHash         string    `json:"contentHash"`
	PreviewAssetID      *string   `json:"previewAssetId,omitempty"`
	PreviewImageURL     *string   `json:"previewImageUrl,omitempty"`
	PreviewContentHash  *string   `json:"previewContentHash,omitempty"`
	PreviewStatus       string    `json:"previewStatus"`
	Source              *string   `json:"source,omitempty"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedByActor      *Actor    `json:"createdByActor,omitempty"`
	UpdatedByActor      *Actor    `json:"updatedByActor,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type DiagramContent struct {
	DiagramID string `json:"diagramId"`
	Content   string `json:"content"`
}

type DiagramImage struct {
	DiagramImageID string    `json:"diagramImageId"`
	DiagramID      string    `json:"diagramId"`
	OrgID          string    `json:"orgId"`
	AssetID        string    `json:"assetId"`
	ImageURL       *string   `json:"imageUrl,omitempty"`
	FileName       *string   `json:"fileName,omitempty"`
	Order          int       `json:"order"`
	CreatedBy      string    `json:"createdBy"`
	CreatedAt      time.Time `json:"createdAt"`
}

type DiagramPage struct {
	Items      []*Diagram `json:"items"`
	TotalCount int        `json:"totalCount"`
}

type DiagramThumbnailUpload struct {
	UploadURL string `json:"uploadUrl"`
	AssetID   string `json:"assetId"`
}

type DiagramVersion struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"orgId"`
	DiagramID      string    `json:"diagramId"`
	VersionNumber  int       `json:"versionNumber"`
	Label          *string   `json:"label,omitempty"`
	ContentKey     string    `json:"contentKey"`
	ContentHash    string    `json:"contentHash"`
	IsAutoVersion  bool      `json:"isAutoVersion"`
	Source         *string   `json:"source,omitempty"`
	CreatedBy      string    `json:"createdBy"`
	CreatedByActor *Actor    `json:"createdByActor,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
}

type Doc struct {
	ID             string    `json:"id"`
	OrgID          string    `json:"orgId"`
	FolderID       *string   `json:"folderId,omitempty"`
	TeamID         *string   `json:"teamId,omitempty"`
	FileAssetID    string    `json:"fileAssetId"`
	FileURL        *string   `json:"fileUrl,omitempty"`
	FileName       string    `json:"fileName"`
	FileType       string    `json:"fileType"`
	Description    string    `json:"description"`
	ContentHash    string    `json:"contentHash"`
	CreatedBy      string    `json:"createdBy"`
	UpdatedBy      *string   `json:"updatedBy,omitempty"`
	CreatedByActor *Actor    `json:"createdByActor,omitempty"`
	UpdatedByActor *Actor    `json:"updatedByActor,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type DocPage struct {
	Items      []*Doc `json:"items"`
	TotalCount int    `json:"totalCount"`
}

type FileDownload struct {
	APIGroupID string `json:"apiGroupId"`
	FileName   string `json:"fileName"`
	Content    string `json:"content"`
}

type FlowDiagramComponent struct {
	ComponentID                string                       `json:"componentId"`
	Type                       string                       `json:"type"`
	Name                       string                       `json:"name"`
	Description                string                       `json:"description"`
	Category                   string                       `json:"category"`
	Tags                       []string                     `json:"tags"`
	Slug                       string                       `json:"slug"`
	PreviewImageJpg            string                       `json:"previewImageJpg"`
	IsActive                   bool                         `json:"isActive"`
	Order                      int                          `json:"order"`
	OrganizationID             *string                      `json:"organizationId,omitempty"`
	FlowDiagramComponentFields []*FlowDiagramComponentField `json:"flowDiagramComponentFields"`
}

type FlowDiagramComponentField struct {
	FlowDiagramComponentFieldID string   `json:"flowDiagramComponentFieldId"`
	Label                       string   `json:"label"`
	Type                        string   `json:"type"`
	Required                    bool     `json:"required"`
	Readonly                    *bool    `json:"readonly,omitempty"`
	Options                     []string `json:"options,omitempty"`
	Order                       int      `json:"order"`
}

type FlowDiagramComponents struct {
	Components       []*FlowDiagramComponent `json:"components"`
	CustomComponents []*FlowDiagramComponent `json:"customComponents"`
}

type FocalPoint struct {
	ID                  string    `json:"id"`
	FrameID             string    `json:"frameId"`
	OrgID               string    `json:"orgId"`
	Name                string    `json:"name"`
	LocationX           float64   `json:"locationX"`
	LocationY           float64   `json:"locationY"`
	Visibility          string    `json:"visibility"`
	IsActive            bool      `json:"isActive"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

type FocalPointMeta struct {
	ID                         string                 `json:"id"`
	FocalPointID               string                 `json:"focalPointId"`
	OrgID                      string                 `json:"orgId"`
	FrameID                    string                 `json:"frameId"`
	ComponentID                string                 `json:"componentId"`
	ComponentLinkDiagramID     *string                `json:"componentLinkDiagramId,omitempty"`
	ComponentLinkAPIEndpointID *string                `json:"componentLinkApiEndpointId,omitempty"`
	ComponentLinkTestPackID    *string                `json:"componentLinkTestPackId,omitempty"`
	ComponentLinkServiceDocID  *string                `json:"componentLinkServiceDocId,omitempty"`
	ComponentModalFields       []*ComponentModalField `json:"componentModalFields"`
	CreatedBy                  string                 `json:"createdBy"`
	UpdatedBy                  *string                `json:"updatedBy,omitempty"`
	CreatedByCommitHash        *string                `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash        *string                `json:"updatedByCommitHash,omitempty"`
	CreatedAt                  time.Time              `json:"createdAt"`
	UpdatedAt                  time.Time              `json:"updatedAt"`
}

type Folder struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	ParentID  *string   `json:"parentId,omitempty"`
	TeamID    *string   `json:"teamId,omitempty"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	Order     float64   `json:"order"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Frame struct {
	ID                    string    `json:"id"`
	MapID                 string    `json:"mapId"`
	OrgID                 string    `json:"orgId"`
	ParentFrameID         *string   `json:"parentFrameId,omitempty"`
	Name                  string    `json:"name"`
	Description           string    `json:"description"`
	TemplateType          string    `json:"templateType"`
	ScreenshotAssetID     *string   `json:"screenshotAssetId,omitempty"`
	ScreenshotImageURL    *string   `json:"screenshotImageUrl,omitempty"`
	ScreenshotContentHash *string   `json:"screenshotContentHash,omitempty"`
	Status                string    `json:"status"`
	Order                 float64   `json:"order"`
	Source                *string   `json:"source,omitempty"`
	FocalPointCount       int       `json:"focalPointCount"`
	CreatedBy             string    `json:"createdBy"`
	UpdatedBy             *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash   *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash   *string   `json:"updatedByCommitHash,omitempty"`
	CreatedByActor        *Actor    `json:"createdByActor,omitempty"`
	UpdatedByActor        *Actor    `json:"updatedByActor,omitempty"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type FrameGroup struct {
	ID          string    `json:"id"`
	FrameID     string    `json:"frameId"`
	OrgID       string    `json:"orgId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	LocationX   float64   `json:"locationX"`
	LocationY   float64   `json:"locationY"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Order       float64   `json:"order"`
	IsActive    bool      `json:"isActive"`
	CreatedBy   string    `json:"createdBy"`
	UpdatedBy   *string   `json:"updatedBy,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type FrameLink struct {
	ID            string    `json:"id"`
	FrameID       string    `json:"frameId"`
	OrgID         string    `json:"orgId"`
	Kind          string    `json:"kind"`
	TargetFrameID *string   `json:"targetFrameId,omitempty"`
	TargetMapID   *string   `json:"targetMapId,omitempty"`
	Label         string    `json:"label"`
	LocationX     float64   `json:"locationX"`
	LocationY     float64   `json:"locationY"`
	IsActive      bool      `json:"isActive"`
	CreatedBy     string    `json:"createdBy"`
	UpdatedBy     *string   `json:"updatedBy,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type FramePage struct {
	Items      []*Frame `json:"items"`
	TotalCount int      `json:"totalCount"`
}

type GRPCTestCase struct {
	ServiceName    string       `json:"serviceName"`
	MethodName     string       `json:"methodName"`
	CallMode       string       `json:"callMode"`
	ProtoFileID    *string      `json:"protoFileId,omitempty"`
	ServerAddress  *string      `json:"serverAddress,omitempty"`
	RequestMessage *string      `json:"requestMessage,omitempty"`
	Metadata       []*KeyValue  `json:"metadata,omitempty"`
	ExpectedStatus string       `json:"expectedStatus"`
	DeadlineMs     *int         `json:"deadlineMs,omitempty"`
	ResponseBody   *string      `json:"responseBody,omitempty"`
	Assertions     []*Assertion `json:"assertions,omitempty"`
	UseTLS         bool         `json:"useTLS"`
	ExpectError    bool         `json:"expectError"`
}

type GRPCTestCaseInput struct {
	ServiceName    string            `json:"serviceName"`
	MethodName     string            `json:"methodName"`
	CallMode       string            `json:"callMode"`
	ProtoFileID    *string           `json:"protoFileId,omitempty"`
	ServerAddress  *string           `json:"serverAddress,omitempty"`
	RequestMessage *string           `json:"requestMessage,omitempty"`
	Metadata       []*KeyValueInput  `json:"metadata,omitempty"`
	ExpectedStatus string            `json:"expectedStatus"`
	DeadlineMs     *int              `json:"deadlineMs,omitempty"`
	ResponseBody   *string           `json:"responseBody,omitempty"`
	Assertions     []*AssertionInput `json:"assertions,omitempty"`
	UseTLS         bool              `json:"useTLS"`
	ExpectError    bool              `json:"expectError"`
}

type GraphQLTestCase struct {
	OperationType string       `json:"operationType"`
	OperationName *string      `json:"operationName,omitempty"`
	Query         string       `json:"query"`
	Variables     *string      `json:"variables,omitempty"`
	ResponseBody  *string      `json:"responseBody,omitempty"`
	Assertions    []*Assertion `json:"assertions,omitempty"`
	ExpectError   bool         `json:"expectError"`
}

type GraphQLTestCaseInput struct {
	OperationType string            `json:"operationType"`
	OperationName *string           `json:"operationName,omitempty"`
	Query         string            `json:"query"`
	Variables     *string           `json:"variables,omitempty"`
	ResponseBody  *string           `json:"responseBody,omitempty"`
	Assertions    []*AssertionInput `json:"assertions,omitempty"`
	ExpectError   bool              `json:"expectError"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LDAPConfig struct {
	ID                string    `json:"id"`
	Host              string    `json:"host"`
	Port              int       `json:"port"`
	UseSsl            bool      `json:"useSsl"`
	StartTLS          bool      `json:"startTls"`
	SkipTLSVerify     bool      `json:"skipTlsVerify"`
	BindDn            string    `json:"bindDn"`
	BindPassword      string    `json:"bindPassword"`
	SearchBaseDn      string    `json:"searchBaseDn"`
	SearchFilter      string    `json:"searchFilter"`
	EmailAttribute    string    `json:"emailAttribute"`
	NameAttribute     string    `json:"nameAttribute"`
	UsernameAttribute string    `json:"usernameAttribute"`
	MemberOfAttribute string    `json:"memberOfAttribute"`
	AllowSignUp       bool      `json:"allowSignUp"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type ManualTestCase struct {
	Preconditions   *string         `json:"preconditions,omitempty"`
	TestData        *string         `json:"testData,omitempty"`
	Steps           []*TestCaseStep `json:"steps,omitempty"`
	ExpectedOutcome *string         `json:"expectedOutcome,omitempty"`
	Postconditions  *string         `json:"postconditions,omitempty"`
}

type ManualTestCaseInput struct {
	Preconditions   *string              `json:"preconditions,omitempty"`
	TestData        *string              `json:"testData,omitempty"`
	Steps           []*TestCaseStepInput `json:"steps,omitempty"`
	ExpectedOutcome *string              `json:"expectedOutcome,omitempty"`
	Postconditions  *string              `json:"postconditions,omitempty"`
}

type Me struct {
	UserID        string  `json:"userId"`
	OrgID         string  `json:"orgId"`
	Email         string  `json:"email"`
	Name          string  `json:"name"`
	Login         string  `json:"login"`
	Kind          string  `json:"kind"`
	IsServerAdmin bool    `json:"isServerAdmin"`
	AuthProvider  string  `json:"authProvider"`
	AvatarURL     *string `json:"avatarUrl,omitempty"`
}

type Member struct {
	UserID    string    `json:"userId"`
	OrgID     string    `json:"orgId"`
	Role      string    `json:"role"`
	Source    string    `json:"source"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	TeamID    *string   `json:"teamId,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type MlArtifact struct {
	ID     string `json:"id"`
	RunID  string `json:"runId"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	URI    string `json:"uri"`
	Size   string `json:"size"`
	Format string `json:"format"`
}

type MlDataset struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Source   string           `json:"source"`
	Type     string           `json:"type"`
	RowCount int              `json:"rowCount"`
	Schema   []*MlSchemaField `json:"schema"`
}

type MlDeployment struct {
	ID           string     `json:"id"`
	ModelID      string     `json:"modelId"`
	VersionID    string     `json:"versionId"`
	Name         string     `json:"name"`
	Environment  string     `json:"environment"`
	Status       string     `json:"status"`
	Endpoint     string     `json:"endpoint"`
	Region       string     `json:"region"`
	DeployedAt   *time.Time `json:"deployedAt,omitempty"`
	RolledBackAt *time.Time `json:"rolledBackAt,omitempty"`
}

type MlExperiment struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
}

type MlFinding struct {
	ID          string   `json:"id"`
	ModelID     string   `json:"modelId"`
	VersionID   *string  `json:"versionId,omitempty"`
	Title       string   `json:"title"`
	Summary     string   `json:"summary"`
	Description string   `json:"description"`
	RunIds      []string `json:"runIds"`
}

type MlModel struct {
	ID                  string     `json:"id"`
	Name                string     `json:"name"`
	Description         string     `json:"description"`
	Domain              string     `json:"domain"`
	ProblemType         string     `json:"problemType"`
	Tags                []string   `json:"tags"`
	ProductionVersionID *string    `json:"productionVersionId,omitempty"`
	CreatedAt           *time.Time `json:"createdAt,omitempty"`
	UpdatedAt           *time.Time `json:"updatedAt,omitempty"`
}

type MlModelVersion struct {
	ID          string     `json:"id"`
	ModelID     string     `json:"modelId"`
	Version     string     `json:"version"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Stage       string     `json:"stage"`
	RunID       *string    `json:"runId,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
}

type MlRun struct {
	ID           string     `json:"id"`
	OrgID        string     `json:"orgId"`
	ExperimentID string     `json:"experimentId"`
	Name         string     `json:"name"`
	Status       string     `json:"status"`
	StartedAt    *time.Time `json:"startedAt,omitempty"`
	EndedAt      *time.Time `json:"endedAt,omitempty"`
	Duration     string     `json:"duration"`
	Notes        string     `json:"notes"`
	Parameters   any        `json:"parameters"`
	Metrics      any        `json:"metrics"`
	DatasetID    *string    `json:"datasetId,omitempty"`
	Series       any        `json:"series"`
}

type MlSchemaField struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

type ModelSavings struct {
	ModelID      string  `json:"modelId"`
	DisplayName  string  `json:"displayName"`
	Provider     string  `json:"provider"`
	TotalCalls   int     `json:"totalCalls"`
	TokensSaved  int     `json:"tokensSaved"`
	CostRawUsd   float64 `json:"costRawUsd"`
	CostSavedUsd float64 `json:"costSavedUsd"`
}

type Mutation struct {
}

type OAuthProvider struct {
	ID             string    `json:"id"`
	ProviderName   string    `json:"providerName"`
	Type           string    `json:"type"`
	DisplayName    string    `json:"displayName"`
	IconURL        string    `json:"iconUrl"`
	ClientID       string    `json:"clientId"`
	ClientSecret   string    `json:"clientSecret"`
	AuthURL        string    `json:"authUrl"`
	TokenURL       string    `json:"tokenUrl"`
	UserinfoURL    string    `json:"userinfoUrl"`
	APIURL         string    `json:"apiUrl"`
	Scopes         string    `json:"scopes"`
	AllowedDomains string    `json:"allowedDomains"`
	AllowSignUp    bool      `json:"allowSignUp"`
	EmailClaim     string    `json:"emailClaim"`
	NameClaim      string    `json:"nameClaim"`
	SubClaim       string    `json:"subClaim"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	LogoURL   *string   `json:"logoUrl,omitempty"`
	Disabled  bool      `json:"disabled"`
	AutoJoin  bool      `json:"autoJoin"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type OrgSummary struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	LogoURL        *string `json:"logoUrl,omitempty"`
	Role           string  `json:"role"`
	Active         bool    `json:"active"`
	OnboardingDone bool    `json:"onboardingDone"`
}

type Query struct {
}

type RoleMapping struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organizationId"`
	ClaimKey       string `json:"claimKey"`
	ClaimValue     string `json:"claimValue"`
	Role           string `json:"role"`
	Scope          string `json:"scope"`
	ResourceType   string `json:"resourceType"`
	ResourceID     string `json:"resourceId"`
}

type SAMLConfig struct {
	ID              string    `json:"id"`
	IdpMetadataURL  string    `json:"idpMetadataUrl"`
	IdpMetadataXML  string    `json:"idpMetadataXml"`
	IdpEntityID     string    `json:"idpEntityId"`
	IdpSsoURL       string    `json:"idpSsoUrl"`
	IdpCert         string    `json:"idpCert"`
	SpEntityID      string    `json:"spEntityId"`
	SpCert          string    `json:"spCert"`
	SpKey           string    `json:"spKey"`
	SignRequests    bool      `json:"signRequests"`
	NameIDFormat    string    `json:"nameIdFormat"`
	EmailAttribute  string    `json:"emailAttribute"`
	NameAttribute   string    `json:"nameAttribute"`
	LoginAttribute  string    `json:"loginAttribute"`
	GroupsAttribute string    `json:"groupsAttribute"`
	AllowSignUp     bool      `json:"allowSignUp"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type SCIMConfig struct {
	ID string `json:"id"`
}

type SavedQuery struct {
	ID                  string          `json:"id"`
	OrgID               string          `json:"orgId"`
	ServiceDbID         string          `json:"serviceDbId"`
	FolderID            *string         `json:"folderId,omitempty"`
	Scope               SavedQueryScope `json:"scope"`
	OwnerUserID         *string         `json:"ownerUserId,omitempty"`
	TeamID              *string         `json:"teamId,omitempty"`
	Title               string          `json:"title"`
	Description         string          `json:"description"`
	QueryText           string          `json:"queryText"`
	Tags                []string        `json:"tags"`
	Source              *string         `json:"source,omitempty"`
	CreatedBy           string          `json:"createdBy"`
	UpdatedBy           *string         `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string         `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string         `json:"updatedByCommitHash,omitempty"`
	CreatedByActor      *Actor          `json:"createdByActor,omitempty"`
	UpdatedByActor      *Actor          `json:"updatedByActor,omitempty"`
	CreatedAt           time.Time       `json:"createdAt"`
	UpdatedAt           time.Time       `json:"updatedAt"`
}

type SavedQueryFolder struct {
	ID          string          `json:"id"`
	OrgID       string          `json:"orgId"`
	ServiceDbID string          `json:"serviceDbId"`
	Scope       SavedQueryScope `json:"scope"`
	OwnerUserID *string         `json:"ownerUserId,omitempty"`
	TeamID      *string         `json:"teamId,omitempty"`
	Name        string          `json:"name"`
	CreatedBy   string          `json:"createdBy"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type SavingsSummary struct {
	OrgID             string  `json:"orgId"`
	Period            string  `json:"period"`
	ModelID           *string `json:"modelId,omitempty"`
	TotalCalls        int     `json:"totalCalls"`
	TotalTokensServed int     `json:"totalTokensServed"`
	TotalTokensSaved  int     `json:"totalTokensSaved"`
	CostServedUsd     float64 `json:"costServedUsd"`
	CostRawUsd        float64 `json:"costRawUsd"`
	CostSavedUsd      float64 `json:"costSavedUsd"`
	UniqueUsersCount  int     `json:"uniqueUsersCount"`
	TotalDurationMs   int     `json:"totalDurationMs"`
	EstAgentTimeMs    int     `json:"estAgentTimeMs"`
	TimeSavedMs       int     `json:"timeSavedMs"`
}

type ServerConfig struct {
	StorageBackend   string `json:"storageBackend"`
	StorageBucket    string `json:"storageBucket"`
	StorageEndpoint  string `json:"storageEndpoint"`
	VectorBackend    string `json:"vectorBackend"`
	EmbeddingBackend string `json:"embeddingBackend"`
	EmbeddingModel   string `json:"embeddingModel"`
}

type ServerOverview struct {
	TotalUsers  int `json:"totalUsers"`
	ActiveUsers int `json:"activeUsers"`
	TotalOrgs   int `json:"totalOrgs"`
}

type Service struct {
	ID                  string        `json:"id"`
	OrgID               string        `json:"orgId"`
	FolderID            *string       `json:"folderId,omitempty"`
	TeamID              *string       `json:"teamId,omitempty"`
	Name                string        `json:"name"`
	Description         string        `json:"description"`
	Status              string        `json:"status"`
	Tier                string        `json:"tier"`
	Category            string        `json:"category"`
	Language            string        `json:"language"`
	GitRepoURL          *string       `json:"gitRepoUrl,omitempty"`
	JiraProjectURL      *string       `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL     *string       `json:"slackChannelUrl,omitempty"`
	LastCommitSha       *string       `json:"lastCommitSha,omitempty"`
	Labels              []string      `json:"labels"`
	Metadata            string        `json:"metadata"`
	CreatedBy           string        `json:"createdBy"`
	UpdatedBy           *string       `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string       `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string       `json:"updatedByCommitHash,omitempty"`
	CreatedByActor      *Actor        `json:"createdByActor,omitempty"`
	UpdatedByActor      *Actor        `json:"updatedByActor,omitempty"`
	Stats               *ServiceStats `json:"stats,omitempty"`
	CreatedAt           time.Time     `json:"createdAt"`
	UpdatedAt           time.Time     `json:"updatedAt"`
}

type ServiceAccount struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Scopes      []string  `json:"scopes"`
	Disabled    bool      `json:"disabled"`
	IsInternal  bool      `json:"isInternal"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ServiceAccountToken struct {
	ID               string     `json:"id"`
	ServiceAccountID string     `json:"serviceAccountId"`
	Name             string     `json:"name"`
	Prefix           string     `json:"prefix"`
	ExpiresAt        *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt       *time.Time `json:"lastUsedAt,omitempty"`
	Revoked          bool       `json:"revoked"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type ServiceDb struct {
	ID                  string     `json:"id"`
	ServiceID           string     `json:"serviceId"`
	OrgID               string     `json:"orgId"`
	DbName              string     `json:"dbName"`
	DbType              string     `json:"dbType"`
	Dialect             string     `json:"dialect"`
	SchemaJSON          string     `json:"schemaJson"`
	Tables              []*DbTable `json:"tables"`
	NoSQLSchema         any        `json:"noSQLSchema,omitempty"`
	DbDiagramID         *string    `json:"dbDiagramId,omitempty"`
	PgDumpFileID        *string    `json:"pgDumpFileId,omitempty"`
	Source              *string    `json:"source,omitempty"`
	SourceTs            *time.Time `json:"sourceTs,omitempty"`
	CreatedBy           string     `json:"createdBy"`
	UpdatedBy           *string    `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string    `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string    `json:"updatedByCommitHash,omitempty"`
	CreatedByActor      *Actor     `json:"createdByActor,omitempty"`
	UpdatedByActor      *Actor     `json:"updatedByActor,omitempty"`
	CreatedAt           time.Time  `json:"createdAt"`
	UpdatedAt           time.Time  `json:"updatedAt"`
}

type ServiceDBVersion struct {
	ID                  string     `json:"id"`
	OrgID               string     `json:"orgId"`
	ServiceDbID         string     `json:"serviceDbId"`
	VersionNumber       int        `json:"versionNumber"`
	Label               *string    `json:"label,omitempty"`
	SchemaJSON          string     `json:"schemaJson"`
	Tables              []*DbTable `json:"tables"`
	NoSQLSchema         any        `json:"noSQLSchema,omitempty"`
	DbDiagramID         *string    `json:"dbDiagramId,omitempty"`
	PgDumpFileID        *string    `json:"pgDumpFileId,omitempty"`
	Source              *string    `json:"source,omitempty"`
	SourceTs            *time.Time `json:"sourceTs,omitempty"`
	IsAutoVersion       bool       `json:"isAutoVersion"`
	CreatedBy           string     `json:"createdBy"`
	CreatedByCommitHash *string    `json:"createdByCommitHash,omitempty"`
	CreatedByActor      *Actor     `json:"createdByActor,omitempty"`
	CreatedAt           time.Time  `json:"createdAt"`
}

type ServiceDependencyInput struct {
	Name             string   `json:"name"`
	Service          string   `json:"service"`
	Type             *string  `json:"type,omitempty"`
	Criticality      string   `json:"criticality"`
	Description      *string  `json:"description,omitempty"`
	APIGroupName     *string  `json:"apiGroupName,omitempty"`
	APIEndpointNames []string `json:"apiEndpointNames,omitempty"`
	DatabaseName     *string  `json:"databaseName,omitempty"`
}

type ServiceDiagram struct {
	ServiceID           string    `json:"serviceId"`
	DiagramID           string    `json:"diagramId"`
	OrgID               string    `json:"orgId"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
	Diagram             *Diagram  `json:"diagram,omitempty"`
}

type ServiceDoc struct {
	ServiceID           string    `json:"serviceId"`
	DocID               string    `json:"docId"`
	OrgID               string    `json:"orgId"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
	Doc                 *Doc      `json:"doc,omitempty"`
}

type ServicePage struct {
	Items      []*Service `json:"items"`
	TotalCount int        `json:"totalCount"`
}

type ServiceStats struct {
	ServiceID     string `json:"serviceId"`
	EndpointCount int    `json:"endpointCount"`
	DiagramCount  int    `json:"diagramCount"`
	DocCount      int    `json:"docCount"`
	DbTableCount  int    `json:"dbTableCount"`
	TestCaseCount int    `json:"testCaseCount"`
}

type SyncAPIGroupInput struct {
	APIGroupID  *string `json:"apiGroupId,omitempty"`
	Name        string  `json:"name"`
	Version     *string `json:"version,omitempty"`
	Protocol    *string `json:"protocol,omitempty"`
	Spec        *string `json:"spec,omitempty"`
	SpecAssetID *string `json:"specAssetId,omitempty"`
}

type SyncAPIGroupResult struct {
	APIGroupID     string `json:"apiGroupId"`
	VersionCreated bool   `json:"versionCreated"`
}

type SyncDiagramInput struct {
	DiagramID *string `json:"diagramId,omitempty"`
	Name      string  `json:"name"`
	Content   string  `json:"content"`
	FolderID  *string `json:"folderId,omitempty"`
	TeamID    *string `json:"teamId,omitempty"`
	Source    *string `json:"source,omitempty"`
}

type SyncDiagramResult struct {
	DiagramID      string  `json:"diagramId"`
	VersionCreated bool    `json:"versionCreated"`
	VersionID      *string `json:"versionId,omitempty"`
}

type SyncFrameInput struct {
	FrameID      *string `json:"frameId,omitempty"`
	Name         string  `json:"name"`
	TemplateType string  `json:"templateType"`
	Description  *string `json:"description,omitempty"`
	Screenshot   string  `json:"screenshot"`
	Source       *string `json:"source,omitempty"`
}

type SyncFrameResult struct {
	FrameID        string `json:"frameId"`
	VersionCreated bool   `json:"versionCreated"`
}

type Team struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	Name        string    `json:"name"`
	Email       *string   `json:"email,omitempty"`
	ExternalID  *string   `json:"externalId,omitempty"`
	MemberCount int       `json:"memberCount"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type TeamMember struct {
	TeamID     string    `json:"teamId"`
	UserID     string    `json:"userId"`
	Permission string    `json:"permission"`
	CreatedAt  time.Time `json:"createdAt"`
}

type TestCase struct {
	TestCaseID            string            `json:"testCaseId"`
	TestPackID            string            `json:"testPackId"`
	ServiceID             string            `json:"serviceId"`
	OrgID                 string            `json:"orgId"`
	Title                 string            `json:"title"`
	Order                 float64           `json:"order"`
	Type                  string            `json:"type"`
	Description           *string           `json:"description,omitempty"`
	Priority              *string           `json:"priority,omitempty"`
	Labels                []string          `json:"labels"`
	LinkedTicket          *string           `json:"linkedTicket,omitempty"`
	EstimatedDurationMins *int              `json:"estimatedDurationMins,omitempty"`
	TestOwner             *string           `json:"testOwner,omitempty"`
	LinkedMapNodeID       *string           `json:"linkedMapNodeId,omitempty"`
	IsCritical            bool              `json:"isCritical"`
	EvidenceRequired      bool              `json:"evidenceRequired"`
	Manual                *ManualTestCase   `json:"manual,omitempty"`
	API                   *APITestCase      `json:"api,omitempty"`
	Graphql               *GraphQLTestCase  `json:"graphql,omitempty"`
	Database              *DatabaseTestCase `json:"database,omitempty"`
	Grpc                  *GRPCTestCase     `json:"grpc,omitempty"`
	Status                string            `json:"status"`
	Version               int               `json:"version"`
	BaselineRunResultID   *string           `json:"baselineRunResultId,omitempty"`
	Dependencies          []string          `json:"dependencies"`
	CreatedBy             string            `json:"createdBy"`
	UpdatedBy             *string           `json:"updatedBy,omitempty"`
	CreatedByCommitHash   *string           `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash   *string           `json:"updatedByCommitHash,omitempty"`
	DeletedBy             *string           `json:"deletedBy,omitempty"`
	CreatedAt             time.Time         `json:"createdAt"`
	UpdatedAt             time.Time         `json:"updatedAt"`
	DeletedAt             *time.Time        `json:"deletedAt,omitempty"`
}

type TestCaseStep struct {
	Order          int    `json:"order"`
	Action         string `json:"action"`
	ExpectedResult string `json:"expectedResult"`
}

type TestCaseStepInput struct {
	Order          int    `json:"order"`
	Action         string `json:"action"`
	ExpectedResult string `json:"expectedResult"`
}

type TestPack struct {
	TestPackID          string     `json:"testPackId"`
	ServiceID           string     `json:"serviceId"`
	OrgID               string     `json:"orgId"`
	Name                string     `json:"name"`
	Type                string     `json:"type"`
	CreatedBy           string     `json:"createdBy"`
	UpdatedBy           *string    `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string    `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string    `json:"updatedByCommitHash,omitempty"`
	DeletedBy           *string    `json:"deletedBy,omitempty"`
	CreatedAt           time.Time  `json:"createdAt"`
	UpdatedAt           time.Time  `json:"updatedAt"`
	DeletedAt           *time.Time `json:"deletedAt,omitempty"`
}

type TestRun struct {
	TestRunID     string     `json:"testRunId"`
	TestPackID    string     `json:"testPackId"`
	ServiceID     string     `json:"serviceId"`
	OrgID         string     `json:"orgId"`
	Environment   string     `json:"environment"`
	ReleaseLabel  *string    `json:"releaseLabel,omitempty"`
	StartedAt     *time.Time `json:"startedAt,omitempty"`
	CompletedAt   *time.Time `json:"completedAt,omitempty"`
	Status        string     `json:"status"`
	StartedBy     *string    `json:"startedBy,omitempty"`
	ExecutedBy    string     `json:"executedBy"`
	ExecutedAt    time.Time  `json:"executedAt"`
	OverallStatus string     `json:"overallStatus"`
}

type TestRunResult struct {
	TestRunResultID string    `json:"testRunResultId"`
	TestRunID       string    `json:"testRunId"`
	TestCaseID      string    `json:"testCaseId"`
	ServiceID       string    `json:"serviceId"`
	OrgID           string    `json:"orgId"`
	Status          string    `json:"status"`
	BlockedReason   *string   `json:"blockedReason,omitempty"`
	ResponseStatus  *int      `json:"responseStatus,omitempty"`
	ResponseBody    *string   `json:"responseBody,omitempty"`
	ResponseTimeMs  *int      `json:"responseTimeMs,omitempty"`
	Notes           *string   `json:"notes,omitempty"`
	ScreenshotUrls  []string  `json:"screenshotUrls"`
	ExecutedAt      time.Time `json:"executedAt"`
	ExecutedBy      string    `json:"executedBy"`
}

type TestRunSummary struct {
	TestRunID     string     `json:"testRunId"`
	TestPackID    string     `json:"testPackId"`
	ServiceID     string     `json:"serviceId"`
	Environment   string     `json:"environment"`
	ReleaseLabel  *string    `json:"releaseLabel,omitempty"`
	StartedAt     *time.Time `json:"startedAt,omitempty"`
	CompletedAt   *time.Time `json:"completedAt,omitempty"`
	Status        string     `json:"status"`
	StartedBy     *string    `json:"startedBy,omitempty"`
	ExecutedBy    string     `json:"executedBy"`
	ExecutedAt    time.Time  `json:"executedAt"`
	OverallStatus string     `json:"overallStatus"`
	PassedCount   int        `json:"passedCount"`
	FailedCount   int        `json:"failedCount"`
	SkippedCount  int        `json:"skippedCount"`
	BlockedCount  int        `json:"blockedCount"`
}

type ToolSavings struct {
	ToolName        string  `json:"toolName"`
	TotalCalls      int     `json:"totalCalls"`
	TokensSaved     int     `json:"tokensSaved"`
	CostSavedUsd    float64 `json:"costSavedUsd"`
	TotalDurationMs int     `json:"totalDurationMs"`
	EstAgentTimeMs  int     `json:"estAgentTimeMs"`
	TimeSavedMs     int     `json:"timeSavedMs"`
}

type UIMap struct {
	ID                  string    `json:"id"`
	OrgID               string    `json:"orgId"`
	FolderID            *string   `json:"folderId,omitempty"`
	TeamID              *string   `json:"teamId,omitempty"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	Status              string    `json:"status"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedBy           *string   `json:"updatedBy,omitempty"`
	CreatedByCommitHash *string   `json:"createdByCommitHash,omitempty"`
	UpdatedByCommitHash *string   `json:"updatedByCommitHash,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
	PreviewImgUrls      []string  `json:"previewImgUrls"`
}

type UIMapPage struct {
	Items      []*UIMap `json:"items"`
	TotalCount int      `json:"totalCount"`
}

type UpdateAPIEndpointInput struct {
	OperationID      *string  `json:"operationId,omitempty"`
	Method           *string  `json:"method,omitempty"`
	Path             *string  `json:"path,omitempty"`
	Summary          *string  `json:"summary,omitempty"`
	Description      *string  `json:"description,omitempty"`
	Tags             []string `json:"tags,omitempty"`
	Parameters       *string  `json:"parameters,omitempty"`
	RequestBody      *string  `json:"requestBody,omitempty"`
	Responses        *string  `json:"responses,omitempty"`
	ExampleRequests  *string  `json:"exampleRequests,omitempty"`
	ExampleResponses *string  `json:"exampleResponses,omitempty"`
	Order            *float64 `json:"order,omitempty"`
}

type UpdateAPIGroupInput struct {
	Name        *string `json:"name,omitempty"`
	Version     *string `json:"version,omitempty"`
	Label       *string `json:"label,omitempty"`
	Protocol    *string `json:"protocol,omitempty"`
	Spec        *string `json:"spec,omitempty"`
	SpecAssetID *string `json:"specAssetId,omitempty"`
}

type UpdateChatSessionInput struct {
	Title    *string `json:"title,omitempty"`
	IsPinned *bool   `json:"isPinned,omitempty"`
}

type UpdateCommentInput struct {
	Text *string `json:"text,omitempty"`
}

type UpdateDiagramInput struct {
	Name     *string `json:"name,omitempty"`
	Content  *string `json:"content,omitempty"`
	FolderID *string `json:"folderId,omitempty"`
	TeamID   *string `json:"teamId,omitempty"`
	Source   *string `json:"source,omitempty"`
}

type UpdateDocInput struct {
	FileName      *string `json:"fileName,omitempty"`
	FileType      *string `json:"fileType,omitempty"`
	Description   *string `json:"description,omitempty"`
	ContentBase64 *string `json:"contentBase64,omitempty"`
	FileAssetID   *string `json:"fileAssetId,omitempty"`
	FolderID      *string `json:"folderId,omitempty"`
	TeamID        *string `json:"teamId,omitempty"`
}

type UpdateFocalPointInput struct {
	Name       *string  `json:"name,omitempty"`
	LocationX  *float64 `json:"locationX,omitempty"`
	LocationY  *float64 `json:"locationY,omitempty"`
	Visibility *string  `json:"visibility,omitempty"`
	IsActive   *bool    `json:"isActive,omitempty"`
}

type UpdateFocalPointMetaInput struct {
	ComponentID                *string                     `json:"componentId,omitempty"`
	ComponentLinkDiagramID     *string                     `json:"componentLinkDiagramId,omitempty"`
	ComponentLinkAPIEndpointID *string                     `json:"componentLinkApiEndpointId,omitempty"`
	ComponentLinkTestPackID    *string                     `json:"componentLinkTestPackId,omitempty"`
	ComponentLinkServiceDocID  *string                     `json:"componentLinkServiceDocId,omitempty"`
	ComponentModalFields       []*ComponentModalFieldInput `json:"componentModalFields,omitempty"`
}

type UpdateFolderInput struct {
	Name     *string  `json:"name,omitempty"`
	ParentID *string  `json:"parentId,omitempty"`
	TeamID   *string  `json:"teamId,omitempty"`
	Order    *float64 `json:"order,omitempty"`
}

type UpdateFrameGroupInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	LocationX   *float64 `json:"locationX,omitempty"`
	LocationY   *float64 `json:"locationY,omitempty"`
	Width       *float64 `json:"width,omitempty"`
	Height      *float64 `json:"height,omitempty"`
	Order       *float64 `json:"order,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
}

type UpdateFrameInput struct {
	Name              *string  `json:"name,omitempty"`
	Description       *string  `json:"description,omitempty"`
	TemplateType      *string  `json:"templateType,omitempty"`
	Status            *string  `json:"status,omitempty"`
	Order             *float64 `json:"order,omitempty"`
	Screenshot        *string  `json:"screenshot,omitempty"`
	ScreenshotAssetID *string  `json:"screenshotAssetId,omitempty"`
}

type UpdateFrameLinkInput struct {
	Kind          *string  `json:"kind,omitempty"`
	TargetFrameID *string  `json:"targetFrameId,omitempty"`
	TargetMapID   *string  `json:"targetMapId,omitempty"`
	Label         *string  `json:"label,omitempty"`
	LocationX     *float64 `json:"locationX,omitempty"`
	LocationY     *float64 `json:"locationY,omitempty"`
	IsActive      *bool    `json:"isActive,omitempty"`
}

type UpdateMapInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	FolderID    *string `json:"folderId,omitempty"`
	TeamID      *string `json:"teamId,omitempty"`
}

type UpdateMemberInput struct {
	Name   string  `json:"name"`
	Email  string  `json:"email"`
	Role   string  `json:"role"`
	TeamID *string `json:"teamId,omitempty"`
}

type UpdateMlDeploymentInput struct {
	Name         *string    `json:"name,omitempty"`
	Environment  *string    `json:"environment,omitempty"`
	Status       *string    `json:"status,omitempty"`
	Endpoint     *string    `json:"endpoint,omitempty"`
	Region       *string    `json:"region,omitempty"`
	DeployedAt   *time.Time `json:"deployedAt,omitempty"`
	RolledBackAt *time.Time `json:"rolledBackAt,omitempty"`
}

type UpdateMlFindingInput struct {
	VersionID   *string  `json:"versionId,omitempty"`
	Title       *string  `json:"title,omitempty"`
	Summary     *string  `json:"summary,omitempty"`
	Description *string  `json:"description,omitempty"`
	RunIds      []string `json:"runIds,omitempty"`
}

type UpdateOrgInput struct {
	Name     *string `json:"name,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
}

type UpdateSavedQueryInput struct {
	Title       *string  `json:"title,omitempty"`
	Description *string  `json:"description,omitempty"`
	QueryText   *string  `json:"queryText,omitempty"`
	Tags        []string `json:"tags,omitempty"`
	FolderID    *string  `json:"folderId,omitempty"`
}

type UpdateServerOrgInput struct {
	Name     *string `json:"name,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
	AutoJoin *bool   `json:"autoJoin,omitempty"`
}

type UpdateServiceAccountInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Scopes      []string `json:"scopes,omitempty"`
	Disabled    *bool    `json:"disabled,omitempty"`
}

type UpdateServiceDBInput struct {
	DbName     *string    `json:"dbName,omitempty"`
	DbType     *string    `json:"dbType,omitempty"`
	Dialect    *string    `json:"dialect,omitempty"`
	SchemaJSON *string    `json:"schemaJson,omitempty"`
	Source     *string    `json:"source,omitempty"`
	SourceTs   *time.Time `json:"sourceTs,omitempty"`
}

type UpdateServiceDependenciesInput struct {
	Dependencies []*ServiceDependencyInput `json:"dependencies"`
	CommitHash   *string                   `json:"commitHash,omitempty"`
}

type UpdateServiceInput struct {
	Name            *string  `json:"name,omitempty"`
	Description     *string  `json:"description,omitempty"`
	Status          *string  `json:"status,omitempty"`
	Tier            *string  `json:"tier,omitempty"`
	Category        *string  `json:"category,omitempty"`
	Language        *string  `json:"language,omitempty"`
	FolderID        *string  `json:"folderId,omitempty"`
	TeamID          *string  `json:"teamId,omitempty"`
	GitRepoURL      *string  `json:"gitRepoUrl,omitempty"`
	JiraProjectURL  *string  `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL *string  `json:"slackChannelUrl,omitempty"`
	LastCommitSha   *string  `json:"lastCommitSha,omitempty"`
	Labels          []string `json:"labels,omitempty"`
	Metadata        *string  `json:"metadata,omitempty"`
}

type UpdateTeamInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UpdateTestCaseInput struct {
	TestPackID            *string                `json:"testPackId,omitempty"`
	Title                 *string                `json:"title,omitempty"`
	Order                 *float64               `json:"order,omitempty"`
	Type                  *string                `json:"type,omitempty"`
	Description           *string                `json:"description,omitempty"`
	Priority              *string                `json:"priority,omitempty"`
	Labels                []string               `json:"labels,omitempty"`
	LinkedTicket          *string                `json:"linkedTicket,omitempty"`
	EstimatedDurationMins *int                   `json:"estimatedDurationMins,omitempty"`
	TestOwner             *string                `json:"testOwner,omitempty"`
	LinkedMapNodeID       *string                `json:"linkedMapNodeId,omitempty"`
	IsCritical            *bool                  `json:"isCritical,omitempty"`
	EvidenceRequired      *bool                  `json:"evidenceRequired,omitempty"`
	Manual                *ManualTestCaseInput   `json:"manual,omitempty"`
	API                   *APITestCaseInput      `json:"api,omitempty"`
	Graphql               *GraphQLTestCaseInput  `json:"graphql,omitempty"`
	Database              *DatabaseTestCaseInput `json:"database,omitempty"`
	Grpc                  *GRPCTestCaseInput     `json:"grpc,omitempty"`
	Status                *string                `json:"status,omitempty"`
	Version               *int                   `json:"version,omitempty"`
	BaselineRunResultID   *string                `json:"baselineRunResultId,omitempty"`
	Dependencies          []string               `json:"dependencies,omitempty"`
}

type UpdateTestPackInput struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

type UpdateTestRunInput struct {
	OverallStatus *string    `json:"overallStatus,omitempty"`
	CompletedAt   *time.Time `json:"completedAt,omitempty"`
	Status        *string    `json:"status,omitempty"`
}

type UpdateTestRunResultInput struct {
	Status         *string  `json:"status,omitempty"`
	BlockedReason  *string  `json:"blockedReason,omitempty"`
	ResponseStatus *int     `json:"responseStatus,omitempty"`
	ResponseBody   *string  `json:"responseBody,omitempty"`
	ResponseTimeMs *int     `json:"responseTimeMs,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
	ScreenshotUrls []string `json:"screenshotUrls,omitempty"`
}

type UpdateUserInput struct {
	Name     *string `json:"name,omitempty"`
	Role     *string `json:"role,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
}

type UpsertCanvasInput struct {
	Zoom           *float64 `json:"zoom,omitempty"`
	NavigationX    *float64 `json:"navigationX,omitempty"`
	NavigationY    *float64 `json:"navigationY,omitempty"`
	FramePositions *string  `json:"framePositions,omitempty"`
}

type UpsertLDAPInput struct {
	Host              string  `json:"host"`
	Port              int     `json:"port"`
	UseSsl            bool    `json:"useSsl"`
	StartTLS          bool    `json:"startTls"`
	SkipTLSVerify     bool    `json:"skipTlsVerify"`
	BindDn            *string `json:"bindDn,omitempty"`
	BindPassword      *string `json:"bindPassword,omitempty"`
	SearchBaseDn      string  `json:"searchBaseDn"`
	SearchFilter      string  `json:"searchFilter"`
	EmailAttribute    string  `json:"emailAttribute"`
	NameAttribute     string  `json:"nameAttribute"`
	UsernameAttribute string  `json:"usernameAttribute"`
	MemberOfAttribute string  `json:"memberOfAttribute"`
	AllowSignUp       bool    `json:"allowSignUp"`
}

type UpsertOAuthInput struct {
	Type           string  `json:"type"`
	DisplayName    string  `json:"displayName"`
	IconURL        *string `json:"iconUrl,omitempty"`
	ClientID       string  `json:"clientId"`
	ClientSecret   *string `json:"clientSecret,omitempty"`
	AuthURL        *string `json:"authUrl,omitempty"`
	TokenURL       *string `json:"tokenUrl,omitempty"`
	UserinfoURL    *string `json:"userinfoUrl,omitempty"`
	APIURL         *string `json:"apiUrl,omitempty"`
	Scopes         string  `json:"scopes"`
	AllowedDomains *string `json:"allowedDomains,omitempty"`
	AllowSignUp    bool    `json:"allowSignUp"`
	EmailClaim     string  `json:"emailClaim"`
	NameClaim      string  `json:"nameClaim"`
	SubClaim       string  `json:"subClaim"`
}

type UpsertSAMLInput struct {
	IdpMetadataURL  *string `json:"idpMetadataUrl,omitempty"`
	IdpMetadataXML  *string `json:"idpMetadataXml,omitempty"`
	SpEntityID      string  `json:"spEntityId"`
	SignRequests    bool    `json:"signRequests"`
	NameIDFormat    string  `json:"nameIdFormat"`
	EmailAttribute  string  `json:"emailAttribute"`
	NameAttribute   string  `json:"nameAttribute"`
	LoginAttribute  string  `json:"loginAttribute"`
	GroupsAttribute *string `json:"groupsAttribute,omitempty"`
	AllowSignUp     bool    `json:"allowSignUp"`
}

type User struct {
	ID         string     `json:"id"`
	Email      string     `json:"email"`
	Name       string     `json:"name"`
	Login      string     `json:"login"`
	Disabled   bool       `json:"disabled"`
	Role       string     `json:"role"`
	AvatarURL  *string    `json:"avatarUrl,omitempty"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

type UserSavings struct {
	UserID           *string `json:"userId,omitempty"`
	ServiceAccountID *string `json:"serviceAccountId,omitempty"`
	DisplayName      string  `json:"displayName"`
	AvatarURL        *string `json:"avatarUrl,omitempty"`
	TotalCalls       int     `json:"totalCalls"`
	TokensSaved      int     `json:"tokensSaved"`
	CostSavedUsd     float64 `json:"costSavedUsd"`
	TotalDurationMs  int     `json:"totalDurationMs"`
}

type SavedQueryScope string

const (
	SavedQueryScopePersonal SavedQueryScope = "PERSONAL"
	SavedQueryScopeTeam     SavedQueryScope = "TEAM"
)

var AllSavedQueryScope = []SavedQueryScope{
	SavedQueryScopePersonal,
	SavedQueryScopeTeam,
}

func (e SavedQueryScope) IsValid() bool {
	switch e {
	case SavedQueryScopePersonal, SavedQueryScopeTeam:
		return true
	}
	return false
}

func (e SavedQueryScope) String() string {
	return string(e)
}

func (e *SavedQueryScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SavedQueryScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SavedQueryScope", str)
	}
	return nil
}

func (e SavedQueryScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SavedQueryScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SavedQueryScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
