// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type APIEndpoint struct {
	ID          string    `json:"id"`
	APIGroupID  string    `json:"apiGroupId"`
	ServiceID   string    `json:"serviceId"`
	OrgID       string    `json:"orgId"`
	OperationID string    `json:"operationId"`
	Method      string    `json:"method"`
	Path        string    `json:"path"`
	Summary     string    `json:"summary"`
	Description string    `json:"description"`
	Tags        []string  `json:"tags"`
	Parameters  string    `json:"parameters"`
	RequestBody string    `json:"requestBody"`
	Responses   string    `json:"responses"`
	Order       float64   `json:"order"`
	CreatedBy   string    `json:"createdBy"`
	UpdatedBy   *string   `json:"updatedBy,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type APIGroup struct {
	ID        string    `json:"id"`
	ServiceID string    `json:"serviceId"`
	OrgID     string    `json:"orgId"`
	Name      string    `json:"name"`
	Version   string    `json:"version"`
	Label     *string   `json:"label,omitempty"`
	Protocol  string    `json:"protocol"`
	SpecKey   *string   `json:"specKey,omitempty"`
	SpecHash  *string   `json:"specHash,omitempty"`
	CreatedBy string    `json:"createdBy"`
	UpdatedBy *string   `json:"updatedBy,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type APIGroupVersion struct {
	ID            string    `json:"id"`
	APIGroupID    string    `json:"apiGroupId"`
	VersionNumber int       `json:"versionNumber"`
	Label         *string   `json:"label,omitempty"`
	SpecKey       string    `json:"specKey"`
	SpecHash      string    `json:"specHash"`
	IsAutoVersion bool      `json:"isAutoVersion"`
	CreatedBy     string    `json:"createdBy"`
	CreatedAt     time.Time `json:"createdAt"`
}

type AddMemberInput struct {
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type Canvas struct {
	MapID          string    `json:"mapId"`
	OrgID          string    `json:"orgId"`
	Zoom           float64   `json:"zoom"`
	NavigationX    float64   `json:"navigationX"`
	NavigationY    float64   `json:"navigationY"`
	FramePositions string    `json:"framePositions"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type CreateAPIEndpointInput struct {
	OperationID *string  `json:"operationId,omitempty"`
	Method      string   `json:"method"`
	Path        string   `json:"path"`
	Summary     *string  `json:"summary,omitempty"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
	Parameters  *string  `json:"parameters,omitempty"`
	RequestBody *string  `json:"requestBody,omitempty"`
	Responses   *string  `json:"responses,omitempty"`
	Order       *float64 `json:"order,omitempty"`
}

type CreateAPIGroupInput struct {
	Name     string  `json:"name"`
	Version  *string `json:"version,omitempty"`
	Label    *string `json:"label,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Spec     *string `json:"spec,omitempty"`
}

type CreateDiagramImageInput struct {
	FileName *string `json:"fileName,omitempty"`
	Order    *int    `json:"order,omitempty"`
}

type CreateDiagramImageResult struct {
	DiagramImageID string `json:"diagramImageId"`
	FileID         string `json:"fileId"`
	FileUploadURL  string `json:"fileUploadURL"`
}

type CreateDiagramInput struct {
	Name     string  `json:"name"`
	Content  string  `json:"content"`
	FolderID *string `json:"folderId,omitempty"`
	TeamID   *string `json:"teamId,omitempty"`
	Source   *string `json:"source,omitempty"`
}

type CreateFocalPointInput struct {
	Name       string  `json:"name"`
	LocationX  float64 `json:"locationX"`
	LocationY  float64 `json:"locationY"`
	Visibility *string `json:"visibility,omitempty"`
	IsActive   *bool   `json:"isActive,omitempty"`
}

type CreateFolderInput struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	ParentID *string  `json:"parentId,omitempty"`
	Order    *float64 `json:"order,omitempty"`
}

type CreateFrameInput struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	TemplateType  string   `json:"templateType"`
	ParentFrameID *string  `json:"parentFrameId,omitempty"`
	Order         *float64 `json:"order,omitempty"`
	Screenshot    *string  `json:"screenshot,omitempty"`
}

type CreateInvitationInput struct {
	Email string `json:"email"`
	Role  string `json:"role"`
}

type CreateMapInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	FolderID    *string `json:"folderId,omitempty"`
	TeamID      *string `json:"teamId,omitempty"`
}

type CreateOrgInput struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

type CreateRoleMappingInput struct {
	ClaimKey     string  `json:"claimKey"`
	ClaimValue   string  `json:"claimValue"`
	Role         string  `json:"role"`
	Scope        string  `json:"scope"`
	ResourceType *string `json:"resourceType,omitempty"`
	ResourceID   *string `json:"resourceId,omitempty"`
}

type CreateServiceAccountInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Role        string  `json:"role"`
}

type CreateServiceInput struct {
	Name            string   `json:"name"`
	Slug            *string  `json:"slug,omitempty"`
	Description     *string  `json:"description,omitempty"`
	Status          *string  `json:"status,omitempty"`
	Tier            *string  `json:"tier,omitempty"`
	Category        *string  `json:"category,omitempty"`
	Language        *string  `json:"language,omitempty"`
	FolderID        *string  `json:"folderId,omitempty"`
	TeamID          *string  `json:"teamId,omitempty"`
	GitRepoURL      *string  `json:"gitRepoUrl,omitempty"`
	JiraProjectURL  *string  `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL *string  `json:"slackChannelUrl,omitempty"`
	Labels          []string `json:"labels,omitempty"`
	Metadata        *string  `json:"metadata,omitempty"`
}

type CreateTeamInput struct {
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

type CreateTokenInput struct {
	Name      string  `json:"name"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

type CreateUserInput struct {
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
	Role     *string `json:"role,omitempty"`
}

type CreatedToken struct {
	ID               string    `json:"id"`
	ServiceAccountID string    `json:"serviceAccountId"`
	Name             string    `json:"name"`
	Prefix           string    `json:"prefix"`
	Token            string    `json:"token"`
	CreatedAt        time.Time `json:"createdAt"`
}

type Diagram struct {
	ID                 string    `json:"id"`
	OrgID              string    `json:"orgId"`
	FolderID           *string   `json:"folderId,omitempty"`
	TeamID             *string   `json:"teamId,omitempty"`
	Name               string    `json:"name"`
	ContentKey         string    `json:"contentKey"`
	ContentHash        string    `json:"contentHash"`
	PreviewImageFileID *string   `json:"previewImageFileId,omitempty"`
	PreviewImageURL    *string   `json:"previewImageUrl,omitempty"`
	Source             *string   `json:"source,omitempty"`
	CreatedBy          string    `json:"createdBy"`
	UpdatedBy          *string   `json:"updatedBy,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type DiagramContent struct {
	DiagramID string `json:"diagramId"`
	Content   string `json:"content"`
}

type DiagramImage struct {
	DiagramImageID string    `json:"diagramImageId"`
	DiagramID      string    `json:"diagramId"`
	FileID         string    `json:"fileId"`
	FileURL        *string   `json:"fileURL,omitempty"`
	FileName       *string   `json:"fileName,omitempty"`
	Order          int       `json:"order"`
	CreatedBy      string    `json:"createdBy"`
	CreatedAt      time.Time `json:"createdAt"`
}

type DiagramThumbnail struct {
	FileID        string `json:"fileId"`
	FileUploadURL string `json:"fileUploadURL"`
}

type DiagramVersion struct {
	ID            string    `json:"id"`
	DiagramID     string    `json:"diagramId"`
	VersionNumber int       `json:"versionNumber"`
	Label         *string   `json:"label,omitempty"`
	ContentKey    string    `json:"contentKey"`
	ContentHash   string    `json:"contentHash"`
	IsAutoVersion bool      `json:"isAutoVersion"`
	Source        *string   `json:"source,omitempty"`
	CreatedBy     string    `json:"createdBy"`
	CreatedAt     time.Time `json:"createdAt"`
}

type FlowDiagramComponent struct {
	ComponentID                string                       `json:"componentId"`
	Type                       string                       `json:"type"`
	Name                       string                       `json:"name"`
	Description                string                       `json:"description"`
	Category                   string                       `json:"category"`
	Tags                       []string                     `json:"tags"`
	Slug                       string                       `json:"slug"`
	PreviewImageJpg            string                       `json:"previewImageJpg"`
	IsActive                   bool                         `json:"isActive"`
	Order                      int                          `json:"order"`
	OrganizationID             *string                      `json:"organizationId,omitempty"`
	FlowDiagramComponentFields []*FlowDiagramComponentField `json:"flowDiagramComponentFields"`
}

type FlowDiagramComponentField struct {
	FlowDiagramComponentFieldID string   `json:"flowDiagramComponentFieldId"`
	Label                       string   `json:"label"`
	Type                        string   `json:"type"`
	Required                    bool     `json:"required"`
	Readonly                    *bool    `json:"readonly,omitempty"`
	Options                     []string `json:"options,omitempty"`
	Order                       int      `json:"order"`
}

type FlowDiagramComponents struct {
	Components       []*FlowDiagramComponent `json:"components"`
	CustomComponents []*FlowDiagramComponent `json:"customComponents"`
}

type FocalPoint struct {
	ID         string    `json:"id"`
	FrameID    string    `json:"frameId"`
	OrgID      string    `json:"orgId"`
	Name       string    `json:"name"`
	LocationX  float64   `json:"locationX"`
	LocationY  float64   `json:"locationY"`
	Visibility string    `json:"visibility"`
	IsActive   bool      `json:"isActive"`
	CreatedBy  string    `json:"createdBy"`
	UpdatedBy  *string   `json:"updatedBy,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Folder struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"orgId"`
	ParentID  *string   `json:"parentId,omitempty"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	Order     float64   `json:"order"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Frame struct {
	ID                    string    `json:"id"`
	MapID                 string    `json:"mapId"`
	OrgID                 string    `json:"orgId"`
	ParentFrameID         *string   `json:"parentFrameId,omitempty"`
	Name                  string    `json:"name"`
	Description           string    `json:"description"`
	TemplateType          string    `json:"templateType"`
	ScreenshotKey         *string   `json:"screenshotKey,omitempty"`
	ScreenshotContentHash *string   `json:"screenshotContentHash,omitempty"`
	Status                string    `json:"status"`
	Order                 float64   `json:"order"`
	Source                *string   `json:"source,omitempty"`
	CreatedBy             string    `json:"createdBy"`
	UpdatedBy             *string   `json:"updatedBy,omitempty"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type Invitation struct {
	ID        string     `json:"id"`
	OrgID     string     `json:"orgId"`
	Email     string     `json:"email"`
	Role      string     `json:"role"`
	Code      string     `json:"code"`
	CreatedBy string     `json:"createdBy"`
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type LDAPConfig struct {
	ID                string    `json:"id"`
	Host              string    `json:"host"`
	Port              int       `json:"port"`
	UseSsl            bool      `json:"useSsl"`
	StartTLS          bool      `json:"startTls"`
	SkipTLSVerify     bool      `json:"skipTlsVerify"`
	BindDn            string    `json:"bindDn"`
	BindPassword      string    `json:"bindPassword"`
	SearchBaseDn      string    `json:"searchBaseDn"`
	SearchFilter      string    `json:"searchFilter"`
	EmailAttribute    string    `json:"emailAttribute"`
	NameAttribute     string    `json:"nameAttribute"`
	UsernameAttribute string    `json:"usernameAttribute"`
	MemberOfAttribute string    `json:"memberOfAttribute"`
	AllowSignUp       bool      `json:"allowSignUp"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type Me struct {
	UserID       string `json:"userId"`
	OrgID        string `json:"orgId"`
	Email        string `json:"email"`
	Name         string `json:"name"`
	Login        string `json:"login"`
	Kind         string `json:"kind"`
	Role         string `json:"role"`
	AuthProvider string `json:"authProvider"`
}

type Member struct {
	UserID    string    `json:"userId"`
	OrgID     string    `json:"orgId"`
	Role      string    `json:"role"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type OAuthProvider struct {
	ID             string    `json:"id"`
	ProviderName   string    `json:"providerName"`
	Type           string    `json:"type"`
	DisplayName    string    `json:"displayName"`
	ClientID       string    `json:"clientId"`
	ClientSecret   string    `json:"clientSecret"`
	AuthURL        string    `json:"authUrl"`
	TokenURL       string    `json:"tokenUrl"`
	UserinfoURL    string    `json:"userinfoUrl"`
	APIURL         string    `json:"apiUrl"`
	Scopes         string    `json:"scopes"`
	AllowedDomains string    `json:"allowedDomains"`
	AllowSignUp    bool      `json:"allowSignUp"`
	EmailClaim     string    `json:"emailClaim"`
	NameClaim      string    `json:"nameClaim"`
	SubClaim       string    `json:"subClaim"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Disabled  bool      `json:"disabled"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type OrgSummary struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Role   string `json:"role"`
	Active bool   `json:"active"`
}

type Query struct {
}

type RoleMapping struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organizationId"`
	ClaimKey       string `json:"claimKey"`
	ClaimValue     string `json:"claimValue"`
	Role           string `json:"role"`
	Scope          string `json:"scope"`
	ResourceType   string `json:"resourceType"`
	ResourceID     string `json:"resourceId"`
}

type SAMLConfig struct {
	ID              string    `json:"id"`
	IdpMetadataURL  string    `json:"idpMetadataUrl"`
	IdpMetadataXML  string    `json:"idpMetadataXml"`
	IdpEntityID     string    `json:"idpEntityId"`
	IdpSsoURL       string    `json:"idpSsoUrl"`
	IdpCert         string    `json:"idpCert"`
	SpEntityID      string    `json:"spEntityId"`
	SpCert          string    `json:"spCert"`
	SpKey           string    `json:"spKey"`
	SignRequests    bool      `json:"signRequests"`
	NameIDFormat    string    `json:"nameIdFormat"`
	EmailAttribute  string    `json:"emailAttribute"`
	NameAttribute   string    `json:"nameAttribute"`
	LoginAttribute  string    `json:"loginAttribute"`
	GroupsAttribute string    `json:"groupsAttribute"`
	AllowSignUp     bool      `json:"allowSignUp"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Service struct {
	ID              string    `json:"id"`
	OrgID           string    `json:"orgId"`
	FolderID        *string   `json:"folderId,omitempty"`
	TeamID          *string   `json:"teamId,omitempty"`
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	Description     string    `json:"description"`
	Status          string    `json:"status"`
	Tier            string    `json:"tier"`
	Category        string    `json:"category"`
	Language        string    `json:"language"`
	GitRepoURL      *string   `json:"gitRepoUrl,omitempty"`
	JiraProjectURL  *string   `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL *string   `json:"slackChannelUrl,omitempty"`
	LastCommitSha   *string   `json:"lastCommitSha,omitempty"`
	Labels          []string  `json:"labels"`
	Metadata        string    `json:"metadata"`
	CreatedBy       string    `json:"createdBy"`
	UpdatedBy       *string   `json:"updatedBy,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type ServiceAccount struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Role        string    `json:"role"`
	Disabled    bool      `json:"disabled"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ServiceAccountToken struct {
	ID               string     `json:"id"`
	ServiceAccountID string     `json:"serviceAccountId"`
	Name             string     `json:"name"`
	Prefix           string     `json:"prefix"`
	ExpiresAt        *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt       *time.Time `json:"lastUsedAt,omitempty"`
	Revoked          bool       `json:"revoked"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type SyncAPIGroupInput struct {
	APIGroupID *string `json:"apiGroupId,omitempty"`
	Name       string  `json:"name"`
	Version    *string `json:"version,omitempty"`
	Protocol   *string `json:"protocol,omitempty"`
	Spec       string  `json:"spec"`
}

type SyncAPIGroupResult struct {
	APIGroupID     string `json:"apiGroupId"`
	VersionCreated bool   `json:"versionCreated"`
}

type SyncDiagramInput struct {
	DiagramID *string `json:"diagramId,omitempty"`
	Name      string  `json:"name"`
	Content   string  `json:"content"`
	FolderID  *string `json:"folderId,omitempty"`
	TeamID    *string `json:"teamId,omitempty"`
	Source    *string `json:"source,omitempty"`
}

type SyncDiagramResult struct {
	DiagramID      string  `json:"diagramId"`
	VersionCreated bool    `json:"versionCreated"`
	VersionID      *string `json:"versionId,omitempty"`
}

type SyncFrameInput struct {
	FrameID      *string `json:"frameId,omitempty"`
	Name         string  `json:"name"`
	TemplateType string  `json:"templateType"`
	Description  *string `json:"description,omitempty"`
	Screenshot   string  `json:"screenshot"`
	Source       *string `json:"source,omitempty"`
}

type SyncFrameResult struct {
	FrameID        string `json:"frameId"`
	VersionCreated bool   `json:"versionCreated"`
}

type Team struct {
	ID         string    `json:"id"`
	OrgID      string    `json:"orgId"`
	Name       string    `json:"name"`
	Email      *string   `json:"email,omitempty"`
	ExternalID *string   `json:"externalId,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type TeamMember struct {
	TeamID     string    `json:"teamId"`
	UserID     string    `json:"userId"`
	Permission string    `json:"permission"`
	CreatedAt  time.Time `json:"createdAt"`
}

type UIMap struct {
	ID          string    `json:"id"`
	OrgID       string    `json:"orgId"`
	FolderID    *string   `json:"folderId,omitempty"`
	TeamID      *string   `json:"teamId,omitempty"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedBy   string    `json:"createdBy"`
	UpdatedBy   *string   `json:"updatedBy,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type UpdateAPIEndpointInput struct {
	OperationID *string  `json:"operationId,omitempty"`
	Method      *string  `json:"method,omitempty"`
	Path        *string  `json:"path,omitempty"`
	Summary     *string  `json:"summary,omitempty"`
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`
	Parameters  *string  `json:"parameters,omitempty"`
	RequestBody *string  `json:"requestBody,omitempty"`
	Responses   *string  `json:"responses,omitempty"`
	Order       *float64 `json:"order,omitempty"`
}

type UpdateAPIGroupInput struct {
	Name     *string `json:"name,omitempty"`
	Version  *string `json:"version,omitempty"`
	Label    *string `json:"label,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	Spec     *string `json:"spec,omitempty"`
}

type UpdateDiagramInput struct {
	Name     *string `json:"name,omitempty"`
	Content  *string `json:"content,omitempty"`
	FolderID *string `json:"folderId,omitempty"`
	TeamID   *string `json:"teamId,omitempty"`
	Source   *string `json:"source,omitempty"`
}

type UpdateDiagramThumbnailInput struct {
	FileName    *string `json:"fileName,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
}

type UpdateFocalPointInput struct {
	Name       *string  `json:"name,omitempty"`
	LocationX  *float64 `json:"locationX,omitempty"`
	LocationY  *float64 `json:"locationY,omitempty"`
	Visibility *string  `json:"visibility,omitempty"`
	IsActive   *bool    `json:"isActive,omitempty"`
}

type UpdateFolderInput struct {
	Name     *string  `json:"name,omitempty"`
	ParentID *string  `json:"parentId,omitempty"`
	Order    *float64 `json:"order,omitempty"`
}

type UpdateFrameInput struct {
	Name         *string  `json:"name,omitempty"`
	Description  *string  `json:"description,omitempty"`
	TemplateType *string  `json:"templateType,omitempty"`
	Status       *string  `json:"status,omitempty"`
	Order        *float64 `json:"order,omitempty"`
	Screenshot   *string  `json:"screenshot,omitempty"`
}

type UpdateMapInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	FolderID    *string `json:"folderId,omitempty"`
	TeamID      *string `json:"teamId,omitempty"`
}

type UpdateOrgInput struct {
	Name     *string `json:"name,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
}

type UpdateServiceAccountInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Disabled    *bool   `json:"disabled,omitempty"`
}

type UpdateServiceInput struct {
	Name            *string  `json:"name,omitempty"`
	Slug            *string  `json:"slug,omitempty"`
	Description     *string  `json:"description,omitempty"`
	Status          *string  `json:"status,omitempty"`
	Tier            *string  `json:"tier,omitempty"`
	Category        *string  `json:"category,omitempty"`
	Language        *string  `json:"language,omitempty"`
	FolderID        *string  `json:"folderId,omitempty"`
	TeamID          *string  `json:"teamId,omitempty"`
	GitRepoURL      *string  `json:"gitRepoUrl,omitempty"`
	JiraProjectURL  *string  `json:"jiraProjectUrl,omitempty"`
	SlackChannelURL *string  `json:"slackChannelUrl,omitempty"`
	LastCommitSha   *string  `json:"lastCommitSha,omitempty"`
	Labels          []string `json:"labels,omitempty"`
	Metadata        *string  `json:"metadata,omitempty"`
}

type UpdateTeamInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UpdateUserInput struct {
	Name     *string `json:"name,omitempty"`
	Role     *string `json:"role,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
}

type UpsertCanvasInput struct {
	Zoom           *float64 `json:"zoom,omitempty"`
	NavigationX    *float64 `json:"navigationX,omitempty"`
	NavigationY    *float64 `json:"navigationY,omitempty"`
	FramePositions *string  `json:"framePositions,omitempty"`
}

type UpsertLDAPInput struct {
	Host              string  `json:"host"`
	Port              int     `json:"port"`
	UseSsl            bool    `json:"useSsl"`
	StartTLS          bool    `json:"startTls"`
	SkipTLSVerify     bool    `json:"skipTlsVerify"`
	BindDn            *string `json:"bindDn,omitempty"`
	BindPassword      *string `json:"bindPassword,omitempty"`
	SearchBaseDn      string  `json:"searchBaseDn"`
	SearchFilter      string  `json:"searchFilter"`
	EmailAttribute    string  `json:"emailAttribute"`
	NameAttribute     string  `json:"nameAttribute"`
	UsernameAttribute string  `json:"usernameAttribute"`
	MemberOfAttribute string  `json:"memberOfAttribute"`
	AllowSignUp       bool    `json:"allowSignUp"`
}

type UpsertOAuthInput struct {
	Type           string  `json:"type"`
	DisplayName    string  `json:"displayName"`
	ClientID       string  `json:"clientId"`
	ClientSecret   *string `json:"clientSecret,omitempty"`
	AuthURL        *string `json:"authUrl,omitempty"`
	TokenURL       *string `json:"tokenUrl,omitempty"`
	UserinfoURL    *string `json:"userinfoUrl,omitempty"`
	APIURL         *string `json:"apiUrl,omitempty"`
	Scopes         string  `json:"scopes"`
	AllowedDomains *string `json:"allowedDomains,omitempty"`
	AllowSignUp    bool    `json:"allowSignUp"`
	EmailClaim     string  `json:"emailClaim"`
	NameClaim      string  `json:"nameClaim"`
	SubClaim       string  `json:"subClaim"`
}

type UpsertSAMLInput struct {
	IdpMetadataURL  *string `json:"idpMetadataUrl,omitempty"`
	IdpMetadataXML  *string `json:"idpMetadataXml,omitempty"`
	SpEntityID      string  `json:"spEntityId"`
	SignRequests    bool    `json:"signRequests"`
	NameIDFormat    string  `json:"nameIdFormat"`
	EmailAttribute  string  `json:"emailAttribute"`
	NameAttribute   string  `json:"nameAttribute"`
	LoginAttribute  string  `json:"loginAttribute"`
	GroupsAttribute *string `json:"groupsAttribute,omitempty"`
	AllowSignUp     bool    `json:"allowSignUp"`
}

type User struct {
	ID         string     `json:"id"`
	Email      string     `json:"email"`
	Name       string     `json:"name"`
	Login      string     `json:"login"`
	Disabled   bool       `json:"disabled"`
	Role       string     `json:"role"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}
