package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/model"
)

// Actor is the resolver for the actor field.
func (r *queryResolver) Actor(ctx context.Context, orgID string, id string) (*model.Actor, error) {
	return r.resolveActor(ctx, orgID, id)
}
