package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// CreateServerOrg is the resolver for the createServerOrg field.
func (r *mutationResolver) CreateServerOrg(ctx context.Context, input model.CreateServerOrgInput) (*model.Org, error) {
	o, err := r.Admin.ServerCreateOrg(ctx, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.OrgToModel(o), nil
}

// UpdateServerOrg is the resolver for the updateServerOrg field.
func (r *mutationResolver) UpdateServerOrg(ctx context.Context, id string, input model.UpdateServerOrgInput) (*model.Org, error) {
	o, err := r.Admin.ServerUpdateOrg(ctx, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.OrgToModel(o), nil
}

// DeleteServerOrg is the resolver for the deleteServerOrg field.
func (r *mutationResolver) DeleteServerOrg(ctx context.Context, id string) (bool, error) {
	return true, r.Admin.ServerDeleteOrg(ctx, id)
}

// PrepareServerOrgLogoUpload is the resolver for the prepareServerOrgLogoUpload field.
func (r *mutationResolver) PrepareServerOrgLogoUpload(ctx context.Context, orgID string) (*model.AssetUpload, error) {
	u, err := r.Admin.PrepareServerOrgLogoUpload(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return &model.AssetUpload{AssetID: u.AssetID, UploadURL: u.UploadURL}, nil
}

// SetServerOrgLogo is the resolver for the setServerOrgLogo field.
func (r *mutationResolver) SetServerOrgLogo(ctx context.Context, orgID string) (bool, error) {
	return true, r.Admin.SetServerOrgLogo(ctx, orgID)
}

// RemoveServerOrgLogo is the resolver for the removeServerOrgLogo field.
func (r *mutationResolver) RemoveServerOrgLogo(ctx context.Context, orgID string) (bool, error) {
	return true, r.Admin.RemoveServerOrgLogo(ctx, orgID)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	u, err := r.Admin.CreateUser(ctx, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.UserToModel(u), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	u, err := r.Admin.UpdateUser(ctx, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.UserToModel(u), nil
}

// DisableUser is the resolver for the disableUser field.
func (r *mutationResolver) DisableUser(ctx context.Context, id string) (bool, error) {
	return true, r.Admin.DisableUser(ctx, id)
}

// UpsertOAuthProvider is the resolver for the upsertOAuthProvider field.
func (r *mutationResolver) UpsertOAuthProvider(ctx context.Context, provider string, input model.UpsertOAuthInput) (bool, error) {
	return true, r.Admin.UpsertOAuthProvider(ctx, provider, convert.ToMap(input))
}

// DeleteOAuthProvider is the resolver for the deleteOAuthProvider field.
func (r *mutationResolver) DeleteOAuthProvider(ctx context.Context, provider string) (bool, error) {
	return true, r.Admin.DeleteOAuthProvider(ctx, provider)
}

// PrepareOAuthProviderIconUpload is the resolver for the prepareOAuthProviderIconUpload field.
func (r *mutationResolver) PrepareOAuthProviderIconUpload(ctx context.Context, provider string) (*model.AssetUpload, error) {
	u, err := r.Admin.PrepareOAuthProviderIconUpload(ctx, provider)
	if err != nil {
		return nil, err
	}
	return &model.AssetUpload{AssetID: u.AssetID, UploadURL: u.UploadURL}, nil
}

// SetOAuthProviderIcon is the resolver for the setOAuthProviderIcon field.
func (r *mutationResolver) SetOAuthProviderIcon(ctx context.Context, provider string) (bool, error) {
	return true, r.Admin.SetOAuthProviderIcon(ctx, provider)
}

// RemoveOAuthProviderIcon is the resolver for the removeOAuthProviderIcon field.
func (r *mutationResolver) RemoveOAuthProviderIcon(ctx context.Context, provider string) (bool, error) {
	return true, r.Admin.RemoveOAuthProviderIcon(ctx, provider)
}

// CreateRoleMapping is the resolver for the createRoleMapping field.
func (r *mutationResolver) CreateRoleMapping(ctx context.Context, input model.CreateRoleMappingInput) (bool, error) {
	return true, r.Admin.CreateRoleMapping(ctx, convert.ToMap(input))
}

// DeleteRoleMapping is the resolver for the deleteRoleMapping field.
func (r *mutationResolver) DeleteRoleMapping(ctx context.Context, id string) (bool, error) {
	return true, r.Admin.DeleteRoleMapping(ctx, id)
}

// UpsertLdap is the resolver for the upsertLDAP field.
func (r *mutationResolver) UpsertLdap(ctx context.Context, input model.UpsertLDAPInput) (bool, error) {
	return true, r.Admin.UpsertLDAP(ctx, convert.ToMap(input))
}

// DeleteLdap is the resolver for the deleteLDAP field.
func (r *mutationResolver) DeleteLdap(ctx context.Context) (bool, error) {
	return true, r.Admin.DeleteLDAP(ctx)
}

// UpsertSaml is the resolver for the upsertSAML field.
func (r *mutationResolver) UpsertSaml(ctx context.Context, input model.UpsertSAMLInput) (bool, error) {
	return true, r.Admin.UpsertSAML(ctx, convert.ToMap(input))
}

// ServerOverview is the resolver for the serverOverview field.
func (r *queryResolver) ServerOverview(ctx context.Context) (*model.ServerOverview, error) {
	o, err := r.Admin.GetServerOverview(ctx)
	if err != nil {
		return nil, err
	}
	return convert.OverviewToModel(o), nil
}

// ServerConfig is the resolver for the serverConfig field.
func (r *queryResolver) ServerConfig(ctx context.Context) (*model.ServerConfig, error) {
	c, err := r.Admin.GetServerConfig(ctx)
	if err != nil {
		return nil, err
	}
	return convert.ServerConfigToModel(c), nil
}

// ServerOrgs is the resolver for the serverOrgs field.
func (r *queryResolver) ServerOrgs(ctx context.Context) ([]*model.Org, error) {
	orgs, err := r.Admin.ServerListOrgs(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Org, len(orgs))
	for i := range orgs {
		out[i] = convert.OrgToModel(&orgs[i])
	}
	return out, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.Admin.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return convert.UsersToModel(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.Admin.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return convert.UserToModel(u), nil
}

// OauthProviders is the resolver for the oauthProviders field.
func (r *queryResolver) OauthProviders(ctx context.Context) ([]*model.OAuthProvider, error) {
	providers, err := r.Admin.ListOAuthProviders(ctx)
	if err != nil {
		return nil, err
	}
	return convert.OAuthProvidersToModel(providers), nil
}

// RoleMappings is the resolver for the roleMappings field.
func (r *queryResolver) RoleMappings(ctx context.Context) ([]*model.RoleMapping, error) {
	mappings, err := r.Admin.ListRoleMappings(ctx)
	if err != nil {
		return nil, err
	}
	return convert.RoleMappingsToModel(mappings), nil
}

// Ldap is the resolver for the ldap field.
func (r *queryResolver) Ldap(ctx context.Context) (*model.LDAPConfig, error) {
	l, err := r.Admin.GetLDAP(ctx)
	if err != nil {
		if uigraphapi.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return convert.LDAPToModel(l), nil
}

// Saml is the resolver for the saml field.
func (r *queryResolver) Saml(ctx context.Context) (*model.SAMLConfig, error) {
	s, err := r.Admin.GetSAML(ctx)
	if err != nil {
		if uigraphapi.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return convert.SAMLToModel(s), nil
}

// Scim is the resolver for the scim field.
func (r *queryResolver) Scim(ctx context.Context) (*model.SCIMConfig, error) {
	s, err := r.Admin.GetSCIM(ctx)
	if err != nil {
		if uigraphapi.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return convert.SCIMToModel(s), nil
}
