package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	u, err := r.Client.CreateUser(ctx, toMap(input))
	if err != nil {
		return nil, err
	}
	return userToModel(u), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	u, err := r.Client.UpdateUser(ctx, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return userToModel(u), nil
}

// DisableUser is the resolver for the disableUser field.
func (r *mutationResolver) DisableUser(ctx context.Context, id string) (bool, error) {
	return true, r.Client.DisableUser(ctx, id)
}

// UpsertOAuthProvider is the resolver for the upsertOAuthProvider field.
func (r *mutationResolver) UpsertOAuthProvider(ctx context.Context, provider string, input model.UpsertOAuthInput) (bool, error) {
	return true, r.Client.UpsertOAuthProvider(ctx, provider, toMap(input))
}

// DeleteOAuthProvider is the resolver for the deleteOAuthProvider field.
func (r *mutationResolver) DeleteOAuthProvider(ctx context.Context, provider string) (bool, error) {
	return true, r.Client.DeleteOAuthProvider(ctx, provider)
}

// CreateRoleMapping is the resolver for the createRoleMapping field.
func (r *mutationResolver) CreateRoleMapping(ctx context.Context, input model.CreateRoleMappingInput) (bool, error) {
	return true, r.Client.CreateRoleMapping(ctx, toMap(input))
}

// DeleteRoleMapping is the resolver for the deleteRoleMapping field.
func (r *mutationResolver) DeleteRoleMapping(ctx context.Context, id string) (bool, error) {
	return true, r.Client.DeleteRoleMapping(ctx, id)
}

// UpsertLdap is the resolver for the upsertLDAP field.
func (r *mutationResolver) UpsertLdap(ctx context.Context, input model.UpsertLDAPInput) (bool, error) {
	return true, r.Client.UpsertLDAP(ctx, toMap(input))
}

// DeleteLdap is the resolver for the deleteLDAP field.
func (r *mutationResolver) DeleteLdap(ctx context.Context) (bool, error) {
	return true, r.Client.DeleteLDAP(ctx)
}

// UpsertSaml is the resolver for the upsertSAML field.
func (r *mutationResolver) UpsertSaml(ctx context.Context, input model.UpsertSAMLInput) (bool, error) {
	return true, r.Client.UpsertSAML(ctx, toMap(input))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.Client.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	return usersToModel(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.Client.GetUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return userToModel(u), nil
}

// OauthProviders is the resolver for the oauthProviders field.
func (r *queryResolver) OauthProviders(ctx context.Context) ([]*model.OAuthProvider, error) {
	providers, err := r.Client.ListOAuthProviders(ctx)
	if err != nil {
		return nil, err
	}
	return oauthProvidersToModel(providers), nil
}

// RoleMappings is the resolver for the roleMappings field.
func (r *queryResolver) RoleMappings(ctx context.Context) ([]*model.RoleMapping, error) {
	mappings, err := r.Client.ListRoleMappings(ctx)
	if err != nil {
		return nil, err
	}
	return roleMappingsToModel(mappings), nil
}

// Ldap is the resolver for the ldap field.
// Single-config GET returns 404 when not yet configured; treat as null.
func (r *queryResolver) Ldap(ctx context.Context) (*model.LDAPConfig, error) {
	l, err := r.Client.GetLDAP(ctx)
	if err != nil {
		if uigraphapi.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return ldapToModel(l), nil
}

// Saml is the resolver for the saml field.
// Single-config GET returns 404 when not yet configured; treat as null.
func (r *queryResolver) Saml(ctx context.Context) (*model.SAMLConfig, error) {
	s, err := r.Client.GetSAML(ctx)
	if err != nil {
		if uigraphapi.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return samlToModel(s), nil
}
