package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// AgentSessions is the resolver for the agentSessions field.
func (r *queryResolver) AgentSessions(ctx context.Context, orgID string, typeArg *string, status *string, period *string, limit *int, offset *int) (*model.AgentSessionPage, error) {
	page, err := r.AgentAPI.GetAgentSessions(ctx, orgID, typeArg, status, period, limit, offset)
	if err != nil {
		return nil, err
	}

	actors, err := r.resolveSessionActors(ctx, orgID, page.Sessions)
	if err != nil {
		return nil, err
	}

	return &model.AgentSessionPage{
		Sessions: convert.AgentSessionListToModel(page.Sessions, actors),
		Total:    page.Total,
		Period:   page.Period,
		Limit:    page.Limit,
		Offset:   page.Offset,
	}, nil
}

// AgentSession is the resolver for the agentSession field.
func (r *queryResolver) AgentSession(ctx context.Context, orgID string, id string) (*model.AgentSessionDetail, error) {
	detail, err := r.AgentAPI.GetAgentSession(ctx, orgID, id)
	if err != nil {
		return nil, err
	}

	actors, err := r.resolveSessionActors(ctx, orgID, []uigraphapi.AgentSession{detail.Session})
	if err != nil {
		return nil, err
	}

	return &model.AgentSessionDetail{
		Session: convert.AgentSessionToModel(detail.Session, actors),
		Steps:   convert.AgentSessionStepListToModel(detail.Steps),
	}, nil
}

// AgentSessionSummary is the resolver for the agentSessionSummary field.
func (r *queryResolver) AgentSessionSummary(ctx context.Context, orgID string, period *string, typeArg *string) (*model.AgentSessionSummary, error) {
	s, err := r.AgentAPI.GetAgentSessionSummary(ctx, orgID, period, typeArg)
	if err != nil {
		return nil, err
	}
	return convert.AgentSessionSummaryToModel(*s), nil
}
