package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateAuthProvider is the resolver for the createAuthProvider field.
func (r *mutationResolver) CreateAuthProvider(ctx context.Context, orgID string, input model.AuthProviderInput) (*model.AuthProvider, error) {
	p, err := r.AuthAPI.CreateAuthProvider(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.AuthProviderToModel(p), nil
}

// UpdateAuthProvider is the resolver for the updateAuthProvider field.
func (r *mutationResolver) UpdateAuthProvider(ctx context.Context, orgID string, slug string, input model.AuthProviderInput) (*model.AuthProvider, error) {
	p, err := r.AuthAPI.UpdateAuthProvider(ctx, orgID, slug, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.AuthProviderToModel(p), nil
}

// DeleteAuthProvider is the resolver for the deleteAuthProvider field.
func (r *mutationResolver) DeleteAuthProvider(ctx context.Context, orgID string, slug string) (bool, error) {
	return true, r.AuthAPI.DeleteAuthProvider(ctx, orgID, slug)
}

// PrepareAuthProviderIconUpload is the resolver for the prepareAuthProviderIconUpload field.
func (r *mutationResolver) PrepareAuthProviderIconUpload(ctx context.Context, orgID string, slug string) (*model.AssetUpload, error) {
	u, err := r.AuthAPI.PrepareAuthProviderIconUpload(ctx, orgID, slug)
	if err != nil {
		return nil, err
	}
	return &model.AssetUpload{AssetID: u.AssetID, UploadURL: u.UploadURL}, nil
}

// SetAuthProviderIcon is the resolver for the setAuthProviderIcon field.
func (r *mutationResolver) SetAuthProviderIcon(ctx context.Context, orgID string, slug string) (bool, error) {
	return true, r.AuthAPI.SetAuthProviderIcon(ctx, orgID, slug)
}

// RemoveAuthProviderIcon is the resolver for the removeAuthProviderIcon field.
func (r *mutationResolver) RemoveAuthProviderIcon(ctx context.Context, orgID string, slug string) (bool, error) {
	return true, r.AuthAPI.RemoveAuthProviderIcon(ctx, orgID, slug)
}

// CreateAuthRoleMapping is the resolver for the createAuthRoleMapping field.
func (r *mutationResolver) CreateAuthRoleMapping(ctx context.Context, orgID string, providerSlug string, input model.AuthRoleMappingInput) (*model.AuthRoleMapping, error) {
	m, err := r.AuthAPI.CreateAuthRoleMapping(ctx, orgID, providerSlug, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.AuthRoleMappingToModel(m), nil
}

// UpdateAuthRoleMapping is the resolver for the updateAuthRoleMapping field.
func (r *mutationResolver) UpdateAuthRoleMapping(ctx context.Context, orgID string, providerSlug string, mappingID string, input model.AuthRoleMappingInput) (*model.AuthRoleMapping, error) {
	m, err := r.AuthAPI.UpdateAuthRoleMapping(ctx, orgID, providerSlug, mappingID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.AuthRoleMappingToModel(m), nil
}

// DeleteAuthRoleMapping is the resolver for the deleteAuthRoleMapping field.
func (r *mutationResolver) DeleteAuthRoleMapping(ctx context.Context, orgID string, providerSlug string, mappingID string) (bool, error) {
	return true, r.AuthAPI.DeleteAuthRoleMapping(ctx, orgID, providerSlug, mappingID)
}

// CreateOrgDomain is the resolver for the createOrgDomain field.
func (r *mutationResolver) CreateOrgDomain(ctx context.Context, orgID string, domain string) (*model.OrgDomain, error) {
	d, err := r.AuthAPI.CreateOrgDomain(ctx, orgID, domain)
	if err != nil {
		return nil, err
	}
	return convert.OrgDomainToModel(d), nil
}

// UpdateOrgDomain is the resolver for the updateOrgDomain field.
func (r *mutationResolver) UpdateOrgDomain(ctx context.Context, orgID string, domainID string, domain string) (*model.OrgDomain, error) {
	d, err := r.AuthAPI.UpdateOrgDomain(ctx, orgID, domainID, domain)
	if err != nil {
		return nil, err
	}
	return convert.OrgDomainToModel(d), nil
}

// DeleteOrgDomain is the resolver for the deleteOrgDomain field.
func (r *mutationResolver) DeleteOrgDomain(ctx context.Context, orgID string, domainID string) (bool, error) {
	return true, r.AuthAPI.DeleteOrgDomain(ctx, orgID, domainID)
}

// AuthProviders is the resolver for the authProviders field.
func (r *queryResolver) AuthProviders(ctx context.Context, orgID string) ([]*model.AuthProvider, error) {
	providers, err := r.AuthAPI.ListAuthProviders(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.AuthProvidersToModel(providers), nil
}

// AuthProvider is the resolver for the authProvider field.
func (r *queryResolver) AuthProvider(ctx context.Context, orgID string, slug string) (*model.AuthProvider, error) {
	p, err := r.AuthAPI.GetAuthProvider(ctx, orgID, slug)
	if err != nil {
		return nil, err
	}
	return convert.AuthProviderToModel(p), nil
}

// AuthProviderSamlMetadata is the resolver for the authProviderSamlMetadata field.
func (r *queryResolver) AuthProviderSamlMetadata(ctx context.Context, orgID string, slug string) (*model.SamlSpMetadata, error) {
	m, err := r.AuthAPI.GetAuthProviderSAMLMetadata(ctx, orgID, slug)
	if err != nil {
		return nil, err
	}
	return convert.SamlSpMetadataToModel(m), nil
}

// AuthRoleMappings is the resolver for the authRoleMappings field.
func (r *queryResolver) AuthRoleMappings(ctx context.Context, orgID string, providerSlug string) ([]*model.AuthRoleMapping, error) {
	mappings, err := r.AuthAPI.ListAuthRoleMappings(ctx, orgID, providerSlug)
	if err != nil {
		return nil, err
	}
	return convert.AuthRoleMappingsToModel(mappings), nil
}

// OrgDomains is the resolver for the orgDomains field.
func (r *queryResolver) OrgDomains(ctx context.Context, orgID string) ([]*model.OrgDomain, error) {
	domains, err := r.AuthAPI.ListOrgDomains(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.OrgDomainsToModel(domains), nil
}

// MappingOperators is the resolver for the mappingOperators field.
func (r *queryResolver) MappingOperators(ctx context.Context) ([]*model.MappingOperator, error) {
	ops, err := r.AuthAPI.ListMappingOperators(ctx)
	if err != nil {
		return nil, err
	}
	return convert.MappingOperatorsToModel(ops), nil
}
