package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreatedByActor is the resolver for the createdByActor field.
func (r *aPIGroupVersionResolver) CreatedByActor(ctx context.Context, obj *model.APIGroupVersion) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// CreateService is the resolver for the createService field.
func (r *mutationResolver) CreateService(ctx context.Context, orgID string, input model.CreateServiceInput) (*model.Service, error) {
	s, err := r.Catalog.CreateService(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceToModel(s), nil
}

// UpdateService is the resolver for the updateService field.
func (r *mutationResolver) UpdateService(ctx context.Context, orgID string, id string, input model.UpdateServiceInput) (*model.Service, error) {
	s, err := r.Catalog.UpdateService(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceToModel(s), nil
}

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Catalog.DeleteService(ctx, orgID, id)
}

// CreateAPIGroup is the resolver for the createAPIGroup field.
func (r *mutationResolver) CreateAPIGroup(ctx context.Context, orgID string, serviceID string, input model.CreateAPIGroupInput) (*model.APIGroup, error) {
	g, err := r.Catalog.CreateAPIGroup(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.APIGroupToModel(g), nil
}

// UpdateAPIGroup is the resolver for the updateAPIGroup field.
func (r *mutationResolver) UpdateAPIGroup(ctx context.Context, orgID string, serviceID string, id string, input model.UpdateAPIGroupInput) (*model.APIGroup, error) {
	g, err := r.Catalog.UpdateAPIGroup(ctx, orgID, serviceID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.APIGroupToModel(g), nil
}

// DeleteAPIGroup is the resolver for the deleteAPIGroup field.
func (r *mutationResolver) DeleteAPIGroup(ctx context.Context, orgID string, serviceID string, id string) (bool, error) {
	return true, r.Catalog.DeleteAPIGroup(ctx, orgID, serviceID, id)
}

// SyncAPIGroup is the resolver for the syncAPIGroup field.
func (r *mutationResolver) SyncAPIGroup(ctx context.Context, orgID string, serviceID string, input model.SyncAPIGroupInput) (*model.SyncAPIGroupResult, error) {
	out, err := r.Catalog.SyncAPIGroup(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return &model.SyncAPIGroupResult{
		APIGroupID:     convert.StrFromMap(out, "apiGroupId"),
		VersionCreated: convert.BoolFromMap(out, "versionCreated"),
	}, nil
}

// CreateServiceDoc is the resolver for the createServiceDoc field.
func (r *mutationResolver) CreateServiceDoc(ctx context.Context, orgID string, serviceID string, input model.CreateServiceDocInput) (*model.ServiceDoc, error) {
	d, err := r.Catalog.CreateServiceDoc(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDocToModel(d), nil
}

// UpdateServiceDoc is the resolver for the updateServiceDoc field.
func (r *mutationResolver) UpdateServiceDoc(ctx context.Context, orgID string, serviceID string, id string, input model.UpdateServiceDocInput) (*model.ServiceDoc, error) {
	d, err := r.Catalog.UpdateServiceDoc(ctx, orgID, serviceID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDocToModel(d), nil
}

// DeleteServiceDoc is the resolver for the deleteServiceDoc field.
func (r *mutationResolver) DeleteServiceDoc(ctx context.Context, orgID string, serviceID string, id string) (bool, error) {
	return true, r.Catalog.DeleteServiceDoc(ctx, orgID, serviceID, id)
}

// CreateServiceDiagram is the resolver for the createServiceDiagram field.
func (r *mutationResolver) CreateServiceDiagram(ctx context.Context, orgID string, serviceID string, input model.CreateServiceDiagramInput) (*model.ServiceDiagram, error) {
	d, err := r.Catalog.CreateServiceDiagram(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDiagramToModel(d), nil
}

// DeleteServiceDiagram is the resolver for the deleteServiceDiagram field.
func (r *mutationResolver) DeleteServiceDiagram(ctx context.Context, orgID string, serviceID string, diagramID string) (bool, error) {
	return true, r.Catalog.DeleteServiceDiagram(ctx, orgID, serviceID, diagramID)
}

// CreateServiceDb is the resolver for the createServiceDB field.
func (r *mutationResolver) CreateServiceDb(ctx context.Context, orgID string, serviceID string, input model.CreateServiceDBInput) (*model.ServiceDb, error) {
	d, err := r.Catalog.CreateServiceDB(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBToModel(d), nil
}

// UpdateServiceDb is the resolver for the updateServiceDB field.
func (r *mutationResolver) UpdateServiceDb(ctx context.Context, orgID string, serviceID string, id string, input model.UpdateServiceDBInput) (*model.ServiceDb, error) {
	d, err := r.Catalog.UpdateServiceDB(ctx, orgID, serviceID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBToModel(d), nil
}

// DeleteServiceDb is the resolver for the deleteServiceDB field.
func (r *mutationResolver) DeleteServiceDb(ctx context.Context, orgID string, serviceID string, id string) (bool, error) {
	return true, r.Catalog.DeleteServiceDB(ctx, orgID, serviceID, id)
}

// CreateServiceDBVersion is the resolver for the createServiceDBVersion field.
func (r *mutationResolver) CreateServiceDBVersion(ctx context.Context, orgID string, serviceID string, serviceDbID string, input model.CreateServiceDBVersionInput) (*model.ServiceDBVersion, error) {
	v, err := r.Catalog.CreateServiceDBVersion(ctx, orgID, serviceID, serviceDbID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBVersionToModel(orgID, *v), nil
}

// RestoreServiceDBVersion is the resolver for the restoreServiceDBVersion field.
func (r *mutationResolver) RestoreServiceDBVersion(ctx context.Context, orgID string, serviceID string, serviceDbID string, versionID string) (*model.ServiceDb, error) {
	d, err := r.Catalog.RestoreServiceDBVersion(ctx, orgID, serviceID, serviceDbID, versionID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBToModel(d), nil
}

// CreateAPIEndpoint is the resolver for the createAPIEndpoint field.
func (r *mutationResolver) CreateAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, input model.CreateAPIEndpointInput) (*model.APIEndpoint, error) {
	e, err := r.Catalog.CreateAPIEndpoint(ctx, orgID, serviceID, apiGroupID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.APIEndpointToModel(e), nil
}

// UpdateAPIEndpoint is the resolver for the updateAPIEndpoint field.
func (r *mutationResolver) UpdateAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string, input model.UpdateAPIEndpointInput) (*model.APIEndpoint, error) {
	e, err := r.Catalog.UpdateAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.APIEndpointToModel(e), nil
}

// DeleteAPIEndpoint is the resolver for the deleteAPIEndpoint field.
func (r *mutationResolver) DeleteAPIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string) (bool, error) {
	return true, r.Catalog.DeleteAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id)
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, orgID string, folderID *string, teamID *string) ([]*model.Service, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	tid := ""
	if teamID != nil {
		tid = *teamID
	}
	services, err := r.Catalog.ListServices(ctx, orgID, fid, tid)
	if err != nil {
		return nil, err
	}
	return convert.ServicesToModel(services), nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, orgID string, id string) (*model.Service, error) {
	s, err := r.Catalog.GetService(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.ServiceToModel(s), nil
}

// APIGroups is the resolver for the apiGroups field.
func (r *queryResolver) APIGroups(ctx context.Context, orgID string, serviceID string) ([]*model.APIGroup, error) {
	groups, err := r.Catalog.ListAPIGroups(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.APIGroupsToModel(groups), nil
}

// APIGroup is the resolver for the apiGroup field.
func (r *queryResolver) APIGroup(ctx context.Context, orgID string, serviceID string, id string) (*model.APIGroup, error) {
	g, err := r.Catalog.GetAPIGroup(ctx, orgID, serviceID, id)
	if err != nil {
		return nil, err
	}
	return convert.APIGroupToModel(g), nil
}

// APIGroupVersions is the resolver for the apiGroupVersions field.
func (r *queryResolver) APIGroupVersions(ctx context.Context, orgID string, serviceID string, apiGroupID string) ([]*model.APIGroupVersion, error) {
	versions, err := r.Catalog.ListAPIGroupVersions(ctx, orgID, serviceID, apiGroupID)
	if err != nil {
		return nil, err
	}
	return convert.APIGroupVersionsToModel(orgID, versions), nil
}

// ServiceDocs is the resolver for the serviceDocs field.
func (r *queryResolver) ServiceDocs(ctx context.Context, orgID string, serviceID string) ([]*model.ServiceDoc, error) {
	docs, err := r.Catalog.ListServiceDocs(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDocsToModel(docs), nil
}

// ServiceDoc is the resolver for the serviceDoc field.
func (r *queryResolver) ServiceDoc(ctx context.Context, orgID string, serviceID string, id string) (*model.ServiceDoc, error) {
	d, err := r.Catalog.GetServiceDoc(ctx, orgID, serviceID, id)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDocToModel(d), nil
}

// ServiceDiagrams is the resolver for the serviceDiagrams field.
func (r *queryResolver) ServiceDiagrams(ctx context.Context, orgID string, serviceID string) ([]*model.ServiceDiagram, error) {
	diagrams, err := r.Catalog.ListServiceDiagrams(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDiagramsToModel(diagrams), nil
}

// ServiceDBs is the resolver for the serviceDBs field.
func (r *queryResolver) ServiceDBs(ctx context.Context, orgID string, serviceID string) ([]*model.ServiceDb, error) {
	dbs, err := r.Catalog.ListServiceDBs(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBsToModel(dbs), nil
}

// ServiceDb is the resolver for the serviceDB field.
func (r *queryResolver) ServiceDb(ctx context.Context, orgID string, serviceID string, id string) (*model.ServiceDb, error) {
	d, err := r.Catalog.GetServiceDB(ctx, orgID, serviceID, id)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBToModel(d), nil
}

// ServiceDBVersions is the resolver for the serviceDBVersions field.
func (r *queryResolver) ServiceDBVersions(ctx context.Context, orgID string, serviceID string, serviceDbID string) ([]*model.ServiceDBVersion, error) {
	versions, err := r.Catalog.ListServiceDBVersions(ctx, orgID, serviceID, serviceDbID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceDBVersionsToModel(orgID, versions), nil
}

// APIEndpoints is the resolver for the apiEndpoints field.
func (r *queryResolver) APIEndpoints(ctx context.Context, orgID string, serviceID string, apiGroupID string) ([]*model.APIEndpoint, error) {
	endpoints, err := r.Catalog.ListAPIEndpoints(ctx, orgID, serviceID, apiGroupID)
	if err != nil {
		return nil, err
	}
	return convert.APIEndpointsToModel(endpoints), nil
}

// APIEndpoint is the resolver for the apiEndpoint field.
func (r *queryResolver) APIEndpoint(ctx context.Context, orgID string, serviceID string, apiGroupID string, id string) (*model.APIEndpoint, error) {
	e, err := r.Catalog.GetAPIEndpoint(ctx, orgID, serviceID, apiGroupID, id)
	if err != nil {
		return nil, err
	}
	return convert.APIEndpointToModel(e), nil
}

// APIGroupSpec is the resolver for the apiGroupSpec field.
func (r *queryResolver) APIGroupSpec(ctx context.Context, orgID string, serviceID string, apiGroupID string, versionID *string) (*model.FileDownload, error) {
	vid := ""
	if versionID != nil {
		vid = *versionID
	}
	spec, err := r.Catalog.GetAPIGroupSpec(ctx, orgID, serviceID, apiGroupID, vid)
	if err != nil {
		return nil, err
	}
	return &model.FileDownload{
		APIGroupID: spec.APIGroupID,
		FileName:   spec.FileName,
		Content:    spec.Content,
	}, nil
}

// ServiceStats is the resolver for the serviceStats field.
func (r *queryResolver) ServiceStats(ctx context.Context, orgID string, serviceID *string) ([]*model.ServiceStats, error) {
	stats, err := r.Catalog.ListServiceStats(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceStatsListToModel(stats), nil
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *serviceResolver) CreatedByActor(ctx context.Context, obj *model.Service) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *serviceResolver) UpdatedByActor(ctx context.Context, obj *model.Service) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *serviceDBResolver) CreatedByActor(ctx context.Context, obj *model.ServiceDb) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *serviceDBResolver) UpdatedByActor(ctx context.Context, obj *model.ServiceDb) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *serviceDBVersionResolver) CreatedByActor(ctx context.Context, obj *model.ServiceDBVersion) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// FileURL is the resolver for the fileUrl field.
func (r *serviceDocResolver) FileURL(ctx context.Context, obj *model.ServiceDoc) (*string, error) {
	return r.resolveAssetURL(ctx, obj.OrgID, obj.FileAssetID)
}

// APIGroupVersion returns generated.APIGroupVersionResolver implementation.
func (r *Resolver) APIGroupVersion() generated.APIGroupVersionResolver {
	return &aPIGroupVersionResolver{r}
}

// Service returns generated.ServiceResolver implementation.
func (r *Resolver) Service() generated.ServiceResolver { return &serviceResolver{r} }

// ServiceDB returns generated.ServiceDBResolver implementation.
func (r *Resolver) ServiceDB() generated.ServiceDBResolver { return &serviceDBResolver{r} }

// ServiceDBVersion returns generated.ServiceDBVersionResolver implementation.
func (r *Resolver) ServiceDBVersion() generated.ServiceDBVersionResolver {
	return &serviceDBVersionResolver{r}
}

// ServiceDoc returns generated.ServiceDocResolver implementation.
func (r *Resolver) ServiceDoc() generated.ServiceDocResolver { return &serviceDocResolver{r} }

type aPIGroupVersionResolver struct{ *Resolver }
type serviceResolver struct{ *Resolver }
type serviceDBResolver struct{ *Resolver }
type serviceDBVersionResolver struct{ *Resolver }
type serviceDocResolver struct{ *Resolver }
