package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/model"
)

// FlowDiagramComponents is the resolver for the flowDiagramComponents field.
func (r *queryResolver) FlowDiagramComponents(ctx context.Context, orgID string) (*model.FlowDiagramComponents, error) {
	res, err := r.Client.ListFlowDiagramComponents(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return &model.FlowDiagramComponents{
		Components:       flowComponentsToModel(res.Components),
		CustomComponents: flowComponentsToModel(res.CustomComponents),
	}, nil
}

// Components is the resolver for the components field.
func (r *queryResolver) Components(ctx context.Context, orgID string) (*model.Components, error) {
	res, err := r.Client.ListComponents(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return &model.Components{
		Components:       componentsToModel(res.Components),
		CustomComponents: componentsToModel(res.CustomComponents),
	}, nil
}
