package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateCloudConnection is the resolver for the createCloudConnection field.
func (r *mutationResolver) CreateCloudConnection(ctx context.Context, orgID string, input model.CreateCloudConnectionInput) (*model.CloudConnection, error) {
	c, err := r.Billing.CreateCloudConnection(ctx, orgID, convert.CreateCloudConnectionInputToBody(input))
	if err != nil {
		return nil, err
	}
	return convert.CloudConnectionToModel(c), nil
}

// DeleteCloudConnection is the resolver for the deleteCloudConnection field.
func (r *mutationResolver) DeleteCloudConnection(ctx context.Context, orgID string, connectionID string) (bool, error) {
	if err := r.Billing.DeleteCloudConnection(ctx, orgID, connectionID); err != nil {
		return false, err
	}
	return true, nil
}

// TestCloudConnection is the resolver for the testCloudConnection field.
func (r *mutationResolver) TestCloudConnection(ctx context.Context, orgID string, connectionID string) (*model.TestCloudConnectionResult, error) {
	result, err := r.Billing.TestCloudConnection(ctx, orgID, connectionID)
	if err != nil {
		return nil, err
	}
	return convert.TestCloudConnectionResultToModel(result), nil
}

// SyncCloudConnection is the resolver for the syncCloudConnection field.
func (r *mutationResolver) SyncCloudConnection(ctx context.Context, orgID string, connectionID string) (bool, error) {
	return r.Billing.SyncCloudConnection(ctx, orgID, connectionID)
}

// CreateServiceCostTagRule is the resolver for the createServiceCostTagRule field.
func (r *mutationResolver) CreateServiceCostTagRule(ctx context.Context, orgID string, serviceID string, tagKey string, tagValue string) (*model.ServiceCostTagRule, error) {
	rule, err := r.Billing.CreateServiceCostTagRule(ctx, orgID, serviceID, map[string]interface{}{
		"tagKey":   tagKey,
		"tagValue": tagValue,
	})
	if err != nil {
		return nil, err
	}
	return convert.ServiceCostTagRuleToModel(rule), nil
}

// DeleteServiceCostTagRule is the resolver for the deleteServiceCostTagRule field.
func (r *mutationResolver) DeleteServiceCostTagRule(ctx context.Context, orgID string, serviceID string, ruleID string) (bool, error) {
	if err := r.Billing.DeleteServiceCostTagRule(ctx, orgID, serviceID, ruleID); err != nil {
		return false, err
	}
	return true, nil
}

// CloudConnections is the resolver for the cloudConnections field.
func (r *queryResolver) CloudConnections(ctx context.Context, orgID string) ([]*model.CloudConnection, error) {
	rows, err := r.Billing.ListCloudConnections(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.CloudConnectionListToModel(rows), nil
}

// CloudConnection is the resolver for the cloudConnection field.
func (r *queryResolver) CloudConnection(ctx context.Context, orgID string, connectionID string) (*model.CloudConnection, error) {
	c, err := r.Billing.GetCloudConnection(ctx, orgID, connectionID)
	if err != nil {
		return nil, err
	}
	return convert.CloudConnectionToModel(c), nil
}

// ServiceCostSummary is the resolver for the serviceCostSummary field.
func (r *queryResolver) ServiceCostSummary(ctx context.Context, orgID string, serviceID string) (*model.ServiceCostSummary, error) {
	s, err := r.Billing.GetServiceCostSummary(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceCostSummaryToModel(s), nil
}

// ServiceCostResources is the resolver for the serviceCostResources field.
func (r *queryResolver) ServiceCostResources(ctx context.Context, orgID string, serviceID string) ([]*model.InfraResource, error) {
	rows, err := r.Billing.ListServiceCostResources(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.InfraResourceListToModel(rows), nil
}

// ServiceCostTrend is the resolver for the serviceCostTrend field.
func (r *queryResolver) ServiceCostTrend(ctx context.Context, orgID string, serviceID string, days *int) ([]*model.CostTrendPoint, error) {
	rows, err := r.Billing.GetServiceCostTrend(ctx, orgID, serviceID, days)
	if err != nil {
		return nil, err
	}
	return convert.CostTrendPointListToModel(rows), nil
}

// ServiceCostTagRules is the resolver for the serviceCostTagRules field.
func (r *queryResolver) ServiceCostTagRules(ctx context.Context, orgID string, serviceID string) ([]*model.ServiceCostTagRule, error) {
	rows, err := r.Billing.ListServiceCostTagRules(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceCostTagRuleListToModel(rows), nil
}
