package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
)

// UpdateServiceDependencies is the resolver for the updateServiceDependencies field.
func (r *mutationResolver) UpdateServiceDependencies(ctx context.Context, orgID string, serviceID string, input model.UpdateServiceDependenciesInput) ([]*model.Dependency, error) {
	dependencies, err := r.Dependency.UpdateServiceDependencies(ctx, orgID, serviceID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.DependenciesToModel(dependencies), nil
}

// Dependencies is the resolver for the dependencies field.
func (r *queryResolver) Dependencies(ctx context.Context, orgID string, serviceID string, direction *string, criticality *string) ([]*model.Dependency, error) {
	dependencies, err := r.Dependency.ListDependencies(ctx, orgID, serviceID, direction, criticality)
	if err != nil {
		return nil, err
	}
	return convert.DependenciesToModel(dependencies), nil
}

// ServiceDependencyGraph is the resolver for the serviceDependencyGraph field.
func (r *queryResolver) ServiceDependencyGraph(ctx context.Context, orgID string, serviceID string) ([]*model.Dependency, error) {
	dependencies, err := r.Dependency.GetServiceDependencyGraph(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.DependenciesToModel(dependencies), nil
}

// DependencyGraph is the resolver for the dependencyGraph field.
func (r *queryResolver) DependencyGraph(ctx context.Context, orgID string) ([]*model.Dependency, error) {
	dependencies, err := r.Dependency.GetDependencyGraph(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.DependenciesToModel(dependencies), nil
}

// ServiceImpact is the resolver for the serviceImpact field.
func (r *queryResolver) ServiceImpact(ctx context.Context, orgID string, serviceID string, direction *string, maxDepth *int) ([]*model.Dependency, error) {
	dependencies, err := r.Dependency.GetServiceImpact(ctx, orgID, serviceID, direction, maxDepth)
	if err != nil {
		return nil, err
	}
	return convert.DependenciesToModel(dependencies), nil
}
