package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// PreviewImageURL is the resolver for the previewImageUrl field.
func (r *diagramResolver) PreviewImageURL(ctx context.Context, obj *model.Diagram) (*string, error) {
	if obj.PreviewAssetID == nil {
		return nil, nil
	}
	return r.resolveAssetURL(ctx, obj.OrgID, *obj.PreviewAssetID)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *diagramResolver) CreatedByActor(ctx context.Context, obj *model.Diagram) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *diagramResolver) UpdatedByActor(ctx context.Context, obj *model.Diagram) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// ImageURL is the resolver for the imageUrl field.
func (r *diagramImageResolver) ImageURL(ctx context.Context, obj *model.DiagramImage) (*string, error) {
	return r.resolveAssetURL(ctx, obj.OrgID, obj.AssetID)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *diagramVersionResolver) CreatedByActor(ctx context.Context, obj *model.DiagramVersion) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// CreateDiagram is the resolver for the createDiagram field.
func (r *mutationResolver) CreateDiagram(ctx context.Context, orgID string, input model.CreateDiagramInput) (*model.Diagram, error) {
	d, err := r.Client.CreateDiagram(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

// UpdateDiagram is the resolver for the updateDiagram field.
func (r *mutationResolver) UpdateDiagram(ctx context.Context, orgID string, id string, input model.UpdateDiagramInput) (*model.Diagram, error) {
	d, err := r.Client.UpdateDiagram(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

// DeleteDiagram is the resolver for the deleteDiagram field.
func (r *mutationResolver) DeleteDiagram(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteDiagram(ctx, orgID, id)
}

// SyncDiagram is the resolver for the syncDiagram field.
func (r *mutationResolver) SyncDiagram(ctx context.Context, orgID string, input model.SyncDiagramInput) (*model.SyncDiagramResult, error) {
	out, err := r.Client.SyncDiagram(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	res := &model.SyncDiagramResult{
		DiagramID:      strFromMap(out, "diagramId"),
		VersionCreated: boolFromMap(out, "versionCreated"),
	}
	if v := optStrFromMap(out, "versionId"); v != nil {
		res.VersionID = v
	}
	return res, nil
}

// CreateDiagramVersion is the resolver for the createDiagramVersion field.
func (r *mutationResolver) CreateDiagramVersion(ctx context.Context, orgID string, diagramID string, label *string) (*model.DiagramVersion, error) {
	body := map[string]interface{}{}
	if label != nil {
		body["label"] = *label
	}
	v, err := r.Client.CreateDiagramVersion(ctx, orgID, diagramID, body)
	if err != nil {
		return nil, err
	}
	return diagramVersionToModel(orgID, *v), nil
}

// RestoreDiagramVersion is the resolver for the restoreDiagramVersion field.
func (r *mutationResolver) RestoreDiagramVersion(ctx context.Context, orgID string, diagramID string, versionID string) (*model.Diagram, error) {
	d, err := r.Client.RestoreDiagramVersion(ctx, orgID, diagramID, versionID)
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

// Diagrams is the resolver for the diagrams field.
func (r *queryResolver) Diagrams(ctx context.Context, orgID string, folderID *string) ([]*model.Diagram, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	diagrams, err := r.Client.ListDiagrams(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return diagramsToModel(diagrams), nil
}

// Diagram is the resolver for the diagram field.
func (r *queryResolver) Diagram(ctx context.Context, orgID string, id string) (*model.Diagram, error) {
	d, err := r.Client.GetDiagram(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return diagramToModel(d), nil
}

// DiagramContent is the resolver for the diagramContent field.
func (r *queryResolver) DiagramContent(ctx context.Context, orgID string, id string) (*model.DiagramContent, error) {
	content, err := r.Client.GetDiagramContent(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return &model.DiagramContent{DiagramID: id, Content: content}, nil
}

// DiagramVersions is the resolver for the diagramVersions field.
func (r *queryResolver) DiagramVersions(ctx context.Context, orgID string, diagramID string) ([]*model.DiagramVersion, error) {
	versions, err := r.Client.ListDiagramVersions(ctx, orgID, diagramID)
	if err != nil {
		return nil, err
	}
	return diagramVersionsToModel(orgID, versions), nil
}

// DiagramVersionContent is the resolver for the diagramVersionContent field.
func (r *queryResolver) DiagramVersionContent(ctx context.Context, orgID string, diagramID string, versionID string) (*model.DiagramContent, error) {
	content, err := r.Client.GetDiagramVersionContent(ctx, orgID, diagramID, versionID)
	if err != nil {
		return nil, err
	}
	return &model.DiagramContent{DiagramID: diagramID, Content: content}, nil
}

// DiagramImages is the resolver for the diagramImages field.
func (r *queryResolver) DiagramImages(ctx context.Context, orgID string, diagramID string) ([]*model.DiagramImage, error) {
	images, err := r.Client.ListDiagramImages(ctx, orgID, diagramID)
	if err != nil {
		return nil, err
	}
	return diagramImagesToModel(images), nil
}

// Diagram returns generated.DiagramResolver implementation.
func (r *Resolver) Diagram() generated.DiagramResolver { return &diagramResolver{r} }

// DiagramImage returns generated.DiagramImageResolver implementation.
func (r *Resolver) DiagramImage() generated.DiagramImageResolver { return &diagramImageResolver{r} }

// DiagramVersion returns generated.DiagramVersionResolver implementation.
func (r *Resolver) DiagramVersion() generated.DiagramVersionResolver {
	return &diagramVersionResolver{r}
}

type diagramResolver struct{ *Resolver }
type diagramImageResolver struct{ *Resolver }
type diagramVersionResolver struct{ *Resolver }
