package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// FileURL is the resolver for the fileUrl field.
func (r *docResolver) FileURL(ctx context.Context, obj *model.Doc) (*string, error) {
	return r.resolveAssetURL(ctx, obj.OrgID, obj.FileAssetID)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *docResolver) CreatedByActor(ctx context.Context, obj *model.Doc) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *docResolver) UpdatedByActor(ctx context.Context, obj *model.Doc) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// CreateDoc is the resolver for the createDoc field.
func (r *mutationResolver) CreateDoc(ctx context.Context, orgID string, input model.CreateDocInput) (*model.Doc, error) {
	d, err := r.DocAPI.CreateDoc(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.DocToModel(d), nil
}

// UpdateDoc is the resolver for the updateDoc field.
func (r *mutationResolver) UpdateDoc(ctx context.Context, orgID string, id string, input model.UpdateDocInput) (*model.Doc, error) {
	d, err := r.DocAPI.UpdateDoc(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.DocToModel(d), nil
}

// DeleteDoc is the resolver for the deleteDoc field.
func (r *mutationResolver) DeleteDoc(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.DocAPI.DeleteDoc(ctx, orgID, id)
}

// Docs is the resolver for the docs field.
func (r *queryResolver) Docs(ctx context.Context, orgID string, folderID *string) ([]*model.Doc, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	docs, err := r.DocAPI.ListDocs(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return convert.DocsToModel(docs), nil
}

// Doc is the resolver for the doc field.
func (r *queryResolver) Doc(ctx context.Context, orgID string, id string) (*model.Doc, error) {
	d, err := r.DocAPI.GetDoc(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.DocToModel(d), nil
}

// Doc returns generated.DocResolver implementation.
func (r *Resolver) Doc() generated.DocResolver { return &docResolver{r} }

type docResolver struct{ *Resolver }
