package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/model"
)

// Features is the resolver for the features field.
func (r *queryResolver) Features(ctx context.Context) (*model.Features, error) {
	features, err := r.FeaturesAPI.GetFeatures(ctx)
	if err != nil {
		return nil, err
	}
	out := &model.Features{Github: features.GitHub, Enterprise: features.Enterprise}
	if features.BillingURL != "" {
		out.BillingURL = &features.BillingURL
	}
	return out, nil
}
