package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, orgID string, input model.CreateFolderInput) (*model.Folder, error) {
	f, err := r.Client.CreateFolder(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FolderToModel(f), nil
}

// UpdateFolder is the resolver for the updateFolder field.
func (r *mutationResolver) UpdateFolder(ctx context.Context, orgID string, id string, input model.UpdateFolderInput) (*model.Folder, error) {
	f, err := r.Client.UpdateFolder(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FolderToModel(f), nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteFolder(ctx, orgID, id)
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context, orgID string, typeArg *string, parentID *string) ([]*model.Folder, error) {
	t := ""
	if typeArg != nil {
		t = *typeArg
	}
	p := ""
	if parentID != nil {
		p = *parentID
	}
	folders, err := r.Client.ListFolders(ctx, orgID, t, p)
	if err != nil {
		return nil, err
	}
	return convert.FoldersToModel(folders), nil
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, orgID string, id string) (*model.Folder, error) {
	f, err := r.Client.GetFolder(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.FolderToModel(f), nil
}
