package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// GithubAppInstallURL is the resolver for the githubAppInstallURL field.
func (r *mutationResolver) GithubAppInstallURL(ctx context.Context, orgID string) (string, error) {
	return r.GitHubAPI.GetGitHubAppInstallURL(ctx, orgID)
}

// DisconnectGitHubApp is the resolver for the disconnectGitHubApp field.
func (r *mutationResolver) DisconnectGitHubApp(ctx context.Context, orgID string) (bool, error) {
	return true, r.GitHubAPI.DisconnectGitHubApp(ctx, orgID)
}

// StartRepositoryOnboarding is the resolver for the startRepositoryOnboarding field.
func (r *mutationResolver) StartRepositoryOnboarding(ctx context.Context, input model.StartRepositoryOnboardingInput) (*model.RepositoryOnboardingBatch, error) {
	batch, err := r.GitHubAPI.StartRepositoryOnboarding(ctx, input.OrgID, uigraphapi.StartRepositoryOnboardingInput{
		TeamID:        input.TeamID,
		RepositoryIDs: input.RepositoryIds,
	})
	if err != nil {
		return nil, err
	}
	return convert.RepositoryOnboardingBatchToModel(batch)
}

// RecheckRepositoryOnboarding is the resolver for the recheckRepositoryOnboarding field.
func (r *mutationResolver) RecheckRepositoryOnboarding(ctx context.Context, orgID string, batchID string, onboardingID string) (*model.RepositoryOnboarding, error) {
	onboarding, err := r.GitHubAPI.RecheckRepositoryOnboarding(ctx, orgID, batchID, onboardingID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryOnboardingToModel(*onboarding)
}

// RetryRepositoryOnboarding is the resolver for the retryRepositoryOnboarding field.
func (r *mutationResolver) RetryRepositoryOnboarding(ctx context.Context, orgID string, batchID string, onboardingID string) (*model.RepositoryOnboarding, error) {
	onboarding, err := r.GitHubAPI.RetryRepositoryOnboarding(ctx, orgID, batchID, onboardingID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryOnboardingToModel(*onboarding)
}

// GithubApp is the resolver for the githubApp field.
func (r *queryResolver) GithubApp(ctx context.Context, orgID string) (*model.GitHubAppInstallation, error) {
	installation, err := r.GitHubAPI.GetGitHubApp(ctx, orgID)
	if uigraphapi.IsNotFound(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if installation == nil {
		return nil, nil
	}
	return convert.GitHubAppInstallationToModel(installation), nil
}

// GithubRepositories is the resolver for the githubRepositories field.
func (r *queryResolver) GithubRepositories(ctx context.Context, orgID string) ([]*model.GitHubRepository, error) {
	repositories, err := r.GitHubAPI.ListGitHubRepositories(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.GitHubRepositoriesToModel(repositories), nil
}

// RepositoryOnboarding is the resolver for the repositoryOnboarding field.
func (r *queryResolver) RepositoryOnboarding(ctx context.Context, orgID string, batchID string) (*model.RepositoryOnboardingBatch, error) {
	batch, err := r.GitHubAPI.GetRepositoryOnboarding(ctx, orgID, batchID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryOnboardingBatchToModel(batch)
}
