package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
)

// GithubAppInstallURL is the resolver for the githubAppInstallURL field.
func (r *mutationResolver) GithubAppInstallURL(ctx context.Context, orgID string) (string, error) {
	return r.GitHubAPI.GetGitHubAppInstallURL(ctx, orgID)
}

// DisconnectGitHubApp is the resolver for the disconnectGitHubApp field.
func (r *mutationResolver) DisconnectGitHubApp(ctx context.Context, orgID string) (bool, error) {
	return true, r.GitHubAPI.DisconnectGitHubApp(ctx, orgID)
}

// StartRepositoryImport is the resolver for the startRepositoryImport field.
func (r *mutationResolver) StartRepositoryImport(ctx context.Context, orgID string, teamID string, repositoryID string) (*model.RepositoryImport, error) {
	value, err := r.GitHubAPI.StartRepositoryImport(ctx, orgID, teamID, repositoryID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryImportToModel(*value)
}

// RecheckRepositoryImport is the resolver for the recheckRepositoryImport field.
func (r *mutationResolver) RecheckRepositoryImport(ctx context.Context, orgID string, importID string) (*model.RepositoryImport, error) {
	value, err := r.GitHubAPI.RecheckRepositoryImport(ctx, orgID, importID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryImportToModel(*value)
}

// RetryRepositoryImport is the resolver for the retryRepositoryImport field.
func (r *mutationResolver) RetryRepositoryImport(ctx context.Context, orgID string, importID string) (*model.RepositoryImport, error) {
	value, err := r.GitHubAPI.RetryRepositoryImport(ctx, orgID, importID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryImportToModel(*value)
}

// GithubAppEnabled is the resolver for the githubAppEnabled field.
func (r *queryResolver) GithubAppEnabled(ctx context.Context, orgID string) (bool, error) {
	enabled, _, err := r.GitHubAPI.GetGitHubApp(ctx, orgID)
	if err != nil {
		return false, err
	}
	return enabled, nil
}

// GithubApp is the resolver for the githubApp field.
func (r *queryResolver) GithubApp(ctx context.Context, orgID string) (*model.GitHubAppInstallation, error) {
	_, installation, err := r.GitHubAPI.GetGitHubApp(ctx, orgID)
	if err != nil {
		return nil, err
	}
	if installation == nil {
		return nil, nil
	}
	return convert.GitHubAppInstallationToModel(installation), nil
}

// GithubRepositories is the resolver for the githubRepositories field.
func (r *queryResolver) GithubRepositories(ctx context.Context, orgID string) ([]*model.GitHubRepository, error) {
	repositories, err := r.GitHubAPI.ListGitHubRepositories(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.GitHubRepositoriesToModel(repositories), nil
}

// RepositoryImport is the resolver for the repositoryImport field.
func (r *queryResolver) RepositoryImport(ctx context.Context, orgID string, importID string) (*model.RepositoryImport, error) {
	value, err := r.GitHubAPI.GetRepositoryImport(ctx, orgID, importID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryImportToModel(*value)
}

// RepositoryImports is the resolver for the repositoryImports field.
func (r *queryResolver) RepositoryImports(ctx context.Context, orgID string) ([]*model.RepositoryImport, error) {
	values, err := r.GitHubAPI.ListRepositoryImports(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.RepositoryImportsToModel(values)
}

// LatestRepositoryImport is the resolver for the latestRepositoryImport field.
func (r *queryResolver) LatestRepositoryImport(ctx context.Context, orgID string) (*model.RepositoryImport, error) {
	value, err := r.GitHubAPI.GetLatestRepositoryImport(ctx, orgID)
	if err != nil {
		return nil, err
	}
	if value == nil {
		return nil, nil
	}
	return convert.RepositoryImportToModel(*value)
}
