package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/uigraph/graphql/internal/graph/model"
)

// CostSavingsSummary is the resolver for the costSavingsSummary field.
func (r *queryResolver) CostSavingsSummary(ctx context.Context, orgID string, period *string, modelID *string) (*model.SavingsSummary, error) {
	panic(fmt.Errorf("not implemented: CostSavingsSummary - costSavingsSummary"))
}

// CostSavingsTimeseries is the resolver for the costSavingsTimeseries field.
func (r *queryResolver) CostSavingsTimeseries(ctx context.Context, orgID string, period *string, modelID *string) ([]*model.DailySavings, error) {
	panic(fmt.Errorf("not implemented: CostSavingsTimeseries - costSavingsTimeseries"))
}

// CostSavingsByTool is the resolver for the costSavingsByTool field.
func (r *queryResolver) CostSavingsByTool(ctx context.Context, orgID string, period *string, modelID *string) ([]*model.ToolSavings, error) {
	panic(fmt.Errorf("not implemented: CostSavingsByTool - costSavingsByTool"))
}

// CostSavingsByModel is the resolver for the costSavingsByModel field.
func (r *queryResolver) CostSavingsByModel(ctx context.Context, orgID string, period *string) ([]*model.ModelSavings, error) {
	panic(fmt.Errorf("not implemented: CostSavingsByModel - costSavingsByModel"))
}

// CostSavingsByUser is the resolver for the costSavingsByUser field.
func (r *queryResolver) CostSavingsByUser(ctx context.Context, orgID string, period *string, modelID *string) ([]*model.UserSavings, error) {
	panic(fmt.Errorf("not implemented: CostSavingsByUser - costSavingsByUser"))
}
