package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// Series is the resolver for the series field.
func (r *mlRunResolver) Series(ctx context.Context, obj *model.MlRun) (any, error) {
	points, err := r.MLStudio.ListMLRunSeries(ctx, obj.OrgID, obj.ID)
	if err != nil {
		return nil, err
	}
	return convert.MLRunSeriesToJSON(points), nil
}

// CreateMlProject is the resolver for the createMlProject field.
func (r *mutationResolver) CreateMlProject(ctx context.Context, orgID string, input model.CreateMlProjectInput) (*model.MlProject, error) {
	p, err := r.MLStudio.CreateMLProject(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLProjectToModel(p), nil
}

// CreateMlDeployment is the resolver for the createMlDeployment field.
func (r *mutationResolver) CreateMlDeployment(ctx context.Context, orgID string, input model.CreateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.CreateMLDeployment(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// UpdateMlDeployment is the resolver for the updateMlDeployment field.
func (r *mutationResolver) UpdateMlDeployment(ctx context.Context, orgID string, id string, input model.UpdateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.UpdateMLDeployment(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// DeleteMlDeployment is the resolver for the deleteMlDeployment field.
func (r *mutationResolver) DeleteMlDeployment(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLDeployment(ctx, orgID, id)
}

// CreateMlFinding is the resolver for the createMlFinding field.
func (r *mutationResolver) CreateMlFinding(ctx context.Context, orgID string, input model.CreateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.CreateMLFinding(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// UpdateMlFinding is the resolver for the updateMlFinding field.
func (r *mutationResolver) UpdateMlFinding(ctx context.Context, orgID string, id string, input model.UpdateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.UpdateMLFinding(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// DeleteMlFinding is the resolver for the deleteMlFinding field.
func (r *mutationResolver) DeleteMlFinding(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLFinding(ctx, orgID, id)
}

// UpdateMlModel is the resolver for the updateMlModel field.
func (r *mutationResolver) UpdateMlModel(ctx context.Context, orgID string, id string, domain *string, problemType *string, license *string, references []string, intendedUse *string, limitations *string, ethicalConsiderations *string, caveats *string) (*model.MlModel, error) {
	body := map[string]interface{}{
		"domain":                derefStr(domain),
		"problemType":           derefStr(problemType),
		"license":               derefStr(license),
		"references":            references,
		"intendedUse":           derefStr(intendedUse),
		"limitations":           derefStr(limitations),
		"ethicalConsiderations": derefStr(ethicalConsiderations),
		"caveats":               derefStr(caveats),
	}
	m, err := r.MLStudio.UpdateMLModel(ctx, orgID, id, body)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// CreateMlVersionDeploymentUpdate is the resolver for the createMlVersionDeploymentUpdate field.
func (r *mutationResolver) CreateMlVersionDeploymentUpdate(ctx context.Context, orgID string, versionID string, toStatus string) (*model.MlVersionDeploymentUpdate, error) {
	u, err := r.MLStudio.CreateVersionDeploymentUpdate(ctx, orgID, versionID, map[string]interface{}{"toStatus": toStatus})
	if err != nil {
		return nil, err
	}
	return convert.MLVersionDeploymentUpdateToModel(u), nil
}

// MlProjects is the resolver for the mlProjects field.
func (r *queryResolver) MlProjects(ctx context.Context, orgID string) ([]*model.MlProject, error) {
	projects, err := r.MLStudio.ListMLProjects(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.MLProjectsToModel(projects), nil
}

// MlProject is the resolver for the mlProject field.
func (r *queryResolver) MlProject(ctx context.Context, orgID string, id string) (*model.MlProject, error) {
	p, err := r.MLStudio.GetMLProject(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLProjectToModel(p), nil
}

// MlModels is the resolver for the mlModels field.
func (r *queryResolver) MlModels(ctx context.Context, orgID string, projectID *string) ([]*model.MlModel, error) {
	models, err := r.MLStudio.ListMLModels(ctx, orgID, derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLModelsToModel(models), nil
}

// MlModel is the resolver for the mlModel field.
func (r *queryResolver) MlModel(ctx context.Context, orgID string, id string) (*model.MlModel, error) {
	m, err := r.MLStudio.GetMLModel(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// MlModelVersions is the resolver for the mlModelVersions field.
func (r *queryResolver) MlModelVersions(ctx context.Context, orgID string, modelID *string, projectID *string) ([]*model.MlModelVersion, error) {
	versions, err := r.MLStudio.ListMLModelVersions(ctx, orgID, derefStr(modelID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionsToModel(versions), nil
}

// MlModelVersion is the resolver for the mlModelVersion field.
func (r *queryResolver) MlModelVersion(ctx context.Context, orgID string, id string) (*model.MlModelVersion, error) {
	v, err := r.MLStudio.GetMLModelVersion(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionToModel(v), nil
}

// MlExperiments is the resolver for the mlExperiments field.
func (r *queryResolver) MlExperiments(ctx context.Context, orgID string, projectID *string) ([]*model.MlExperiment, error) {
	experiments, err := r.MLStudio.ListMLExperiments(ctx, orgID, derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentsToModel(experiments), nil
}

// MlExperiment is the resolver for the mlExperiment field.
func (r *queryResolver) MlExperiment(ctx context.Context, orgID string, id string) (*model.MlExperiment, error) {
	e, err := r.MLStudio.GetMLExperiment(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentToModel(e), nil
}

// MlRuns is the resolver for the mlRuns field.
func (r *queryResolver) MlRuns(ctx context.Context, orgID string, experimentID *string, projectID *string) ([]*model.MlRun, error) {
	runs, _, err := r.MLStudio.ListMLRuns(ctx, orgID, uigraphapi.MLRunQuery{
		ExperimentID: derefStr(experimentID),
		ProjectID:    derefStr(projectID),
	})
	if err != nil {
		return nil, err
	}
	return convert.MLRunsToModel(runs), nil
}

// MlRunsPage is the resolver for the mlRunsPage field.
func (r *queryResolver) MlRunsPage(ctx context.Context, orgID string, experimentID *string, projectID *string, search *string, limit *int, offset *int) (*model.MlRunPage, error) {
	query := uigraphapi.MLRunQuery{
		ExperimentID: derefStr(experimentID),
		ProjectID:    derefStr(projectID),
		Search:       derefStr(search),
	}
	if limit != nil {
		query.Limit = *limit
	}
	if offset != nil {
		query.Offset = *offset
	}
	runs, total, err := r.MLStudio.ListMLRuns(ctx, orgID, query)
	if err != nil {
		return nil, err
	}
	return &model.MlRunPage{
		Runs:  convert.MLRunsToModel(runs),
		Total: total,
	}, nil
}

// MlRun is the resolver for the mlRun field.
func (r *queryResolver) MlRun(ctx context.Context, orgID string, id string) (*model.MlRun, error) {
	run, err := r.MLStudio.GetMLRun(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLRunToModel(run), nil
}

// MlArtifacts is the resolver for the mlArtifacts field.
func (r *queryResolver) MlArtifacts(ctx context.Context, orgID string, runID *string) ([]*model.MlArtifact, error) {
	artifacts, err := r.MLStudio.ListMLArtifacts(ctx, orgID, derefStr(runID))
	if err != nil {
		return nil, err
	}
	return convert.MLArtifactsToModel(artifacts), nil
}

// MlDatasets is the resolver for the mlDatasets field.
func (r *queryResolver) MlDatasets(ctx context.Context, orgID string, experimentID *string) ([]*model.MlDataset, error) {
	datasets, err := r.MLStudio.ListMLDatasets(ctx, orgID, derefStr(experimentID))
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetsToModel(datasets), nil
}

// MlDataset is the resolver for the mlDataset field.
func (r *queryResolver) MlDataset(ctx context.Context, orgID string, id string) (*model.MlDataset, error) {
	ds, err := r.MLStudio.GetMLDataset(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetToModel(ds), nil
}

// MlDeployments is the resolver for the mlDeployments field.
func (r *queryResolver) MlDeployments(ctx context.Context, orgID string, modelID *string, versionID *string) ([]*model.MlDeployment, error) {
	deployments, err := r.MLStudio.ListMLDeployments(ctx, orgID, derefStr(modelID), derefStr(versionID))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentsToModel(deployments), nil
}

// MlFindings is the resolver for the mlFindings field.
func (r *queryResolver) MlFindings(ctx context.Context, orgID string, modelID *string, projectID *string) ([]*model.MlFinding, error) {
	findings, err := r.MLStudio.ListMLFindings(ctx, orgID, derefStr(modelID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingsToModel(findings), nil
}

// MlVersionDeploymentUpdates is the resolver for the mlVersionDeploymentUpdates field.
func (r *queryResolver) MlVersionDeploymentUpdates(ctx context.Context, orgID string, versionID *string, projectID *string) ([]*model.MlVersionDeploymentUpdate, error) {
	updates, err := r.MLStudio.ListVersionDeploymentUpdates(ctx, orgID, derefStr(versionID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLVersionDeploymentUpdatesToModel(updates), nil
}

// MlRun returns generated.MlRunResolver implementation.
func (r *Resolver) MlRun() generated.MlRunResolver { return &mlRunResolver{r} }

type mlRunResolver struct{ *Resolver }
