package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// CreatedByActor is the resolver for the createdByActor field.
func (r *mlFindingResolver) CreatedByActor(ctx context.Context, obj *model.MlFinding) (*model.Actor, error) {
	if obj.CreatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.CreatedBy)
}

// CreateMlProject is the resolver for the createMlProject field.
func (r *mutationResolver) CreateMlProject(ctx context.Context, orgID string, input model.CreateMlProjectInput) (*model.MlProject, error) {
	p, err := r.MLStudio.CreateMLProject(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLProjectToModel(p), nil
}

// UpdateMlProject is the resolver for the updateMlProject field.
func (r *mutationResolver) UpdateMlProject(ctx context.Context, orgID string, id string, input model.UpdateMlProjectInput) (*model.MlProject, error) {
	p, err := r.MLStudio.UpdateMLProject(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLProjectToModel(p), nil
}

// DeleteMlProject is the resolver for the deleteMlProject field.
func (r *mutationResolver) DeleteMlProject(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLProject(ctx, orgID, id)
}

// CreateMlDeployment is the resolver for the createMlDeployment field.
func (r *mutationResolver) CreateMlDeployment(ctx context.Context, orgID string, input model.CreateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.CreateMLDeployment(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// UpdateMlDeployment is the resolver for the updateMlDeployment field.
func (r *mutationResolver) UpdateMlDeployment(ctx context.Context, orgID string, id string, input model.UpdateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.UpdateMLDeployment(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// DeleteMlDeployment is the resolver for the deleteMlDeployment field.
func (r *mutationResolver) DeleteMlDeployment(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLDeployment(ctx, orgID, id)
}

// CreateMlFinding is the resolver for the createMlFinding field.
func (r *mutationResolver) CreateMlFinding(ctx context.Context, orgID string, input model.CreateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.CreateMLFinding(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// UpdateMlFinding is the resolver for the updateMlFinding field.
func (r *mutationResolver) UpdateMlFinding(ctx context.Context, orgID string, id string, input model.UpdateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.UpdateMLFinding(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// DeleteMlFinding is the resolver for the deleteMlFinding field.
func (r *mutationResolver) DeleteMlFinding(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLFinding(ctx, orgID, id)
}

// CreateMlModel is the resolver for the createMlModel field.
func (r *mutationResolver) CreateMlModel(ctx context.Context, orgID string, input model.CreateMlModelInput) (*model.MlModel, error) {
	m, err := r.MLStudio.CreateMLModel(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// UpdateMlModel is the resolver for the updateMlModel field.
func (r *mutationResolver) UpdateMlModel(ctx context.Context, orgID string, id string, domain *string, problemType *string, license *string, references []string, intendedUse *string, limitations *string, considerations *string, recommendations *string) (*model.MlModel, error) {
	body := map[string]interface{}{
		"domain":          derefStr(domain),
		"problemType":     derefStr(problemType),
		"license":         derefStr(license),
		"references":      references,
		"intendedUse":     derefStr(intendedUse),
		"limitations":     derefStr(limitations),
		"considerations":  derefStr(considerations),
		"recommendations": derefStr(recommendations),
	}
	m, err := r.MLStudio.UpdateMLModel(ctx, orgID, id, body)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// UpdateMlModelInfo is the resolver for the updateMlModelInfo field.
func (r *mutationResolver) UpdateMlModelInfo(ctx context.Context, orgID string, id string, input model.UpdateMlModelInfoInput) (*model.MlModel, error) {
	body := convert.ToMap(input)
	// ToMap drops an empty tag list because of `omitempty`, which would make
	// clearing every tag a no-op instead of an update.
	if input.Tags != nil {
		body["tags"] = input.Tags
	}
	m, err := r.MLStudio.UpdateMLModelInfo(ctx, orgID, id, body)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// DeleteMlModel is the resolver for the deleteMlModel field.
func (r *mutationResolver) DeleteMlModel(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLModel(ctx, orgID, id)
}

// CreateMlVersionDeploymentUpdate is the resolver for the createMlVersionDeploymentUpdate field.
func (r *mutationResolver) CreateMlVersionDeploymentUpdate(ctx context.Context, orgID string, versionID string, toStatus string) (*model.MlVersionDeploymentUpdate, error) {
	update, err := r.MLStudio.CreateVersionDeploymentUpdate(ctx, orgID, versionID, map[string]interface{}{"toStatus": toStatus})
	if err != nil {
		return nil, err
	}
	return convert.MLVersionDeploymentUpdateToModel(update), nil
}

// SetMlModelVersionRun is the resolver for the setMlModelVersionRun field.
func (r *mutationResolver) SetMlModelVersionRun(ctx context.Context, orgID string, versionID string, runID *string) (*model.MlModelVersion, error) {
	v, err := r.MLStudio.SetMLModelVersionRun(ctx, orgID, versionID, map[string]interface{}{"runId": runID})
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionToModel(v), nil
}

// LinkMlVersionEvaluations is the resolver for the linkMlVersionEvaluations field.
func (r *mutationResolver) LinkMlVersionEvaluations(ctx context.Context, orgID string, versionID string, evaluationIds []string) ([]*model.MlEvaluation, error) {
	evals, err := r.MLStudio.LinkMLVersionEvaluations(ctx, orgID, versionID, map[string]interface{}{"evaluationIds": evaluationIds})
	if err != nil {
		return nil, err
	}
	return convert.MLEvaluationsToModel(evals), nil
}

// CreateMlExperiment is the resolver for the createMlExperiment field.
func (r *mutationResolver) CreateMlExperiment(ctx context.Context, orgID string, input model.CreateMlExperimentInput) (*model.MlExperiment, error) {
	e, err := r.MLStudio.CreateMLExperiment(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentToModel(e), nil
}

// UpdateMlExperiment is the resolver for the updateMlExperiment field.
func (r *mutationResolver) UpdateMlExperiment(ctx context.Context, orgID string, id string, input model.UpdateMlExperimentInput) (*model.MlExperiment, error) {
	body := convert.ToMap(input)
	// ToMap drops an empty tag list because of `omitempty`, which would make
	// clearing every tag a no-op instead of an update.
	if input.Tags != nil {
		body["tags"] = input.Tags
	}
	e, err := r.MLStudio.UpdateMLExperiment(ctx, orgID, id, body)
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentToModel(e), nil
}

// DeleteMlExperiment is the resolver for the deleteMlExperiment field.
func (r *mutationResolver) DeleteMlExperiment(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLExperiment(ctx, orgID, id)
}

// CreateMlRun is the resolver for the createMlRun field.
func (r *mutationResolver) CreateMlRun(ctx context.Context, orgID string, experimentID string, input model.CreateMlRunInput) (*model.MlRun, error) {
	run, err := r.MLStudio.CreateMLRun(ctx, orgID, experimentID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLRunToModel(run), nil
}

// UpdateMlRun is the resolver for the updateMlRun field.
func (r *mutationResolver) UpdateMlRun(ctx context.Context, orgID string, id string, input model.UpdateMlRunInput) (*model.MlRun, error) {
	run, err := r.MLStudio.UpdateMLRun(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLRunToModel(run), nil
}

// DeleteMlRun is the resolver for the deleteMlRun field.
func (r *mutationResolver) DeleteMlRun(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLRun(ctx, orgID, id)
}

// CreateMlDataset is the resolver for the createMlDataset field.
func (r *mutationResolver) CreateMlDataset(ctx context.Context, orgID string, experimentID string, input model.CreateMlDatasetInput) (*model.MlDataset, error) {
	ds, err := r.MLStudio.CreateMLDataset(ctx, orgID, experimentID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetToModel(ds), nil
}

// UpdateMlDataset is the resolver for the updateMlDataset field.
func (r *mutationResolver) UpdateMlDataset(ctx context.Context, orgID string, id string, input model.UpdateMlDatasetInput) (*model.MlDataset, error) {
	ds, err := r.MLStudio.UpdateMLDataset(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetToModel(ds), nil
}

// DeleteMlDataset is the resolver for the deleteMlDataset field.
func (r *mutationResolver) DeleteMlDataset(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLDataset(ctx, orgID, id)
}

// MlProjects is the resolver for the mlProjects field.
func (r *queryResolver) MlProjects(ctx context.Context, orgID string) ([]*model.MlProject, error) {
	projects, err := r.MLStudio.ListMLProjects(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.MLProjectsToModel(projects), nil
}

// MlProject is the resolver for the mlProject field.
func (r *queryResolver) MlProject(ctx context.Context, orgID string, id string) (*model.MlProject, error) {
	p, err := r.MLStudio.GetMLProject(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLProjectToModel(p), nil
}

// MlModels is the resolver for the mlModels field.
func (r *queryResolver) MlModels(ctx context.Context, orgID string, projectID *string) ([]*model.MlModel, error) {
	models, err := r.MLStudio.ListMLModels(ctx, orgID, derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLModelsToModel(models), nil
}

// MlModel is the resolver for the mlModel field.
func (r *queryResolver) MlModel(ctx context.Context, orgID string, id string) (*model.MlModel, error) {
	m, err := r.MLStudio.GetMLModel(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// MlModelVersions is the resolver for the mlModelVersions field.
func (r *queryResolver) MlModelVersions(ctx context.Context, orgID string, modelID *string, projectID *string) ([]*model.MlModelVersion, error) {
	versions, err := r.MLStudio.ListMLModelVersions(ctx, orgID, derefStr(modelID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionsToModel(versions), nil
}

// MlModelVersion is the resolver for the mlModelVersion field.
func (r *queryResolver) MlModelVersion(ctx context.Context, orgID string, id string) (*model.MlModelVersion, error) {
	v, err := r.MLStudio.GetMLModelVersion(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionToModel(v), nil
}

// MlExperiments is the resolver for the mlExperiments field.
func (r *queryResolver) MlExperiments(ctx context.Context, orgID string, projectID *string) ([]*model.MlExperiment, error) {
	experiments, err := r.MLStudio.ListMLExperiments(ctx, orgID, derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentsToModel(experiments), nil
}

// MlExperiment is the resolver for the mlExperiment field.
func (r *queryResolver) MlExperiment(ctx context.Context, orgID string, id string) (*model.MlExperiment, error) {
	e, err := r.MLStudio.GetMLExperiment(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentToModel(e), nil
}

// MlRuns is the resolver for the mlRuns field.
func (r *queryResolver) MlRuns(ctx context.Context, orgID string, experimentID *string, projectID *string) ([]*model.MlRun, error) {
	runs, _, err := r.MLStudio.ListMLRuns(ctx, orgID, uigraphapi.MLRunQuery{
		ExperimentID: derefStr(experimentID),
		ProjectID:    derefStr(projectID),
	})
	if err != nil {
		return nil, err
	}
	return convert.MLRunsToModel(runs), nil
}

// MlRunsPage is the resolver for the mlRunsPage field.
func (r *queryResolver) MlRunsPage(ctx context.Context, orgID string, experimentID *string, projectID *string, search *string, limit *int, offset *int) (*model.MlRunPage, error) {
	query := uigraphapi.MLRunQuery{
		ExperimentID: derefStr(experimentID),
		ProjectID:    derefStr(projectID),
		Search:       derefStr(search),
	}
	if limit != nil {
		query.Limit = *limit
	}
	if offset != nil {
		query.Offset = *offset
	}
	runs, total, err := r.MLStudio.ListMLRuns(ctx, orgID, query)
	if err != nil {
		return nil, err
	}
	return &model.MlRunPage{
		Runs:  convert.MLRunsToModel(runs),
		Total: total,
	}, nil
}

// MlRun is the resolver for the mlRun field.
func (r *queryResolver) MlRun(ctx context.Context, orgID string, id string) (*model.MlRun, error) {
	run, err := r.MLStudio.GetMLRun(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLRunToModel(run), nil
}

// MlArtifacts is the resolver for the mlArtifacts field.
func (r *queryResolver) MlArtifacts(ctx context.Context, orgID string, runID *string) ([]*model.MlArtifact, error) {
	artifacts, err := r.MLStudio.ListMLArtifacts(ctx, orgID, derefStr(runID))
	if err != nil {
		return nil, err
	}
	return convert.MLArtifactsToModel(artifacts), nil
}

// MlDatasets is the resolver for the mlDatasets field.
func (r *queryResolver) MlDatasets(ctx context.Context, orgID string, experimentID *string) ([]*model.MlDataset, error) {
	datasets, err := r.MLStudio.ListMLDatasets(ctx, orgID, derefStr(experimentID))
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetsToModel(datasets), nil
}

// MlDataset is the resolver for the mlDataset field.
func (r *queryResolver) MlDataset(ctx context.Context, orgID string, id string) (*model.MlDataset, error) {
	ds, err := r.MLStudio.GetMLDataset(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetToModel(ds), nil
}

// MlDeployments is the resolver for the mlDeployments field.
func (r *queryResolver) MlDeployments(ctx context.Context, orgID string, modelID *string, versionID *string) ([]*model.MlDeployment, error) {
	deployments, err := r.MLStudio.ListMLDeployments(ctx, orgID, derefStr(modelID), derefStr(versionID))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentsToModel(deployments), nil
}

// MlFindings is the resolver for the mlFindings field.
func (r *queryResolver) MlFindings(ctx context.Context, orgID string, modelID *string, projectID *string) ([]*model.MlFinding, error) {
	findings, err := r.MLStudio.ListMLFindings(ctx, orgID, derefStr(modelID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingsToModel(findings), nil
}

// MlVersionDeploymentUpdates is the resolver for the mlVersionDeploymentUpdates field.
func (r *queryResolver) MlVersionDeploymentUpdates(ctx context.Context, orgID string, versionID *string, projectID *string) ([]*model.MlVersionDeploymentUpdate, error) {
	updates, err := r.MLStudio.ListVersionDeploymentUpdates(ctx, orgID, derefStr(versionID), derefStr(projectID))
	if err != nil {
		return nil, err
	}
	return convert.MLVersionDeploymentUpdatesToModel(updates), nil
}

// MlVersionEvaluations is the resolver for the mlVersionEvaluations field.
func (r *queryResolver) MlVersionEvaluations(ctx context.Context, orgID string, versionID string) ([]*model.MlEvaluation, error) {
	evaluations, _, err := r.MLStudio.ListMLVersionEvaluations(ctx, orgID, versionID, uigraphapi.MLEvaluationQuery{})
	if err != nil {
		return nil, err
	}
	return convert.MLEvaluationsToModel(evaluations), nil
}

// MlExperimentEvaluations is the resolver for the mlExperimentEvaluations field.
func (r *queryResolver) MlExperimentEvaluations(ctx context.Context, orgID string, experimentID string) ([]*model.MlEvaluation, error) {
	evaluations, _, err := r.MLStudio.ListMLExperimentEvaluations(ctx, orgID, experimentID, uigraphapi.MLEvaluationQuery{})
	if err != nil {
		return nil, err
	}
	return convert.MLEvaluationsToModel(evaluations), nil
}

// MlVersionEvaluationsPage is the resolver for the mlVersionEvaluationsPage field.
func (r *queryResolver) MlVersionEvaluationsPage(ctx context.Context, orgID string, versionID string, search *string, limit *int, offset *int) (*model.MlEvaluationPage, error) {
	query := uigraphapi.MLEvaluationQuery{Search: derefStr(search)}
	if limit != nil {
		query.Limit = *limit
	}
	if offset != nil {
		query.Offset = *offset
	}
	evaluations, total, err := r.MLStudio.ListMLVersionEvaluations(ctx, orgID, versionID, query)
	if err != nil {
		return nil, err
	}
	return &model.MlEvaluationPage{
		Evaluations: convert.MLEvaluationsToModel(evaluations),
		Total:       total,
	}, nil
}

// MlExperimentEvaluationsPage is the resolver for the mlExperimentEvaluationsPage field.
func (r *queryResolver) MlExperimentEvaluationsPage(ctx context.Context, orgID string, experimentID string, search *string, limit *int, offset *int) (*model.MlEvaluationPage, error) {
	query := uigraphapi.MLEvaluationQuery{Search: derefStr(search)}
	if limit != nil {
		query.Limit = *limit
	}
	if offset != nil {
		query.Offset = *offset
	}
	evaluations, total, err := r.MLStudio.ListMLExperimentEvaluations(ctx, orgID, experimentID, query)
	if err != nil {
		return nil, err
	}
	return &model.MlEvaluationPage{
		Evaluations: convert.MLEvaluationsToModel(evaluations),
		Total:       total,
	}, nil
}

// MlEvaluation is the resolver for the mlEvaluation field.
func (r *queryResolver) MlEvaluation(ctx context.Context, orgID string, id string) (*model.MlEvaluation, error) {
	evaluation, err := r.MLStudio.GetMLEvaluation(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLEvaluationToModel(evaluation), nil
}

// MlFinding returns generated.MlFindingResolver implementation.
func (r *Resolver) MlFinding() generated.MlFindingResolver { return &mlFindingResolver{r} }

type mlFindingResolver struct{ *Resolver }
