package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// Series is the resolver for the series field.
func (r *mlRunResolver) Series(ctx context.Context, obj *model.MlRun) (any, error) {
	points, err := r.MLStudio.ListMLRunSeries(ctx, obj.OrgID, obj.ID)
	if err != nil {
		return nil, err
	}
	return convert.MLRunSeriesToJSON(points), nil
}

// CreateMlDeployment is the resolver for the createMlDeployment field.
func (r *mutationResolver) CreateMlDeployment(ctx context.Context, orgID string, input model.CreateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.CreateMLDeployment(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// UpdateMlDeployment is the resolver for the updateMlDeployment field.
func (r *mutationResolver) UpdateMlDeployment(ctx context.Context, orgID string, id string, input model.UpdateMlDeploymentInput) (*model.MlDeployment, error) {
	d, err := r.MLStudio.UpdateMLDeployment(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentToModel(d), nil
}

// DeleteMlDeployment is the resolver for the deleteMlDeployment field.
func (r *mutationResolver) DeleteMlDeployment(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLDeployment(ctx, orgID, id)
}

// CreateMlFinding is the resolver for the createMlFinding field.
func (r *mutationResolver) CreateMlFinding(ctx context.Context, orgID string, input model.CreateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.CreateMLFinding(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// UpdateMlFinding is the resolver for the updateMlFinding field.
func (r *mutationResolver) UpdateMlFinding(ctx context.Context, orgID string, id string, input model.UpdateMlFindingInput) (*model.MlFinding, error) {
	f, err := r.MLStudio.UpdateMLFinding(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingToModel(f), nil
}

// DeleteMlFinding is the resolver for the deleteMlFinding field.
func (r *mutationResolver) DeleteMlFinding(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.MLStudio.DeleteMLFinding(ctx, orgID, id)
}

// UpdateMlModel is the resolver for the updateMlModel field.
func (r *mutationResolver) UpdateMlModel(ctx context.Context, orgID string, id string, domain *string, problemType *string) (*model.MlModel, error) {
	body := map[string]interface{}{
		"domain":      derefStr(domain),
		"problemType": derefStr(problemType),
	}
	m, err := r.MLStudio.UpdateMLModel(ctx, orgID, id, body)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// MlModels is the resolver for the mlModels field.
func (r *queryResolver) MlModels(ctx context.Context, orgID string) ([]*model.MlModel, error) {
	models, err := r.MLStudio.ListMLModels(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.MLModelsToModel(models), nil
}

// MlModel is the resolver for the mlModel field.
func (r *queryResolver) MlModel(ctx context.Context, orgID string, id string) (*model.MlModel, error) {
	m, err := r.MLStudio.GetMLModel(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelToModel(m), nil
}

// MlModelVersions is the resolver for the mlModelVersions field.
func (r *queryResolver) MlModelVersions(ctx context.Context, orgID string, modelID *string) ([]*model.MlModelVersion, error) {
	versions, err := r.MLStudio.ListMLModelVersions(ctx, orgID, derefStr(modelID))
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionsToModel(versions), nil
}

// MlModelVersion is the resolver for the mlModelVersion field.
func (r *queryResolver) MlModelVersion(ctx context.Context, orgID string, id string) (*model.MlModelVersion, error) {
	v, err := r.MLStudio.GetMLModelVersion(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLModelVersionToModel(v), nil
}

// MlExperiments is the resolver for the mlExperiments field.
func (r *queryResolver) MlExperiments(ctx context.Context, orgID string) ([]*model.MlExperiment, error) {
	experiments, err := r.MLStudio.ListMLExperiments(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentsToModel(experiments), nil
}

// MlExperiment is the resolver for the mlExperiment field.
func (r *queryResolver) MlExperiment(ctx context.Context, orgID string, id string) (*model.MlExperiment, error) {
	e, err := r.MLStudio.GetMLExperiment(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLExperimentToModel(e), nil
}

// MlRuns is the resolver for the mlRuns field.
func (r *queryResolver) MlRuns(ctx context.Context, orgID string, experimentID *string) ([]*model.MlRun, error) {
	runs, err := r.MLStudio.ListMLRuns(ctx, orgID, derefStr(experimentID))
	if err != nil {
		return nil, err
	}
	return convert.MLRunsToModel(runs), nil
}

// MlRun is the resolver for the mlRun field.
func (r *queryResolver) MlRun(ctx context.Context, orgID string, id string) (*model.MlRun, error) {
	run, err := r.MLStudio.GetMLRun(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLRunToModel(run), nil
}

// MlArtifacts is the resolver for the mlArtifacts field.
func (r *queryResolver) MlArtifacts(ctx context.Context, orgID string, runID *string) ([]*model.MlArtifact, error) {
	artifacts, err := r.MLStudio.ListMLArtifacts(ctx, orgID, derefStr(runID))
	if err != nil {
		return nil, err
	}
	return convert.MLArtifactsToModel(artifacts), nil
}

// MlDatasets is the resolver for the mlDatasets field.
func (r *queryResolver) MlDatasets(ctx context.Context, orgID string) ([]*model.MlDataset, error) {
	datasets, err := r.MLStudio.ListMLDatasets(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetsToModel(datasets), nil
}

// MlDataset is the resolver for the mlDataset field.
func (r *queryResolver) MlDataset(ctx context.Context, orgID string, id string) (*model.MlDataset, error) {
	ds, err := r.MLStudio.GetMLDataset(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.MLDatasetToModel(ds), nil
}

// MlEvaluationDatasets is the resolver for the mlEvaluationDatasets field.
func (r *queryResolver) MlEvaluationDatasets(ctx context.Context, orgID string, experimentID *string) ([]*model.MlEvaluationDataset, error) {
	datasets, err := r.MLStudio.ListMLEvaluationDatasets(ctx, orgID, derefStr(experimentID))
	if err != nil {
		return nil, err
	}
	return convert.MLEvaluationDatasetsToModel(datasets), nil
}

// MlDeployments is the resolver for the mlDeployments field.
func (r *queryResolver) MlDeployments(ctx context.Context, orgID string, modelID *string, versionID *string) ([]*model.MlDeployment, error) {
	deployments, err := r.MLStudio.ListMLDeployments(ctx, orgID, derefStr(modelID), derefStr(versionID))
	if err != nil {
		return nil, err
	}
	return convert.MLDeploymentsToModel(deployments), nil
}

// MlFindings is the resolver for the mlFindings field.
func (r *queryResolver) MlFindings(ctx context.Context, orgID string, modelID *string) ([]*model.MlFinding, error) {
	findings, err := r.MLStudio.ListMLFindings(ctx, orgID, derefStr(modelID))
	if err != nil {
		return nil, err
	}
	return convert.MLFindingsToModel(findings), nil
}

// MlRun returns generated.MlRunResolver implementation.
func (r *Resolver) MlRun() generated.MlRunResolver { return &mlRunResolver{r} }

type mlRunResolver struct{ *Resolver }
