package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateOrg is the resolver for the createOrg field.
func (r *mutationResolver) CreateOrg(ctx context.Context, input model.CreateOrgInput) (*model.Org, error) {
	o, err := r.Client.CreateOrg(ctx, toMap(input))
	if err != nil {
		return nil, err
	}
	return orgToModel(o), nil
}

// UpdateOrg is the resolver for the updateOrg field.
func (r *mutationResolver) UpdateOrg(ctx context.Context, id string, input model.UpdateOrgInput) (*model.Org, error) {
	o, err := r.Client.UpdateOrg(ctx, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return orgToModel(o), nil
}

// DeleteOrg is the resolver for the deleteOrg field.
func (r *mutationResolver) DeleteOrg(ctx context.Context, id string) (bool, error) {
	return true, r.Client.DeleteOrg(ctx, id)
}

// AddMember is the resolver for the addMember field.
func (r *mutationResolver) AddMember(ctx context.Context, orgID string, input model.AddMemberInput) (*model.Member, error) {
	m, err := r.Client.AddMember(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return memberToModel(*m), nil
}

// UpdateMemberRole is the resolver for the updateMemberRole field.
func (r *mutationResolver) UpdateMemberRole(ctx context.Context, orgID string, userID string, role string) (*model.Member, error) {
	m, err := r.Client.UpdateMemberRole(ctx, orgID, userID, map[string]interface{}{"role": role})
	if err != nil {
		return nil, err
	}
	return memberToModel(*m), nil
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, orgID string, userID string) (bool, error) {
	return true, r.Client.RemoveMember(ctx, orgID, userID)
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, orgID string, input model.CreateTeamInput) (*model.Team, error) {
	t, err := r.Client.CreateTeam(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return teamToModel(t), nil
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, orgID string, teamID string, input model.UpdateTeamInput) (*model.Team, error) {
	t, err := r.Client.UpdateTeam(ctx, orgID, teamID, toMap(input))
	if err != nil {
		return nil, err
	}
	return teamToModel(t), nil
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, orgID string, teamID string) (bool, error) {
	return true, r.Client.DeleteTeam(ctx, orgID, teamID)
}

// AddTeamMember is the resolver for the addTeamMember field.
func (r *mutationResolver) AddTeamMember(ctx context.Context, orgID string, teamID string, userID string, permission *string) (bool, error) {
	body := map[string]interface{}{"userId": userID}
	if permission != nil {
		body["permission"] = *permission
	}
	return true, r.Client.AddTeamMember(ctx, orgID, teamID, body)
}

// RemoveTeamMember is the resolver for the removeTeamMember field.
func (r *mutationResolver) RemoveTeamMember(ctx context.Context, orgID string, teamID string, userID string) (bool, error) {
	return true, r.Client.RemoveTeamMember(ctx, orgID, teamID, userID)
}

// CreateInvitation is the resolver for the createInvitation field.
func (r *mutationResolver) CreateInvitation(ctx context.Context, orgID string, input model.CreateInvitationInput) (*model.Invitation, error) {
	inv, err := r.Client.CreateInvitation(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return invitationToModel(*inv), nil
}

// RevokeInvitation is the resolver for the revokeInvitation field.
func (r *mutationResolver) RevokeInvitation(ctx context.Context, orgID string, invitationID string) (bool, error) {
	return true, r.Client.RevokeInvitation(ctx, orgID, invitationID)
}

// CreateServiceAccount is the resolver for the createServiceAccount field.
func (r *mutationResolver) CreateServiceAccount(ctx context.Context, orgID string, input model.CreateServiceAccountInput) (*model.ServiceAccount, error) {
	sa, err := r.Client.CreateServiceAccount(ctx, orgID, toMap(input))
	if err != nil {
		return nil, err
	}
	return serviceAccountToModel(*sa), nil
}

// UpdateServiceAccount is the resolver for the updateServiceAccount field.
func (r *mutationResolver) UpdateServiceAccount(ctx context.Context, orgID string, id string, input model.UpdateServiceAccountInput) (*model.ServiceAccount, error) {
	sa, err := r.Client.UpdateServiceAccount(ctx, orgID, id, toMap(input))
	if err != nil {
		return nil, err
	}
	return serviceAccountToModel(*sa), nil
}

// DeleteServiceAccount is the resolver for the deleteServiceAccount field.
func (r *mutationResolver) DeleteServiceAccount(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.Client.DeleteServiceAccount(ctx, orgID, id)
}

// CreateServiceAccountToken is the resolver for the createServiceAccountToken field.
func (r *mutationResolver) CreateServiceAccountToken(ctx context.Context, orgID string, saID string, input model.CreateTokenInput) (*model.CreatedToken, error) {
	t, err := r.Client.CreateServiceAccountToken(ctx, orgID, saID, toMap(input))
	if err != nil {
		return nil, err
	}
	return createdTokenToModel(t), nil
}

// RevokeServiceAccountToken is the resolver for the revokeServiceAccountToken field.
func (r *mutationResolver) RevokeServiceAccountToken(ctx context.Context, orgID string, saID string, tokenID string) (bool, error) {
	return true, r.Client.RevokeServiceAccountToken(ctx, orgID, saID, tokenID)
}

// Org is the resolver for the org field.
func (r *queryResolver) Org(ctx context.Context, id string) (*model.Org, error) {
	o, err := r.Client.GetOrg(ctx, id)
	if err != nil {
		return nil, err
	}
	return orgToModel(o), nil
}

// Orgs is the resolver for the orgs field.
func (r *queryResolver) Orgs(ctx context.Context) ([]*model.Org, error) {
	orgs, err := r.Client.ListOrgs(ctx)
	if err != nil {
		return nil, err
	}
	return orgsToModel(orgs), nil
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context, orgID string) ([]*model.Member, error) {
	members, err := r.Client.ListMembers(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return membersToModel(members), nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, orgID string) ([]*model.Team, error) {
	teams, err := r.Client.ListTeams(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return teamsToModel(teams), nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, orgID string, teamID string) (*model.Team, error) {
	t, err := r.Client.GetTeam(ctx, orgID, teamID)
	if err != nil {
		return nil, err
	}
	return teamToModel(t), nil
}

// TeamMembers is the resolver for the teamMembers field.
func (r *queryResolver) TeamMembers(ctx context.Context, orgID string, teamID string) ([]*model.TeamMember, error) {
	members, err := r.Client.ListTeamMembers(ctx, orgID, teamID)
	if err != nil {
		return nil, err
	}
	return teamMembersToModel(members), nil
}

// Invitations is the resolver for the invitations field.
func (r *queryResolver) Invitations(ctx context.Context, orgID string) ([]*model.Invitation, error) {
	invs, err := r.Client.ListInvitations(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return invitationsToModel(invs), nil
}

// ServiceAccounts is the resolver for the serviceAccounts field.
func (r *queryResolver) ServiceAccounts(ctx context.Context, orgID string) ([]*model.ServiceAccount, error) {
	sas, err := r.Client.ListServiceAccounts(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return serviceAccountsToModel(sas), nil
}

// ServiceAccount is the resolver for the serviceAccount field.
func (r *queryResolver) ServiceAccount(ctx context.Context, orgID string, id string) (*model.ServiceAccount, error) {
	sa, err := r.Client.GetServiceAccount(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return serviceAccountToModel(*sa), nil
}

// ServiceAccountTokens is the resolver for the serviceAccountTokens field.
func (r *queryResolver) ServiceAccountTokens(ctx context.Context, orgID string, saID string) ([]*model.ServiceAccountToken, error) {
	tokens, err := r.Client.ListServiceAccountTokens(ctx, orgID, saID)
	if err != nil {
		return nil, err
	}
	return saTokensToModel(tokens), nil
}
