package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/model"
	"github.com/uigraph/graphql/internal/uigraphapi"
)

// CreateOrg is the resolver for the createOrg field.
func (r *mutationResolver) CreateOrg(ctx context.Context, input model.CreateOrgInput) (*model.Org, error) {
	o, err := r.OrgAPI.CreateOrg(ctx, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.OrgToModel(o), nil
}

// UpdateOrg is the resolver for the updateOrg field.
func (r *mutationResolver) UpdateOrg(ctx context.Context, id string, input model.UpdateOrgInput) (*model.Org, error) {
	o, err := r.OrgAPI.UpdateOrg(ctx, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.OrgToModel(o), nil
}

// DeleteOrg is the resolver for the deleteOrg field.
func (r *mutationResolver) DeleteOrg(ctx context.Context, id string) (bool, error) {
	return true, r.OrgAPI.DeleteOrg(ctx, id)
}

// CompleteOnboarding is the resolver for the completeOnboarding field.
func (r *mutationResolver) CompleteOnboarding(ctx context.Context, orgID string) (bool, error) {
	return true, r.OrgAPI.CompleteOnboarding(ctx, orgID)
}

// AddMember is the resolver for the addMember field.
func (r *mutationResolver) AddMember(ctx context.Context, orgID string, input model.AddMemberInput) (*model.Member, error) {
	m, err := r.OrgAPI.AddMember(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MemberToModel(*m), nil
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, orgID string, userID string, input model.UpdateMemberInput) (*model.Member, error) {
	m, err := r.OrgAPI.UpdateMember(ctx, orgID, userID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.MemberToModel(*m), nil
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, orgID string, userID string) (bool, error) {
	return true, r.OrgAPI.RemoveMember(ctx, orgID, userID)
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, orgID string, input model.CreateTeamInput) (*model.Team, error) {
	t, err := r.OrgAPI.CreateTeam(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.TeamToModel(t), nil
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, orgID string, teamID string, input model.UpdateTeamInput) (*model.Team, error) {
	t, err := r.OrgAPI.UpdateTeam(ctx, orgID, teamID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.TeamToModel(t), nil
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, orgID string, teamID string) (bool, error) {
	return true, r.OrgAPI.DeleteTeam(ctx, orgID, teamID)
}

// AddTeamMember is the resolver for the addTeamMember field.
func (r *mutationResolver) AddTeamMember(ctx context.Context, orgID string, teamID string, userID string, permission *string) (bool, error) {
	body := map[string]interface{}{"userId": userID}
	if permission != nil {
		body["permission"] = *permission
	}
	return true, r.OrgAPI.AddTeamMember(ctx, orgID, teamID, body)
}

// RemoveTeamMember is the resolver for the removeTeamMember field.
func (r *mutationResolver) RemoveTeamMember(ctx context.Context, orgID string, teamID string, userID string) (bool, error) {
	return true, r.OrgAPI.RemoveTeamMember(ctx, orgID, teamID, userID)
}

// CreateServiceAccount is the resolver for the createServiceAccount field.
func (r *mutationResolver) CreateServiceAccount(ctx context.Context, orgID string, input model.CreateServiceAccountInput) (*model.ServiceAccount, error) {
	sa, err := r.OrgAPI.CreateServiceAccount(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceAccountToModel(*sa), nil
}

// UpdateServiceAccount is the resolver for the updateServiceAccount field.
func (r *mutationResolver) UpdateServiceAccount(ctx context.Context, orgID string, id string, input model.UpdateServiceAccountInput) (*model.ServiceAccount, error) {
	sa, err := r.OrgAPI.UpdateServiceAccount(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.ServiceAccountToModel(*sa), nil
}

// DeleteServiceAccount is the resolver for the deleteServiceAccount field.
func (r *mutationResolver) DeleteServiceAccount(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.OrgAPI.DeleteServiceAccount(ctx, orgID, id)
}

// CreateServiceAccountToken is the resolver for the createServiceAccountToken field.
func (r *mutationResolver) CreateServiceAccountToken(ctx context.Context, orgID string, saID string, input model.CreateTokenInput) (*model.CreatedToken, error) {
	t, err := r.OrgAPI.CreateServiceAccountToken(ctx, orgID, saID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.CreatedTokenToModel(t), nil
}

// RevokeServiceAccountToken is the resolver for the revokeServiceAccountToken field.
func (r *mutationResolver) RevokeServiceAccountToken(ctx context.Context, orgID string, saID string, tokenID string) (bool, error) {
	return true, r.OrgAPI.RevokeServiceAccountToken(ctx, orgID, saID, tokenID)
}

// PrepareServiceAccountAvatarUpload is the resolver for the prepareServiceAccountAvatarUpload field.
func (r *mutationResolver) PrepareServiceAccountAvatarUpload(ctx context.Context, orgID string, saID string) (*model.AssetUpload, error) {
	u, err := r.OrgAPI.PrepareServiceAccountAvatarUpload(ctx, orgID, saID)
	if err != nil {
		return nil, err
	}
	return &model.AssetUpload{AssetID: u.AssetID, UploadURL: u.UploadURL}, nil
}

// SetServiceAccountAvatar is the resolver for the setServiceAccountAvatar field.
func (r *mutationResolver) SetServiceAccountAvatar(ctx context.Context, orgID string, saID string) (bool, error) {
	return true, r.OrgAPI.SetServiceAccountAvatar(ctx, orgID, saID)
}

// Org is the resolver for the org field.
func (r *queryResolver) Org(ctx context.Context, id string) (*model.Org, error) {
	o, err := r.OrgAPI.GetOrg(ctx, id)
	if err != nil {
		return nil, err
	}
	return convert.OrgToModel(o), nil
}

// Orgs is the resolver for the orgs field.
func (r *queryResolver) Orgs(ctx context.Context) ([]*model.Org, error) {
	orgs, err := r.OrgAPI.ListOrgs(ctx)
	if err != nil {
		return nil, err
	}
	return convert.OrgsToModel(orgs), nil
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context, orgID string) ([]*model.Member, error) {
	members, err := r.OrgAPI.ListMembers(ctx, orgID)
	if err != nil {
		return nil, err
	}

	ids := make([]string, len(members))
	for i, m := range members {
		ids[i] = m.UserID
	}

	actors := map[string]*uigraphapi.Actor{}
	if len(ids) > 0 {
		actors, err = r.Resolver.Actor.ResolveActors(ctx, orgID, ids)
		if err != nil {
			return nil, err
		}
	}
	return convert.MembersToModel(members, actors), nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, orgID string) ([]*model.Team, error) {
	teams, err := r.OrgAPI.ListTeams(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.TeamsToModel(teams), nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, orgID string, teamID string) (*model.Team, error) {
	t, err := r.OrgAPI.GetTeam(ctx, orgID, teamID)
	if err != nil {
		return nil, err
	}
	return convert.TeamToModel(t), nil
}

// TeamMembers is the resolver for the teamMembers field.
func (r *queryResolver) TeamMembers(ctx context.Context, orgID string, teamID string) ([]*model.TeamMember, error) {
	members, err := r.OrgAPI.ListTeamMembers(ctx, orgID, teamID)
	if err != nil {
		return nil, err
	}
	return convert.TeamMembersToModel(members), nil
}

// ServiceAccounts is the resolver for the serviceAccounts field.
func (r *queryResolver) ServiceAccounts(ctx context.Context, orgID string) ([]*model.ServiceAccount, error) {
	sas, err := r.OrgAPI.ListServiceAccounts(ctx, orgID)
	if err != nil {
		return nil, err
	}
	return convert.ServiceAccountsToModel(sas), nil
}

// ServiceAccount is the resolver for the serviceAccount field.
func (r *queryResolver) ServiceAccount(ctx context.Context, orgID string, id string) (*model.ServiceAccount, error) {
	sa, err := r.OrgAPI.GetServiceAccount(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.ServiceAccountToModel(*sa), nil
}

// ServiceAccountTokens is the resolver for the serviceAccountTokens field.
func (r *queryResolver) ServiceAccountTokens(ctx context.Context, orgID string, saID string) ([]*model.ServiceAccountToken, error) {
	tokens, err := r.OrgAPI.ListServiceAccountTokens(ctx, orgID, saID)
	if err != nil {
		return nil, err
	}
	return convert.SATokensToModel(tokens), nil
}

// ServiceAccountScopes is the resolver for the serviceAccountScopes field.
func (r *queryResolver) ServiceAccountScopes(ctx context.Context, orgID string) ([]string, error) {
	return r.OrgAPI.ListServiceAccountScopes(ctx, orgID)
}
