package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"strings"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateSavedQueryFolder is the resolver for the createSavedQueryFolder field.
func (r *mutationResolver) CreateSavedQueryFolder(ctx context.Context, orgID string, serviceID string, serviceDbID string, input model.CreateSavedQueryFolderInput) (*model.SavedQueryFolder, error) {
	body := convert.ToMap(input)
	body["scope"] = strings.ToLower(input.Scope.String())
	f, err := r.Catalog.CreateSavedQueryFolder(ctx, orgID, serviceID, serviceDbID, body)
	if err != nil {
		return nil, err
	}
	return convert.SavedQueryFolderToModel(f), nil
}

// DeleteSavedQueryFolder is the resolver for the deleteSavedQueryFolder field.
func (r *mutationResolver) DeleteSavedQueryFolder(ctx context.Context, orgID string, serviceID string, serviceDbID string, id string) (bool, error) {
	return true, r.Catalog.DeleteSavedQueryFolder(ctx, orgID, serviceID, serviceDbID, id)
}

// CreateSavedQuery is the resolver for the createSavedQuery field.
func (r *mutationResolver) CreateSavedQuery(ctx context.Context, orgID string, serviceID string, serviceDbID string, input model.CreateSavedQueryInput) (*model.SavedQuery, error) {
	body := convert.ToMap(input)
	body["scope"] = strings.ToLower(input.Scope.String())
	q, err := r.Catalog.CreateSavedQuery(ctx, orgID, serviceID, serviceDbID, body)
	if err != nil {
		return nil, err
	}
	return convert.SavedQueryToModel(q), nil
}

// UpdateSavedQuery is the resolver for the updateSavedQuery field.
func (r *mutationResolver) UpdateSavedQuery(ctx context.Context, orgID string, serviceID string, serviceDbID string, id string, input model.UpdateSavedQueryInput) (*model.SavedQuery, error) {
	q, err := r.Catalog.UpdateSavedQuery(ctx, orgID, serviceID, serviceDbID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.SavedQueryToModel(q), nil
}

// DeleteSavedQuery is the resolver for the deleteSavedQuery field.
func (r *mutationResolver) DeleteSavedQuery(ctx context.Context, orgID string, serviceID string, serviceDbID string, id string) (bool, error) {
	return true, r.Catalog.DeleteSavedQuery(ctx, orgID, serviceID, serviceDbID, id)
}

// SavedQueryFolders is the resolver for the savedQueryFolders field.
func (r *queryResolver) SavedQueryFolders(ctx context.Context, orgID string, serviceID string, serviceDbID string, scope model.SavedQueryScope) ([]*model.SavedQueryFolder, error) {
	folders, err := r.Catalog.ListSavedQueryFolders(ctx, orgID, serviceID, serviceDbID, strings.ToLower(scope.String()))
	if err != nil {
		return nil, err
	}
	return convert.SavedQueryFoldersToModel(folders), nil
}

// SavedQueries is the resolver for the savedQueries field.
func (r *queryResolver) SavedQueries(ctx context.Context, orgID string, serviceID string, serviceDbID string, scope model.SavedQueryScope) ([]*model.SavedQuery, error) {
	queries, err := r.Catalog.ListSavedQueries(ctx, orgID, serviceID, serviceDbID, strings.ToLower(scope.String()))
	if err != nil {
		return nil, err
	}
	return convert.SavedQueriesToModel(queries), nil
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *savedQueryResolver) CreatedByActor(ctx context.Context, obj *model.SavedQuery) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *savedQueryResolver) UpdatedByActor(ctx context.Context, obj *model.SavedQuery) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// SavedQuery returns generated.SavedQueryResolver implementation.
func (r *Resolver) SavedQuery() generated.SavedQueryResolver { return &savedQueryResolver{r} }

type savedQueryResolver struct{ *Resolver }
