package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// CreateTimelineEvent is the resolver for the createTimelineEvent field.
func (r *mutationResolver) CreateTimelineEvent(ctx context.Context, orgID string, serviceID string, input model.CreateTimelineEventInput) (*model.TimelineEvent, error) {
	event, err := r.Timeline.CreateTimelineEvent(ctx, orgID, serviceID, convert.CreateTimelineEventInputToBody(input))
	if err != nil {
		return nil, err
	}
	return convert.TimelineEventToModel(event), nil
}

// UpdateTimelineEvent is the resolver for the updateTimelineEvent field.
func (r *mutationResolver) UpdateTimelineEvent(ctx context.Context, orgID string, serviceID string, eventID string, input model.UpdateTimelineEventInput) (*model.TimelineEvent, error) {
	event, err := r.Timeline.UpdateTimelineEvent(ctx, orgID, serviceID, eventID, convert.UpdateTimelineEventInputToBody(input))
	if err != nil {
		return nil, err
	}
	return convert.TimelineEventToModel(event), nil
}

// DeleteTimelineEvent is the resolver for the deleteTimelineEvent field.
func (r *mutationResolver) DeleteTimelineEvent(ctx context.Context, orgID string, serviceID string, eventID string) (bool, error) {
	if err := r.Timeline.DeleteTimelineEvent(ctx, orgID, serviceID, eventID); err != nil {
		return false, err
	}
	return true, nil
}

// ServiceTimelineEvents is the resolver for the serviceTimelineEvents field.
func (r *queryResolver) ServiceTimelineEvents(ctx context.Context, orgID string, serviceID string) ([]*model.TimelineEvent, error) {
	events, err := r.Timeline.ListServiceTimelineEvents(ctx, orgID, serviceID)
	if err != nil {
		return nil, err
	}
	return convert.TimelineEventListToModel(events), nil
}

// AttachmentURL is the resolver for the attachmentUrl field.
func (r *timelineEventResolver) AttachmentURL(ctx context.Context, obj *model.TimelineEvent) (*string, error) {
	if obj.AttachmentAssetID == nil {
		return nil, nil
	}
	return r.resolveAssetURL(ctx, obj.OrgID, *obj.AttachmentAssetID)
}

// TimelineEvent returns generated.TimelineEventResolver implementation.
func (r *Resolver) TimelineEvent() generated.TimelineEventResolver { return &timelineEventResolver{r} }

type timelineEventResolver struct{ *Resolver }
