package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/uigraph/graphql/internal/graph/convert"
	"github.com/uigraph/graphql/internal/graph/generated"
	"github.com/uigraph/graphql/internal/graph/model"
)

// ScreenshotImageURL is the resolver for the screenshotImageUrl field.
func (r *frameResolver) ScreenshotImageURL(ctx context.Context, obj *model.Frame) (*string, error) {
	if obj.ScreenshotAssetID == nil {
		return nil, nil
	}
	return r.resolveAssetURL(ctx, obj.OrgID, *obj.ScreenshotAssetID)
}

// CreatedByActor is the resolver for the createdByActor field.
func (r *frameResolver) CreatedByActor(ctx context.Context, obj *model.Frame) (*model.Actor, error) {
	return r.resolveActor(ctx, obj.OrgID, obj.CreatedBy)
}

// UpdatedByActor is the resolver for the updatedByActor field.
func (r *frameResolver) UpdatedByActor(ctx context.Context, obj *model.Frame) (*model.Actor, error) {
	if obj.UpdatedBy == nil {
		return nil, nil
	}
	return r.resolveActor(ctx, obj.OrgID, *obj.UpdatedBy)
}

// CreateMap is the resolver for the createMap field.
func (r *mutationResolver) CreateMap(ctx context.Context, orgID string, input model.CreateMapInput) (*model.UIMap, error) {
	m, err := r.UIMap.CreateMap(ctx, orgID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.UIMapToModel(m), nil
}

// UpdateMap is the resolver for the updateMap field.
func (r *mutationResolver) UpdateMap(ctx context.Context, orgID string, id string, input model.UpdateMapInput) (*model.UIMap, error) {
	m, err := r.UIMap.UpdateMap(ctx, orgID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.UIMapToModel(m), nil
}

// DeleteMap is the resolver for the deleteMap field.
func (r *mutationResolver) DeleteMap(ctx context.Context, orgID string, id string) (bool, error) {
	return true, r.UIMap.DeleteMap(ctx, orgID, id)
}

// CreateFrame is the resolver for the createFrame field.
func (r *mutationResolver) CreateFrame(ctx context.Context, orgID string, mapID string, input model.CreateFrameInput) (*model.Frame, error) {
	f, err := r.UIMap.CreateFrame(ctx, orgID, mapID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameToModel(f), nil
}

// UpdateFrame is the resolver for the updateFrame field.
func (r *mutationResolver) UpdateFrame(ctx context.Context, orgID string, mapID string, id string, input model.UpdateFrameInput) (*model.Frame, error) {
	f, err := r.UIMap.UpdateFrame(ctx, orgID, mapID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameToModel(f), nil
}

// DeleteFrame is the resolver for the deleteFrame field.
func (r *mutationResolver) DeleteFrame(ctx context.Context, orgID string, mapID string, id string) (bool, error) {
	return true, r.UIMap.DeleteFrame(ctx, orgID, mapID, id)
}

// SyncFrame is the resolver for the syncFrame field.
func (r *mutationResolver) SyncFrame(ctx context.Context, orgID string, mapID string, input model.SyncFrameInput) (*model.SyncFrameResult, error) {
	out, err := r.UIMap.SyncFrame(ctx, orgID, mapID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return &model.SyncFrameResult{
		FrameID:        convert.StrFromMap(out, "frameId"),
		VersionCreated: convert.BoolFromMap(out, "versionCreated"),
	}, nil
}

// CreateFocalPoint is the resolver for the createFocalPoint field.
func (r *mutationResolver) CreateFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFocalPointInput) (*model.FocalPoint, error) {
	fp, err := r.UIMap.CreateFocalPoint(ctx, orgID, mapID, frameID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FocalPointToModel(fp), nil
}

// UpdateFocalPoint is the resolver for the updateFocalPoint field.
func (r *mutationResolver) UpdateFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFocalPointInput) (*model.FocalPoint, error) {
	fp, err := r.UIMap.UpdateFocalPoint(ctx, orgID, mapID, frameID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FocalPointToModel(fp), nil
}

// DeleteFocalPoint is the resolver for the deleteFocalPoint field.
func (r *mutationResolver) DeleteFocalPoint(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.UIMap.DeleteFocalPoint(ctx, orgID, mapID, frameID, id)
}

// UpsertCanvas is the resolver for the upsertCanvas field.
func (r *mutationResolver) UpsertCanvas(ctx context.Context, orgID string, mapID string, input model.UpsertCanvasInput) (*model.Canvas, error) {
	body := convert.ToMap(input)
	if fp, ok := body["framePositions"].(string); ok {
		var raw interface{}
		if err := convert.UnmarshalJSONString(fp, &raw); err == nil {
			body["framePositions"] = raw
		}
	}
	c, err := r.UIMap.UpsertCanvas(ctx, orgID, mapID, body)
	if err != nil {
		return nil, err
	}
	return convert.CanvasToModel(c), nil
}

// CreateFrameGroup is the resolver for the createFrameGroup field.
func (r *mutationResolver) CreateFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFrameGroupInput) (*model.FrameGroup, error) {
	g, err := r.UIMap.CreateFrameGroup(ctx, orgID, mapID, frameID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameGroupToModel(g), nil
}

// UpdateFrameGroup is the resolver for the updateFrameGroup field.
func (r *mutationResolver) UpdateFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFrameGroupInput) (*model.FrameGroup, error) {
	g, err := r.UIMap.UpdateFrameGroup(ctx, orgID, mapID, frameID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameGroupToModel(g), nil
}

// DeleteFrameGroup is the resolver for the deleteFrameGroup field.
func (r *mutationResolver) DeleteFrameGroup(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.UIMap.DeleteFrameGroup(ctx, orgID, mapID, frameID, id)
}

// CreateFrameLink is the resolver for the createFrameLink field.
func (r *mutationResolver) CreateFrameLink(ctx context.Context, orgID string, mapID string, frameID string, input model.CreateFrameLinkInput) (*model.FrameLink, error) {
	l, err := r.UIMap.CreateFrameLink(ctx, orgID, mapID, frameID, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameLinkToModel(l), nil
}

// UpdateFrameLink is the resolver for the updateFrameLink field.
func (r *mutationResolver) UpdateFrameLink(ctx context.Context, orgID string, mapID string, frameID string, id string, input model.UpdateFrameLinkInput) (*model.FrameLink, error) {
	l, err := r.UIMap.UpdateFrameLink(ctx, orgID, mapID, frameID, id, convert.ToMap(input))
	if err != nil {
		return nil, err
	}
	return convert.FrameLinkToModel(l), nil
}

// DeleteFrameLink is the resolver for the deleteFrameLink field.
func (r *mutationResolver) DeleteFrameLink(ctx context.Context, orgID string, mapID string, frameID string, id string) (bool, error) {
	return true, r.UIMap.DeleteFrameLink(ctx, orgID, mapID, frameID, id)
}

// CreateFocalPointMeta is the resolver for the createFocalPointMeta field.
func (r *mutationResolver) CreateFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, input model.CreateFocalPointMetaInput) (*model.FocalPointMeta, error) {
	m, err := r.UIMap.CreateFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, convert.FocalPointMetaBody(convert.ToMap(input)))
	if err != nil {
		return nil, err
	}
	return convert.FocalPointMetaToModel(m), nil
}

// UpdateFocalPointMeta is the resolver for the updateFocalPointMeta field.
func (r *mutationResolver) UpdateFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, id string, input model.UpdateFocalPointMetaInput) (*model.FocalPointMeta, error) {
	m, err := r.UIMap.UpdateFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, id, convert.FocalPointMetaBody(convert.ToMap(input)))
	if err != nil {
		return nil, err
	}
	return convert.FocalPointMetaToModel(m), nil
}

// DeleteFocalPointMeta is the resolver for the deleteFocalPointMeta field.
func (r *mutationResolver) DeleteFocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string, id string) (bool, error) {
	return true, r.UIMap.DeleteFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID, id)
}

// Maps is the resolver for the maps field.
func (r *queryResolver) Maps(ctx context.Context, orgID string, folderID *string) ([]*model.UIMap, error) {
	fid := ""
	if folderID != nil {
		fid = *folderID
	}
	maps, err := r.UIMap.ListMaps(ctx, orgID, fid)
	if err != nil {
		return nil, err
	}
	return convert.UIMapsToModel(maps), nil
}

// Map is the resolver for the map field.
func (r *queryResolver) Map(ctx context.Context, orgID string, id string) (*model.UIMap, error) {
	m, err := r.UIMap.GetMap(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.UIMapToModel(m), nil
}

// Frames is the resolver for the frames field.
func (r *queryResolver) Frames(ctx context.Context, orgID string, mapID string) ([]*model.Frame, error) {
	frames, err := r.UIMap.ListFrames(ctx, orgID, mapID)
	if err != nil {
		return nil, err
	}
	return convert.FramesToModel(frames), nil
}

// Frame is the resolver for the frame field.
func (r *queryResolver) Frame(ctx context.Context, orgID string, mapID string, id string) (*model.Frame, error) {
	f, err := r.UIMap.GetFrame(ctx, orgID, mapID, id)
	if err != nil {
		return nil, err
	}
	return convert.FrameToModel(f), nil
}

// FrameByID is the resolver for the frameById field.
func (r *queryResolver) FrameByID(ctx context.Context, orgID string, id string) (*model.Frame, error) {
	f, err := r.UIMap.GetFrameByID(ctx, orgID, id)
	if err != nil {
		return nil, err
	}
	return convert.FrameToModel(f), nil
}

// FocalPoints is the resolver for the focalPoints field.
func (r *queryResolver) FocalPoints(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FocalPoint, error) {
	fps, err := r.UIMap.ListFocalPoints(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return convert.FocalPointsToModel(fps), nil
}

// Canvas is the resolver for the canvas field.
func (r *queryResolver) Canvas(ctx context.Context, orgID string, mapID string) (*model.Canvas, error) {
	c, err := r.UIMap.GetCanvas(ctx, orgID, mapID)
	if err != nil {
		return nil, err
	}
	return convert.CanvasToModel(c), nil
}

// FrameGroups is the resolver for the frameGroups field.
func (r *queryResolver) FrameGroups(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FrameGroup, error) {
	groups, err := r.UIMap.ListFrameGroups(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return convert.FrameGroupsToModel(groups), nil
}

// FrameLinks is the resolver for the frameLinks field.
func (r *queryResolver) FrameLinks(ctx context.Context, orgID string, mapID string, frameID string) ([]*model.FrameLink, error) {
	links, err := r.UIMap.ListFrameLinks(ctx, orgID, mapID, frameID)
	if err != nil {
		return nil, err
	}
	return convert.FrameLinksToModel(links), nil
}

// FocalPointMeta is the resolver for the focalPointMeta field.
func (r *queryResolver) FocalPointMeta(ctx context.Context, orgID string, mapID string, frameID string, focalPointID string) ([]*model.FocalPointMeta, error) {
	metas, err := r.UIMap.ListFocalPointMeta(ctx, orgID, mapID, frameID, focalPointID)
	if err != nil {
		return nil, err
	}
	return convert.FocalPointMetasToModel(metas), nil
}

// Frame returns generated.FrameResolver implementation.
func (r *Resolver) Frame() generated.FrameResolver { return &frameResolver{r} }

type frameResolver struct{ *Resolver }
